### ISSUE TITLE
Retrive calendar by country name/abbreviation

### ISSUE THREAD

**Issue by roberto-fierimonte** [dr-prodigy/python-holidays#100]
In many occasions the country for which we want to retrive the calendar is a parameter of the program/analysis itself so don't want to hardcode an infinite list of `if ... elif`.

Is it possible to have a function like `get_calendar(country)`, from which we can retrive a calendar class by passing a string with the country name/abbreviation?

Thanks

**Comment by skunca** [comment]
It would be nice to have a simple way of doing this out of the box but this is also possible by dynamically loading the class you need:

    import holidays

    country = 'US'
    CountryHolidays = getattr(holidays, country)
    country_holidays = CountryHolidays()

**Comment by dr-prodigy** [comment]
Just done! Thx to both ;)
