### ISSUE TITLE
"RuntimeError: Set changed size during iteration" in version 0.20

### ISSUE THREAD

**Issue by lunarflint** [dr-prodigy/python-holidays#1005]
Hello, I would like to report a bug when doing the following:
```holidays.financial_holidays('NYSE', years=2020)```

It will give  `RuntimeError: Set changed size during iteration` in version 0.20

I reverted to version 0.19 and it works again, tested on miniconda3 on win server.

**Comment by arkid15r** [comment]
HI @lunarflint,
thanks for reporting this!

The good news is that the issue has already been addressed in https://github.com/dr-prodigy/python-holidays/pull/1000

You might be interested in using beta (0.21)
`pip install --upgrade https://github.com/dr-prodigy/python-holidays/tarball/beta`

I hope to release the 0.21 today.
