### ISSUE TITLE
I am sure that is not more a holiday in Ukraine

### ISSUE THREAD

**Issue by foxtrot-dfm1** [dr-prodigy/python-holidays#1009]
https://github.com/dr-prodigy/python-holidays/blob/d4cfc391d1562f33f8be9fd692c85a97544786ad/holidays/locale/uk/LC_MESSAGES/UA.po#L86

**Comment by PPsyrius** [comment]
It's there for historical coverage with date trigger for pre-2000:
```python
        # October Revolution
        if year <= 1999:
            name = self.tr(
                "Річниця Великої Жовтневої соціалістичної революції"
            )
            _add_with_observed(date(year, NOV, 7), name, days=2)
            _add_with_observed(date(year, NOV, 8), name, days=2)
```

**Comment by foxtrot-dfm1** [comment]
> It's there for historical coverage with date trigger for pre-2000:
> 
> ```python
>         # October Revolution
>         if year <= 1999:
>             name = self.tr(
>                 "Річниця Великої Жовтневої соціалістичної революції"
>             )
>             _add_with_observed(date(year, NOV, 7), name, days=2)
>             _add_with_observed(date(year, NOV, 8), name, days=2)
> ```

Okay thanks for explaining
