### ISSUE TITLE
Question: python way to get list of all supported countries

### ISSUE THREAD

**Issue by laurent-brisbois** [dr-prodigy/python-holidays#1022]
Hello !

I have a strong interest in this library and I was wondering whether there is a way to get a list of all supported countries ?

Thanks in advance !

**Comment by KJhellico** [comment]
Hello @laurent-brisbois! There is a function `list_supported_countries()` for this purpose. For example:
```
import holidays
countries = holidays.list_supported_countries()
```

**Comment by laurent-brisbois** [comment]
@KJhellico 
Ok thanks and sorry, I didn't see it while browsing the repo !

Perfect 👌 !
