### ISSUE TITLE
Should province and state be synonyms?

### ISSUE THREAD

**Issue by achim0308** [dr-prodigy/python-holidays#108]
Hi,

shouldn't states and provinces be synonyms so that they can be used interchangeably? 

For example, so that
holidays.DE(state='BW') == holidays.DE(prov='BW') # True

Regards,
Achim

**Comment by dr-prodigy** [comment]
Hi,
functionally, states and provinces behave and work the same, in that you have specific holidays for a given state or province among all the ones belonging to a country.

On the other hand, "state" concept makes sense for, for instance, USA, but makes no sense in "normal" countries (ie: not federal union or similar), so it's correct to keep them separated.

Thank you regards
Maurizio

**Comment by achim0308** [comment]
Hi Maurizio,

In case of Germany then, states should be permitted as it is a federal country. Thus, can you reopen the issue.

Best regards,
Achim

Am 17. Apr. 2018, 13:30 +0200 schrieb Maurizio Montel <notifications@github.com>:

**Comment by dr-prodigy** [comment]
Okay, but in this case, for Germany we should move from provinces (as-is) to states, breaking compatibility with lib previous versions..
At the time this would carry more cons than pros, so we will consider this in case of a remarkable refactoring.
Thank you very much
