### ISSUE TITLE
Push archive of 0.9.5 to PyPI

### ISSUE THREAD

**Issue by fabaff** [dr-prodigy/python-holidays#109]
Please push 0.9.5 as archive to PyPI. Thanks.

**Comment by fabaff** [comment]
Yes, it has but only the .egg is available.

**Comment by dr-prodigy** [comment]
Okay, now everything should be in place! Pls let me know, thank you!

**Comment by fabaff** [comment]
Works. At least for https://github.com/home-assistant/home-assistant/pull/14274. Thanks for your effort.
