### ISSUE TITLE
Easter Sunday is a holiday in all of Germany, not only in Brandenburg.

### ISSUE THREAD

**Issue by Achimh3011** [dr-prodigy/python-holidays#110]
For some reason I don't understand `python-holidays` only defines Easter Sunday for `country == 'DE'` as holiday in `prov = 'BB'` which I guess means _Brandenburg_. Easter Monday and Good Friday are (correctly) set up for entire Germany. 

I'm not aware of any special regulation in _Brandenburg_, so I'd say this is a bug. Of course, Easter Sunday is always a Sunday, so the consequences aren't that great from a work time perspective, but anyhow...

P.S.: https://www.youtube.com/watch?v=kdwKbiMyvu0

P.P.S: Same issue with Pentecost (_Pfingstsonntag_)...

**Comment by dr-prodigy** [comment]
Thank you: it will be fixed in the next release.

**Comment by dr-prodigy** [comment]
Released in v.0.9.6. Thank you

**Comment by karlsebal** [comment]
This is not true. Easter Sunday and Whit Sunday are Holidays only in BB (Berlin-Brandenburg). For HE (Hessen) every Sunday is a holiday.

https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland
