### ISSUE TITLE
Time span performance

### ISSUE THREAD

**Issue by jbmoorhouse** [dr-prodigy/python-holidays#1107]
Firstly, thank you for producing a great library! This tool is invaluable!

## Problem

Was curious if the following performance characteristics are expected, or if there is scope to enhance lazy loading?

```python
In [1]: import holidays

In [2]: %timeit holidays.country_holidays("GB", years=range(2000, 2100))
2.14 ms ± 4.18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Vs manually querying each year. For my use case, I would prefer to be able query holidays lazily (for a given year), vs eagerly loading a given time period.

```python
In [3]: def manual():
    ...:     for year in range(2000, 2100):
    ...:         holidays.country_holidays("GB", years=year)

In [4]: %timeit manual()
11.1 ms ± 993 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by dr-prodigy** [comment]
Hi,
thank you for your appreciation in our lib :-)

I hope I'm catching it right, but in fact, in python_holidays' standard usage you shouldn't definitely need to pre-initialize a year range.
Here's a sample code to check a date, as taken from [here](https://github.com/dr-prodigy/python-holidays#quick-start):
```
from datetime import date
import holidays

us_holidays = holidays.US()  # this is a dict
date(2015, 1, 1) in us_holidays  # True
```
As you can see, it is sufficient to check presence of a specific date in a holidays dict to have it initialized for that year.
Does this answer your question out?

**Comment by jbmoorhouse** [comment]
Hello,

Thank you for you reply,

It looks like `%timeit` may have been disguising some caching

```python
In [1]: def manual():
    ...:     for i in range(2000, 2100):
    ...:         holidays.country_holidays("GB", years=i)
    ...: 

In [2]: %time _ = manual()
CPU times: user 183 ms, sys: 8.08 ms, total: 191 ms
Wall time: 193 ms

In [3]: %time _ =  holidays.country_holidays("GB", years=range(2000, 2100))
CPU times: user 124 ms, sys: 0 ns, total: 124 ms
Wall time: 123 ms

**Comment by jbmoorhouse** [comment]
Happy to close :+1:

**Comment by dr-prodigy** [comment]
Thank you!
