### ISSUE TITLE
Buß- und Bettag was a Germany-wide holiday from 1990-1994

### ISSUE THREAD

**Issue by Achimh3011** [dr-prodigy/python-holidays#111]
Hi,

from 1990 until 1994, _Buß- und Bettag_ was a Germany-wide holiday after which it was removed except for federal state Saxonia (`prov == 'SN'). `python-holidays` incorrectly lists it as a Saxonia-specific holiday from 1990 onward.

https://en.wikipedia.org/wiki/Bu%C3%9F-_und_Bettag#As_a_statutory_non-working_holiday
https://de.wikipedia.org/wiki/Bu%C3%9F-_und_Bettag#Abschaffung

**Comment by dr-prodigy** [comment]
Okay, will be fixed in next release, thank you

**Comment by dr-prodigy** [comment]
Fixed in just released v.0.9.6. Thank you
