### ISSUE TITLE
Depend on hijridate rather than hijri-converter

### ISSUE THREAD

**Issue by metrizable** [dr-prodigy/python-holidays#1123]
Greetings `holidays` maintainers! Thanks for making working with the world's holidays in Python fast and flexible.

I see that `hijri-converter` has been [deprecated](https://pypi.org/project/hijri-converter/) and [`hijridate`](https://pypi.org/project/hijridate/) is the recommended dependency to take. Are there plans to migrate to `hijridate` in the near future?

**Comment by dralshehri** [comment]
Currently, both packages `hijri-coverter` and `hijridate` are fully compatible except for the name, which only requires replacement.

Additionally, to avoid breaking changes or issues such as #1127 in the future, I highly recommend specifying the required version to a compatible version, e.g. `hijridate~=2.3.0`

**Comment by arkid15r** [comment]
`hijridate` is now a source for estimated Islamic holidays.

Thank you!
