### ISSUE TITLE
ImportError after updating to newer version

### ISSUE THREAD

**Issue by provinzio** [dr-prodigy/python-holidays#1127]
I updated from holidays==0.11.1 to 0.23 and got the following error

```
Exception has occurred: ImportError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
cannot import name 'GREGORIAN_RANGE' from 'hijri_converter.ummalqura' (d:\workspace\cerox\venv\lib\site-packages\hijri_converter\ummalqura.py)
```

I installed hijri-converter==2.3.1 manually to fix it.

I propose to add a constraint to the version of hijri-converter in setup.cfg

may be related to #425

**Comment by dralshehri** [comment]
I believe that's a pip cache issue. When the `hijri-converter` package is required without a version specifier, the pip tends to install a cached version, which could be missing new features used.

To solve this temporarily, run `pip install -U hijri-converter`.

However, as you said, the required version should be specified in `setup.cfg`.

**Comment by arkid15r** [comment]
This dependency is no longer in use for the recent PH version(s).
Please upgrade if possible.

Thank for reporting this.
