### ISSUE TITLE
pull date range

### ISSUE THREAD

**Issue by samuel-1985** [dr-prodigy/python-holidays#113]
Hi

I am a newbie to this library and I tried to find the holidays in a date range that started from date A to date B in Canada.
 for example, this is what I would do with the U.S. holidays:

from pandas.tseries.holiday import USFederalHolidayCalendar as calendar
cal = calendar()
holidays = cal.holidays(start='05-13-2014, end=05-13-2016)
print(holidays)

I would appreciate if you help me with that.

Regards

**Comment by philwech** [comment]
I solved the problem outside. But it could be a nice function for the library.

def holidays_from_range(lower_date, upper_date, prov):
    # smallest and biggest year
    smallest_year = lower_date.year
    biggest_year = upper_date.year
    # list_holidays has all holidays
    list_holidays = sorted(holidays.CH(prov=prov, years=range(smallest_year, biggest_year+1)))
    df_holidays = pd.DataFrame(index=list_holidays)
    # return just the holidays between lower- and upper-date
    df_holidays = df_holidays[lower_date:upper_date]
    ls_holidays = []
    for row_index, row in df_holidays.iterrows():
        ls_holidays.append(row_index.strftime('%Y%m%d'))
    return ls_holidays

**Comment by dr-prodigy** [comment]
I will release this solution after some more analysis: thank you very much for your contribution.

**Comment by elln2** [comment]
Hey @dr-prodigy I've got an idea to tackle this, mind if I take a shot and get some feedback if you haven't had a chance to get started?

**Comment by dr-prodigy** [comment]
Hey elln2,
in fact unfortunately I couldn't work on this until now, but still it's an interesting feature.
So, of course, I'll surely be happy to consider/include your work, if you want to contribute in any way.

Thank you very much, cheers!

**Comment by dr-prodigy** [comment]
Thank you very much for your contribution @elln2 .. much appreciated! 👍
