### ISSUE TITLE
Add a list_all_countries_with_translations() function?

### ISSUE THREAD

**Issue by juanitobananas** [dr-prodigy/python-holidays#1138]
Dear python-holiday devs,

First of all, thank you very much for this very useful library and for all the hard work you put in it! :clap:

That said, I'd love if there could be an option to get a list of the countries that have at least one translation (and also get the languages they're translated into).

I'm testing a function I've written, which at first sight seems to be working, but I haven't thoroughly checked it. I assume stuff (explained in the pydocs for the function) that just might be wrong.

If you happen to find some time and feel like it, would you mind taking a quick look at it?

``` python
def list_all_countries_with_translations() -> Dict[str, List[Optional[str]]]:
    """
    Recursively search for all .po files in python-holidays's locale dir.
    Assume the filename is the country code the parent's parent dir is the language.

    The structure looks like this:

    holidays/locale/{lang}/LC_MESSAGES/{country_code}.po

    Returns a dict whose keys are the country_codes and whose values are the list of
    languages that are available for that country.

    Beware that countries without any translation won't have their key present in
    the resulting dictionary.
    """
    module_dir = os.path.dirname(os.path.abspath(holidays.__file__))
    locale_dir = os.path.join(module_dir, 'locale')
    country_codes = {}
    for root, dirs, files in os.walk(locale_dir):
        for file in files:
            if file.endswith('.po'):
                country_code = re.sub(r'(.*)\.po', r'\1', file)
                lang = os.path.basename(os.path.dirname(root))
                country_codes.setdefault(country_code, []).append(lang)
    return dict(sorted(country_codes.items()))
```

If you like the idea, and feel like adding it to `holidays`, please feel free to do so. If not, it doesn't really bother me having it somewhere in my python code. I am just not sure if my assumptions are correct.

P.D.- As to why I'd like to have something like this. I was looking for an ICS URL for the city I live in so that I could subscribe to it. And just couldn't find it, which brought me to trying to generate one. Which brought me to your lib. And it worked great! Then I thought I might as well just export all ICS files and publish them. So I ended up creating a super simple GitLab page[1] so that I can set my calendar apps to update from there periodically :shrug:

[Holy Moly Days!](https://holymolydays.gitlab.io/)

And I though I could add the translations whenever available... :blush:

**Comment by arkid15r** [comment]
Hi @juanitobananas, thanks for your request!

This is totally valid idea that should be implemented as our l10n approach has been in place for a while and seems to be working fine. We could reuse the code you kindly provided (or similar, depending on the implementation details) to close https://github.com/dr-prodigy/python-holidays/issues/984 as well.

I guess these are the parts of PH you might find useful:
  - https://github.com/dr-prodigy/python-holidays/blob/master/holidays/holiday_base.py#L291
  - https://github.com/dr-prodigy/python-holidays/blob/master/scripts/l10n/generate_mo_files.py#L25
  
or just wait until the `utils::list_localized_countries()` is implemented.

Your project looks great and the name is lit 🔥

**Comment by juanitobananas** [comment]
Hey @arkid15r, thanks for getting back to me that fast!

> This is totally valid idea that should be implemented as our l10n approach has been in place for a while and seems to be working fine. 

Nice!

> We could reuse the code you kindly provided (or similar, depending on the implementation details) to close https://github.com/dr-prodigy/python-holidays/issues/984 as well.

If it's worth anything, please do so :smile:

> I guess these are the parts of PH you might find useful:

    https://github.com/dr-prodigy/python-holidays/blob/master/holidays/holiday_base.py#L291
    https://github.com/dr-prodigy/python-holidays/blob/master/scripts/l10n/generate_mo_files.py#L25

Thanks, I'll take a closer look at that.

> or just wait until the utils::list_localized_countries() is implemented.

And will most probably still wait for this. For the moment, my code seems to work. Well enough for the (very probably) sole user :wink:

Again, thank you very much!

Cheers

**Comment by arkid15r** [comment]
Okay, the #1185 with `utils::list_localized_countries()`has just been merged into beta.

**Comment by juanitobananas** [comment]
Beautiful! Thank you so much for that!

I haven't had time to test it out until now. And I had completely forgotten how everything worked. Fortunately, I can just use it as a drop-in replacement of my own code :wink: 

Thank you so much again!

**Comment by arkid15r** [comment]
Sure!

Thanks for the suggestion @juanitobananas, it was quite valuable 👍
