### ISSUE TITLE
Canada Day vs. Dominion Day

### ISSUE THREAD

**Issue by endlisnis** [dr-prodigy/python-holidays#114]
You currently report Canada Day as being valid all the way back to 1867, but before 1983, the holiday was called "Dominion Day".

Also, it was not a statutory holiday until 1879, which means there should be no "(Observed)" version of Dominion Day before 1879.

**Comment by dr-prodigy** [comment]
Okay, all clear.. will fix it in next release.
I assume these considerations are valid both for NL province (whose holiday is currently named "Canada Day") and for other provinces (whose holiday is named "Memorial Day").
Hope this makes sense: otherwise we'll rearrange code consequently.
Thank you

**Comment by dr-prodigy** [comment]
Released in v.0.9.6. Thank you
