### ISSUE TITLE
Holidays for state BW in Germany are missing (?)

### ISSUE THREAD

**Issue by rdorsch** [dr-prodigy/python-holidays#115]
Hi,

thanks for coming up with this nice package, I am using 0.9.5 from Debian :-)

I just realized, that the holidays for BW in Germany are incomplete:

```
import holidays
        
bw_holidays = holidays.DE(state='BW',years=2018)

for date, name in sorted(bw_holidays.items()):
    print(date, name)

```
results in
```

rd@b370:~$ python3 test-holidays.py 
2018-01-01 Neujahr
2018-03-30 Karfreitag
2018-04-02 Ostermontag
2018-05-01 Maifeiertag
2018-05-10 Christi Himmelfahrt
2018-05-21 Pfingstmontag
2018-10-03 Tag der Deutschen Einheit
2018-12-25 Erster Weihnachtstag
2018-12-26 Zweiter Weihnachtstag
rd@b370:~$ 
```

A full list is give e.g. here:

[https://www.schulferien.org/Feiertage/Feiertage_Baden_Wuerttemberg.html](url)

**Comment by rdorsch** [comment]
I just realized that I need

holidays.DE(### prov='BW',years=2018)

**Comment by dr-prodigy** [comment]
Done, thank you
