### ISSUE TITLE
Not able to access Indian Holidays

### ISSUE THREAD

**Issue by Yogeshnaik1190** [dr-prodigy/python-holidays#117]
I am trying to run holidays.IND() for Indian Holidays but it is showing me following error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-106-630d746aaa1c> in <module>()
----> 1 holidays.IND()

AttributeError: module 'holidays' has no attribute 'IND'

please suggest any solution for this.

**Comment by dr-prodigy** [comment]
Hi,
unfortunately, indian holidays still have to be released in PyPi lib release.
Either wait for the current source version to be released in PyPi, or use it through sources (which already contain indian holidays implementation).

**Comment by dr-prodigy** [comment]
Just released v.0.9.6 to pypi. Thanks

**Comment by Yogeshnaik1190** [comment]
Thanks.

**Comment by emeraldev** [comment]
Hi, 
I am getting similar error when I run the following 

`from datetime import date 
import holidays 

uk_holidays = holidays.UnitedKingdom() 

for ptr in holidays.UnitedKingdom(years = 2020).items(): 
	print(ptr) 
`
Error: AttributeError: module 'holidays' has no attribute 'UnitedKingdom'

May you please advise on a solution
