### ISSUE TITLE
Push archive of 0.9.6 to PyPI

### ISSUE THREAD

**Issue by fabaff** [dr-prodigy/python-holidays#119]
Could you please push 0.9.6 as archive to PyPI? At the moment only the .egg is available.

Thanks.

Is required by https://github.com/home-assistant/home-assistant/pull/15831

**Comment by dr-prodigy** [comment]
Thank you for your issue reporting: I've just released 0.9.6 with tar.gz format.
Pls let me know, thanks

**Comment by fabaff** [comment]
Works.

Thanks again for your fast reaction.
