### ISSUE TITLE
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by Gobi2511** [dr-prodigy/python-holidays#1200]
When using the latest version of the holidays, getting the following error. 

`File "/usr/local/airflow/.local/lib/python3.7/site-packages/prophet/hdays.py", line 683, in <module>
    class TU(Turkey):
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/holidays/registry.py", line 178, in __init__
    super().__init__(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)`

Please help someone to fix this issue in the holidays module

**Comment by dadwin** [comment]
+1 -  v0.25 does't work for me, but v0.24 was OK.

**Comment by milesDashFuel** [comment]
+1 v0.25 doesn't work for me either

**Comment by F1nalFortune** [comment]
+1 Holidays v0.24 worked for me - fixed the prophet issue

**Comment by arkid15r** [comment]
This was ddressed in https://github.com/dr-prodigy/python-holidays/pull/1208
Please use v0.24 as a workaround or let me know if you need help w/ class inheritance migration.
