### ISSUE TITLE
Missing: Victoria Day (Nova Scotia, Canada)

### ISSUE THREAD

**Issue by program-the-brain-not-the-heartbeat** [dr-prodigy/python-holidays#1214]
Looks like most provinces in https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/canada.py have Victoria Day listed.

Victoria Day is also celebrated here in Nova Scotia but there is no reference in the _add_subdiv_ns_holidays function.

**Comment by PPsyrius** [comment]
I'm afraid that isn't the case according to [RCC](https://www.retailcouncil.org/province/national/victoria-day-retail-hours/):
> "Nova Scotia: Despite provincial tradition, Victoria Day is not a statutory holiday nor is it a retail closing day. This creates confusion in the province as many Nova Scotia businesses close for Victoria Day and some even provide their employees with a paid day off."

**Comment by arkid15r** [comment]
Hi @program-the-brain-not-the-heartbeat,
could you provide some additional information or references to look into in order to confirm the claim?

Thank you!

**Comment by program-the-brain-not-the-heartbeat** [comment]
Sorry for the delay, my apologies. It is a non-statutory holiday.

Wasn't sure if this library considers non-statutory holidays as holidays or not.
