### ISSUE TITLE
Adding Israeli holidays

### ISSUE THREAD

**Issue by tsehori** [dr-prodigy/python-holidays#122]
I'd like to suggest adding Israeli holidays.
Note that Israel has a few different calendars for holidays: they are not different between states (no states in Israel) but rather between religions: Jewish, Christian and Muslim holidays are all different.
Furthermore, they don't all follow the Georgian calendar. Libraries such as [pyluach](https://github.com/simlist/pyluach) might be convenient in implementing these holidays.
I will try to address the issue, and update accordingly.

**Comment by dr-prodigy** [comment]
Hi,
contributions are welcome!
I'll be waiting for yours, thank you very much
