### ISSUE TITLE
Adding a Singapore Calendar

### ISSUE THREAD

**Issue by popsyann** [dr-prodigy/python-holidays#123]
Similarly to what has been requested for Israel, Singapore public holidays are made of fixed dates (New Year, Labour day, National Day and Christmas). Other public holidays are "religious" celebrations taken from muslim, Hinddu and Buddhist calendars). These "religious" celebrations vary every year but the Ministry of Manpower in Singapore publishes the official public holidays with 1 year in advance (currently published are 2018 and 2019).
There is no accurate way to calculate (or I do not know it) what will be the dates for these religious holidays for 2020 and beyond. Which means that this library, if it is created will have to be updated at the beginning or every year.

I have prepared a SG class covering 2018 and 2019. I could submit it but I will need some guidance as I am a newbie to all this (Github, python,...)
Here is the code:

`# -*- coding: utf-8 -*-

class Singapore(HolidayBase):
    PROVINCES = []

    def __init__(self, **kwargs):
        self.country = 'SG'
        HolidayBase.__init__(self, **kwargs)

    def _populate(self, year):
    # Singapore became independent on 9th August 1965
        if year < 1965:
            return

        # New Year's Day
        name = "New Year's Day"
        jan1 = date(year, 1, 1)
        self[jan1] = name
        # If New year falls on Sunday, Monday becomes public Holiday
        if self.observed and jan1.weekday() == 6:
            self[date(year, 1, 2)] = name + " (Observed)"

        # Chinese New Year
        name = "Chinese New Year (1)"
        if year == 2018:
            self[date(year, 2, 16) = name
        if year == 2019:
            self[date(year, 2, 5) = name

        # Chinese New Year
        name = "Chinese New Year (2)"
        if year == 2018:
            self[date(year, 2, 17) = name
        if year == 2019:
            self[date(year, 2, 6) = name

        # Good Friday
        self[easter(year) + rd(weekday=FR(-1))] = "Good Friday"

        # Labour Day
        name = "Labour Day"
        # Started being celebrated in 1960 after People Action Party went into power
        # Reference Wikipedia (Labour Day Singapore)
        if year >= 1960:
            self[date(year, 5, 1) = name
        # if Labour day falls on a Sunday, Monday is observed
        if self.observed and may1.weekday() == 6:
            self[date(year, 5, 2)] = name + " (Observed)"

        # Vesak Day
        name = "Vesak day"
        if year == 2018:
            self[date(year, 5, 29) = name
        if year == 2019:
            self[date(year, 5, 19) = name

        # Hari Raya Puasa
        # End of Ramadan
        name = "Hari Raya Puasa"
        if year == 2018:
            self[date(year, 6, 15) = name
        if year == 2019:
            self[date(year, 6, 5) = name

        # National Day
        if year > 1965:
            name = "National Day"
            aug9 = date(year, 8, 9)
            self[feb6] = name
        # if National day falls on a Sunday, Monday is observed
            if self.observed and year >= 1965 and aug9.weekday() == 6:
                self[date(year, 8, 10)] = name + " (Observed)"

        # Hari Raya Hadji
        # First day of muslim pilgrimage to Mecca
          name = "Hari Raya Hadji"
          if year == 2018:
              self[date(year, 8, 22) = name
          if year == 2019:
              self[date(year, 8, 11) = name

        # Deepavali
          name = "Deepavali"
          if year == 2018:
              self[date(year, 11, 6) = name
          if year == 2019:
              self[date(year, 10, 27) = name

        # Christmas Day
        name = "Christmas Day"
        dec25 = date(year, 12, 25)
        self[dec25] = name
        # if Christms day falls on a Sunday, Monday is observed
        if self.observed and dec25.weekday() == 6 :
            self[date(year, 12, 26)] = name + " (Observed)"

class SG(Singapore):
    pass
`

**Comment by dr-prodigy** [comment]
Hi,
thank you for your work.

Unfortunately, IMHO, a good library (or sw in general) is supposed to work as-is for a reasonable time (say: 10 years at least?) with no need for mandatory upgrades (which *could* instead be applied in case of bug fixing or more functionalities added / needed).
Moreover, a future release could, for other reasons, break compatibility with previous versions: this would impose code refactoring to anyone using it, only to keep it working from a year to the next.

For these reasons, I have to say that this approach (ie: impose a new release every year to include new year's data) is not acceptable in the official version.
But, of course, we still can receive logic for all the fixed and known holidays.

Then, I would suggest you to:
- create your own fork of the library
- add and commit your code there
so you can play around and test everything with no harm and, when you're done, we will be able to separate and include the compliant part of the code in the mainstream.

This way (which, btw, is the "standard" :) ) you still can stick to your custom version if the official library doesn't cover all your needs.

Thank you very much, best regards

**Comment by popsyann** [comment]
Hi
Thank you for your quick answer. I understand your point (work as-is for a reasonable time).
If I create my own fork, will I be able to use it for the works I do in my home automation (Home Assistant binary_sensor.workday_sensor)? (This is my main objective in trying to build this "Singapore" Class).
I will follow your recommendation anyway and try my best to come out with something viable.

Best regards

**Comment by Achimh3011** [comment]
The 10+ years stability will not work with other holidays as well (e.g., the newly introduced "Reformationstag" holiday in Germany (single occurence holiday for entire Germany with one year lead time, newly set up holiday in parts later on).

Given that, definition of holidays two years in advance does not sound so bad...

I think it's important to be clear with what users can expect from the library and that holidays are a moving (sometimes even fast moving) target.

**Comment by dr-prodigy** [comment]
I see the point, but - still - an exception can't become rule.

As a standard library, python-holidays - of course - will always try to reflect any change that will occur in the future.
On the other hand, it must be up to users whether to update or not, which means, as a rule of thumb, it will never impose cadenced updating to remain operational.

As I already explained in a direct email to popsyann, a good approach to these use cases would be to integrate external services providing the requested data as soon as they become available (ie: consume some holiday web service) but, being an impacting and disruptive modification, at least for now, we must consider it out of scope.

**Comment by dr-prodigy** [comment]
PS @popsyann : of course, you will be able to use your library fork if needed, either installing it manually with a "git clone .." or, if using virtualenv or similar, also adding your repo to project through requirement files.
Some info here:
[https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source](url)
Please keep me updated, thx!
