### ISSUE TITLE
Missing Orthodox Good Friday in Greece national holiday

### ISSUE THREAD

**Issue by DBoudart23** [dr-prodigy/python-holidays#1255]
Hello team,
I was looking at your package's data and noticed one missing day for Greece.

Source: https://www.officeholidays.com/countries/greece/2022
Missing day: 2023 Fri, Apr 14 National Holiday (Orthodox Good Friday)

Would it be possible to include it in your package, please?

Best regards,
David Boudart

**Comment by arkid15r** [comment]
Hi @DBoudart23,
I guess somebody will volunteer and fix this soon as it's quite simple and straightforward.

Huge thanks for reporting this, David!

**Comment by DBoudart23** [comment]
Thank you!!

**Comment by arkid15r** [comment]
It'll be available starting v0.26 that's going to be released today.
