### ISSUE TITLE
Multi-locale support

### ISSUE THREAD

**Issue by Gennady-Andreyev** [dr-prodigy/python-holidays#126]
Hello there!

As long as the library provides verbose human-readable pieces of text (names of holidays), it would make a lot of sense to make that locale-aware. It is especially relevant for countries that have several official languages (like Switzerland, Canada or Belarus).

I see the simplest implementation as adding another parameter to `HolidayBase.__init__`  as well as the respective `get()` and its variations.

```
>>> h = holidays.Canada()
>>>  h.get('2018-09-03')
Labour Day

>>> h.get('2018-09-03', locale='fr_CA')
Fête du travail
```
Would love to hear if that sounds reasonable...

Thank you!

**Comment by dr-prodigy** [comment]
Well it sure is reasonable.. thank you!
We should theoretically complete this new feature by managing all multi-language countries.
I will think of it and let you know ASAP.
Thanks again, best regards

**Comment by dr-prodigy** [comment]
Hi there.. just completed a new release, so it's time to start thinking about next updates..

Could you be possibly providing translations for all Belarus locales? In this case I would be able to implementing this new feature for it.
Then, in the future next countries will hopefully come over..

Please let me know, thank you very much

**Comment by Gennady-Andreyev** [comment]
Thanks for keeping this on the radar!

Sure, I'll be glad to provide the translations for Belarus. Shall I contribute to a branch where you implement multi-locale?

**Comment by dr-prodigy** [comment]
Why, of course: if you want to contribute with this useful feature, I'll surely be glad to support you and include your work in the proj.
Thank you very much, KUTGW!

**Comment by dr-prodigy** [comment]
Closing this issue until somebody will make some work on it ;-)
