### ISSUE TITLE
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by TaherHabib** [dr-prodigy/python-holidays#1260]
Hi, 

I have been using the holidays package since the last six months for my enterprise's project and never have had this issue before:
![image](https://github.com/dr-prodigy/python-holidays/assets/33577096/0bc4345c-2d75-4a00-b98a-46d9fe5b0ea3)

I don't know if this comes from the recent release of version 0.25 or not. But could someone please check on this and help me out. Thanks a ton in advance!

**Comment by TaherHabib** [comment]
Thanks for teh response @ngerald . Do you have some sort of evidence to back this claim? For instance, is this bug a result of introducing entity lazy loading as in https://github.com/dr-prodigy/python-holidays/pull/1087?

**Comment by ngerald** [comment]
This issue on the holidays package repo should serve as evidence: https://github.com/dr-prodigy/python-holidays/issues/1200

**Comment by arkid15r** [comment]
@TaherHabib if it's related to prophet you need to update to the most recent version that has [the issue fixed](https://github.com/facebook/prophet/pull/2431).

If it's something else -- your enterprise project's code needs to be changed to import entries from `holidays.countries` / `holidays.financial` instead of directly from `holidays` for inheritance.

**Comment by TaherHabib** [comment]
Hi @arkid15r, many thanks for responding. 

No, the issue is not related to prophet in this particular case. It is rather that I am creating my enterprise's own holiday class which, by design, inherits from holidays.AT or holidays.DE to populate the standard calendar holidays; and on top, I am adding a few more holidays to the dict which are unique to my enterprise.

It is when the interpreter executes this inheritance code that the error gets generated.

**Comment by TaherHabib** [comment]
Also, your proposed fix doesn't solve my issue. Based on your suggestion, I basically:

changed the class definition/inheritance from this: 
```python
import holidays
class SomeHolidays(holidays.AT)
```

To this:
```python
import holidays
class SomeHolidays(holidays.countries.AT)
```

And now, it gives me this error: ` AttributeError: module 'holidays' has no attribute 'countries'`

I am sure I am making some mistake here in terms of interpreting your suggested solution, could you please elaborate on the matter? Thanks!

**Comment by KJhellico** [comment]
@TaherHabib, please, try
```python
from holidays.countries import AT

class SomeHolidays(AT):
    """
    <Body of the class>
    """
```

**Comment by TaherHabib** [comment]
Thank you @KJhellico for the suggestion. It seems to have worked for me :)

However, now I am faced with a different issue! :/

The inheritance and class initialization works fine now, however, when I call the `MyEnterpriseHolidays` method `get_dict_holidays(self, subdiv)` which basically returns the holiday dictionary (object of SomeHolidays(<country_code: AT or DE>)) based on the country and the subdivision, I get the following error traceback when running for Austria:

![image](https://github.com/dr-prodigy/python-holidays/assets/33577096/6046e44b-0584-4719-8d30-53effb861ee0)

**Line where the error occurs:**
![image](https://github.com/dr-prodigy/python-holidays/assets/33577096/a2157eb6-45e3-48f9-b9aa-b6e79a9125c4)

**Pytest Summary of all tests using `MyEnterpriseHolidays()`:**
![image](https://github.com/dr-prodigy/python-holidays/assets/33577096/43784989-824f-44a9-8f5d-7704bf097354)




**Skeleton of my class:**
```python
from holidays.countries import AT

class MyEnterpriseHolidays():
    def __init__(self, ...):
        # <class attributes incl. `country_code`>
    
    def get_dict_holidays(self, subdiv):
        if self.country_code == 'AT':
            return SomeHolidaysAT(
                        subdiv=subdiv, 
                        years=list(range(some_past_yr, some_future_yr))
                        )
        elif self.country_code == 'DE':
            return SomeHolidaysDE(
                        subdiv=subdiv, 
                        years=list(range(some_past_yr, some_future_yr))
                        )

class SomeHolidaysAT(AT):
    """
    <Body of the class>
    """

class SomeHolidaysDE(DE):
    """
    <Body of the class>
    """
```

Any suggestions on where this might be going wrong or how to fix it? Thanks once again! Really appreciate the help

**Comment by KJhellico** [comment]
This error means that most likely holiday from year **other than `year`** is being added somewhere in `SomeHolidaysAT::_populate()`.

**Comment by TaherHabib** [comment]
@KJhellico Thanks a lot for your inputs. The package now works just fine, as expected, again! :)
