### ISSUE TITLE
setting state/province using CountryHoliday

### ISSUE THREAD

**Issue by luto** [dr-prodigy/python-holidays#128]
Assuming that, `CountryHoliday` is used as described in the README and the country is not know until runtime (e.g. it is read from a config or user input):

```python
import holidays

country = "DE"  # from sys.argv, for example
ch = holidays.CountryHoliday(country)
```

This of course yields a perfectly fine instance. The problem comes up when the state or province is also relevant. Since `CountryHoliday` returns an instance, there is no way to add a state, which is set using the constructor.

A couple of workarounds:

* use `type()` or `.__class__` to get the class; create a new instance
* use `getattr(holidays, country)` to get the class directly, skips the nice error handling

Neither of those seem like a sleek and easy to understand solution to me.

To resolve this, I propose that all keyword arguments to `CountryHoliday` should be passed onto the class, like so (omitting error handling):

```python
def CountryHoliday(country, **kwargs):
    country_holiday = globals()[country](**kwargs)
    return country_holiday

holidays_de_he = CountryHoliday("DE", prov="HE")
```

This enables setting the state/province and of course all other options like `expand` or `observed`, even when using the very friendly `CountryHoliday`. The external API stays stable, since arguments are only added and the single existing one just stays in place.

What do you think? :) I am happy to code up a quick PR including docs and a test, if you'd like.

**Comment by dr-prodigy** [comment]
Hi,
thanks for your very good analysis! 👍

I totally agree with you: province / state initialization should find their place in CountryHoliday method as well.
But instead of providing **kwargs (not explicit parameters), I'd better like to see a clearer method signature (thru , such as
```
def CountryHoliday(country, prov='', state=''):
    [...]
```
Of course, go on coding if you like: I'll be glad to include this upgrade in the next releases.

Please let me know, thank you

**Comment by dr-prodigy** [comment]
Thanks a lot for your contribution.. closing, cheers!

**Comment by luto** [comment]
@dr-prodigy Thanks :) do you know when this will be released?

**Comment by dr-prodigy** [comment]
Hi.. nope, not yet: not having a real release scheduling, I usually pile up some updates on beta branch, then when they're a considerable amount (no specific rule about this: it's just up to my sense), I "pour" them on master and release a new official version to github and pypi.

Meanwhile, if you can't wait, there's always the possibility to install the beta directly from the repo.
As much as possible, I always care about stability, test coverage etc. before committing any change, so you *should* never have issues even with beta code.

Please refer to:
https://github.com/dr-prodigy/python-holidays#development-version

Thank you again, ciao! ;)
