### ISSUE TITLE
Cannot "Pop" Combined Texas Emancipation/Juneteenth Holiday

### ISSUE THREAD

**Issue by jasonalsing** [dr-prodigy/python-holidays#1281]
Creating a holiday using TX as the state, there is the combined holiday 'Emancipation Day In Texas; Juneteenth National Independence Day'

Previous versions of python-holidays seemed to treat this concatenation with a comma a such: 'Emancipation Day In Texas, Juneteenth National Independence Day'

I am able to 'pop_named' the holiday in the older version, not in the newer with the semicolon seperator:

python3.6/holidays 0.11.3.1:
![image](https://github.com/dr-prodigy/python-holidays/assets/38263272/0de82f34-1c46-400b-859a-b7d87f7c8703)

python 3.10/holidays .25:
![image](https://github.com/dr-prodigy/python-holidays/assets/38263272/381017f6-0d49-49d3-9b09-f4e5c85b31f0)

**Comment by jasonalsing** [comment]
I guess technically these are two separate holidays. I can pop_named them individually but it ends up removing both anyways since it pops the date itself.

**Comment by jasonalsing** [comment]
seems like 'get_names' has changed since version .20 with this code from #991 

![image](https://github.com/dr-prodigy/python-holidays/assets/38263272/320c667c-b6b0-4a8e-82aa-f260b76000ca)

**Comment by arkid15r** [comment]
Hi @jasonalsing,
I agree w/ your point that `pop_named()` should have kept the second holiday present. We'll spend some time to make sure the fix is ready before the next release.

Thanks for bringing this up!

**Comment by jasonalsing** [comment]
thanks, that makes sense to keep secondary holidays if one is pop_named()

However, what will the behavior be if both are pop_named() in the concatenated form:

pop_named('Emancipation Day In Texas; Juneteenth National Independence Day')

currently this just fails. Should users of this module expect to have to pop them individually as well? (like two separate pops) can pop_named() method support sending multiple with the HOLIDAY_NAME_DELIMITER included?

Thanks!

**Comment by arkid15r** [comment]
Implemented in #1306, in beta now
