### ISSUE TITLE
TypeError: Canada Holiday

### ISSUE THREAD

**Issue by justinasfour04** [dr-prodigy/python-holidays#152]
https://github.com/dr-prodigy/python-holidays/blob/7d9c4ed98bfb90f01d1278c9bd9b7d591c70a5b8/holidays.py#L578

TypeError: 'in <string>' requires string as left operand, not NoneType
it should be `elif self.prov == 'NS' and year >= 2015:`

Also on https://github.com/dr-prodigy/python-holidays/blob/7d9c4ed98bfb90f01d1278c9bd9b7d591c70a5b8/holidays.py#L581

and possibly other places

**Comment by dr-prodigy** [comment]
It should be fixed now on beta.. please let me know.
Thx!
