### ISSUE TITLE
Columbus Day no holiday in AR?

### ISSUE THREAD

**Issue by johanneshk** [dr-prodigy/python-holidays#155]
Hi,
I'm retrieving holidays for Arkansas and it shows that Columbus day is a holiday, e.g.:
```
import holidays
us_holidays = holidays.CountryHoliday('US', state='AR')
us_holidays.get('2021-10-11') -> 'Columbus Day'
```
Is this true? According to my quick research (please note I'm not from the US, so I might confuse something), it isn't:

- https://www.officeholidays.com/countries/usa/regional.php?list_year=2018&list_region=Arkansas
- https://www.employmentlawhandbook.com/leave-laws/state-leave-laws/arkansas/holidays/

Thank you.

**Comment by dr-prodigy** [comment]
Hi,
thank you for your contribution.
Your analisys seems correct: I've released a fix on beta branch.
Thank you very much, cheers
