### ISSUE TITLE
England holidays

### ISSUE THREAD

**Issue by tigattack** [dr-prodigy/python-holidays#160]
Hi,
Love the project.
Would it be possible to get an abbreviation for England, or provinces for UK?
I'm using your project as a workday/holiday sensor in my Home Assistant install, [as shown here](https://www.home-assistant.io/components/binary_sensor.workday/).
Currently I believe it is getting all UK holidays, some of which are not relevant in England (i.e. Scotland, Wales and N. Ireland have some different public holidays).

It would be awesome if I could narrow it down to only get holidays for England to prevent any issues with my Home Assistant automations.

Cheers.

**Comment by dr-prodigy** [comment]
Hi,
thank you very much for your support and interest in the project.

I had a look at this (which was implemented in the very early days of the prj, while I was not involved), and possibly found what you're looking for.

In particular, referring to UK, you can initialize holidays using:
`holidays.UK()` or `holidays.UnitedKingdom()` => holidays for all provinces
or
```
holidays.England()
holidays.Scotland()
holidays.IsleOfMan()
holidays.Wales()
holidays.NorthernIreland()
holidays.Ireland() # (of course IE is not in the UK, but it's probably been put in the list to simplify things)
```
=> holidays only for requested province

Please let me know if this covers your needs, thank you very much

**Comment by tigattack** [comment]
Hi,
I did see that issue before, I should've mentioned that to make my request more clear!

Unfortunately I don't think that method is a possibility for me, as outlined [here](https://www.home-assistant.io/components/binary_sensor.workday/#configuration-variables) it's only possible to specify the country abbreviation from the module that has been included in Home Assistant.

Please correct me if I'm wrong, I'm unfamiliar with Python and not that experienced with HA as I've only started using it recently!

As I'm writing this, I'm thinking I probably should have opened an issue on the Home Assistant project instead.
Sorry if this is a pain for you. Let me know what you think.

Cheers.

**Comment by dr-prodigy** [comment]
Hi,
sorry for late answering!

Thus probably not completely intuitive, you can provide any state description (both full or shortened, indistinctly) to CountryHoliday(...) method, like here:

my_holidays = holidays.CountryHoliday('Wales')

Given this, you should be able to provide any of those state names (yep, they're not provinces!) in your configuration.yaml, like this:

# Example configuration.yaml entry
binary_sensor:
  - platform: workday
    country: England
    workdays: [mon, wed, fri]

Please let me know, cheers

**Comment by dr-prodigy** [comment]
Hi @tigattack ,
not hearing from you in the last month, I assume this issue has been resolved.
Please let me know, in case of no news I'll be closing it in some days.
Thank you very much

**Comment by dr-prodigy** [comment]
Solved :)
