### ISSUE TITLE
WA day not correct in AU

### ISSUE THREAD

**Issue by isha1111** [dr-prodigy/python-holidays#161]
WA day is on the first Monday of June and not on 1st June.

**Comment by dr-prodigy** [comment]
Hi,
this is relevant code:
`
        if self.prov == 'WA' and year > 1832:
            if year >= 2015:
                name = "Western Australia Day"
            else:
                name = "Foundation Day"
            self[date(year, JUN, 1) + rd(weekday=MO(+1))] = name
`
which returns correct results for Western Australia. 
Please double-check and close this issue if everything makes sense to you too, thank you.
