### ISSUE TITLE
queen birthday in WA, AU is wrong

### ISSUE THREAD

**Issue by isha1111** [dr-prodigy/python-holidays#163]
Queen birthday is on last Monday of September.

line 1911 in holidays.py

**Comment by dr-prodigy** [comment]
Hi,
if possible, I would kindly ask you to implement the changes and tests, and pack them in a PR: I'll surely be merging it in the next release.

Thank you very much, cheers

**Comment by dr-prodigy** [comment]
Already fixed. Closing
