### ISSUE TITLE
2 Missing Dates in Germany

### ISSUE THREAD

**Issue by Berserker66** [dr-prodigy/python-holidays#165]
So the 24th and 31st december are afternoon-only holidays in Germany. Though most people take half-days off there anyway. In our case we use this for opening times of doctor's offices and the 24th and 31th december are closed times.
Could a GermanyExt be added similar to PortugalExt? Or could they even be added to Germany entirely?
I don't entirely know why they're missing, it seems intentional, hence me asking.

**Comment by Achimh3011** [comment]
They are not even afternoon-only holidays, they are regular working days by the law. However, most companies let their employees go home the afternoon for free (or, rather have them only spend half a day of vacation for each of the days).

**Comment by dr-prodigy** [comment]
Sorry for my late answer.
Thank you both for your contributions. Given this, I'm going to close the issue.
@Achimh3011 , thanks again for your always prompt and valuable interventions.. tchuss!
