### ISSUE TITLE
Spanish Regions Codes

### ISSUE THREAD

**Issue by dvicentem** [dr-prodigy/python-holidays#180]
Hi, I really love the project.

I have found that the nomenclature of the regions of Spain do not follow the ISO 3166-2 standard. I was thinking about changing it, but I don't know whether to maintain compatibility with the current names or not. What is preferred?

Best regards and thank you for your time.

**Comment by dr-prodigy** [comment]
Hi,
thank you very much!
I would surely suggest to add support for Spanish ISO codes, aside to the currently supported codes, so to keep "the best of both worlds" ;-)
If you could implement this, I'd surely include it in the next releases.

Thx a lot, KUTGW!
