### ISSUE TITLE
Cant import the library

### ISSUE THREAD

**Issue by Jdash99** [dr-prodigy/python-holidays#193]
I already install the library, as shown here:

```
(djangoDev) C:\Users\Jdash\Documents\gitlab\working-days>pip install holidays
Requirement already satisfied: holidays in c:\users\jdash\anaconda3\envs\djangodev\lib\site-packages (0.9.10)
Requirement already satisfied: six in c:\users\jdash\anaconda3\envs\djangodev\lib\site-packages (from holidays) (1.12.0)
Requirement already satisfied: python-dateutil in c:\users\jdash\anaconda3\envs\djangodev\lib\site-packages (from holidays) (2.8.0)
```

But when trying to import it with `import holidays,` I get the message that there is no module name` holidays`

What i'm doing wrong?

**Comment by dr-prodigy** [comment]
Hi,
at a first glance, it seems you're not doing anything particularly wrong: the issue has sth to do with your virtualenv, not doing what it's expected to (have you relocated it?).
Anyway, given that this is a setup issue, not depending on the package itself, I'm afraid I won't be able to provide more support.
Best regards

**Comment by nocibambi** [comment]
I just had the same issue.

I created a fresh conda environment with the pandas seaborn and scikit-learn libraries. Then I tried to install holidays with pip, then with conda, and finally with easy_install (I removed the package after each attempt). No difference:

```python
In [1]: import holidays                                                                                                                                       
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-fa4bcd159274> in <module>
----> 1 import holidays

ModuleNotFoundError: No module named 'holidays'
```
