### ISSUE TITLE
GB representation for UK

### ISSUE THREAD

**Issue by ivanfer** [dr-prodigy/python-holidays#197]
👋 

ISO standard country code for United Kingdom is actually [GB](https://en.wikipedia.org/wiki/ISO_3166-2:GB)

Having GB as well as UK makes lookup with ISO codes cleaner

**Comment by dr-prodigy** [comment]
Thank you

**Comment by ivanfer** [comment]
no, thank you, that was blazing fast 😻

**Comment by dr-prodigy** [comment]
Oh well y'know, 2 rows of code overall! :-D
