### ISSUE TITLE
Add support for hongkong

### ISSUE THREAD

**Issue by tongt15** [dr-prodigy/python-holidays#201]
Please add support for Hong Kong and China Mainland, please.

**Comment by dr-prodigy** [comment]
I'm sorry, no development requests are accepted, and this especially applies to very specific ones (HK and China support are "expensive" features, due to their language structure).
Would you be able to contribute in some way?

Thanks.

**Comment by tongt15** [comment]
I can provide the date of the holidays for HongKong if you wish

**Comment by dr-prodigy** [comment]
In order to do the work, we should receive the complete list of all HK holidays containing, for each item:
* name in native language
* name translation in English
* date (for holidays on fixed dates), or date logic
If you can arrange this materials, we'll do our best to integrate it: thanks.
dr-p

**Comment by DaisyLL** [comment]
Hi here I attached holiday-calendar from 2012 to 2025 for China, but the question is that it may be a little different with the real holiday cause we don't know the accual date untill The Government announce it.......
so  do you think you can use it?
Thank you ~~

**Comment by DaisyLL** [comment]
the file...

**Comment by DaisyLL** [comment]
Hi here I attached holiday-calendar from 2012 to 2025 for China, but the question is that it may be a little different with the real holiday cause we don't know the accual date untill The Government announce it.......
so do you think you can use it?
Thank you ~~



holidayname_Chinese	holidayname_English	date
元旦	New Yesr's Day	2012/1/1
元旦	New Yesr's Day	2012/1/2
元旦	New Yesr's Day	2012/1/3
春节	The Spring Festival	2012/1/22
春节	The Spring Festival	2012/1/23
春节	The Spring Festival	2012/1/24
春节	The Spring Festival	2012/1/25
春节	The Spring Festival	2012/1/26
春节	The Spring Festival	2012/1/27
春节	The Spring Festival	2012/1/28
清明	Qingming Festival	2012/4/2
清明	Qingming Festival	2012/4/3
清明	Qingming Festival	2012/4/4
劳动	Labour Day	2012/4/29
劳动	Labour Day	2012/4/30
劳动	Labour Day	2012/5/1
端午	The Dragon Boat Festival	2012/6/22
端午	The Dragon Boat Festival	2012/6/23
端午	The Dragon Boat Festival	2012/6/24
国庆	National Day	2012/9/30
国庆	National Day	2012/10/1
国庆	National Day	2012/10/2
国庆	National Day	2012/10/3
国庆	National Day	2012/10/4
国庆	National Day	2012/10/5
国庆	National Day	2012/10/6
国庆	National Day	2012/10/7
元旦	New Yesr's Day	2013/1/1
元旦	New Yesr's Day	2013/1/2
元旦	New Yesr's Day	2013/1/3
春节	The Spring Festival	2013/2/9
春节	The Spring Festival	2013/2/10
春节	The Spring Festival	2013/2/11
春节	The Spring Festival	2013/2/12
春节	The Spring Festival	2013/2/13
春节	The Spring Festival	2013/2/14
春节	The Spring Festival	2013/2/15
清明	Qingming Festival	2013/4/4
清明	Qingming Festival	2013/4/5
清明	Qingming Festival	2013/4/6
劳动	Labour Day	2013/4/29
劳动	Labour Day	2013/4/30
劳动	Labour Day	2013/5/1
端午	The Dragon Boat Festival	2013/6/10
端午	The Dragon Boat Festival	2013/6/11
端午	The Dragon Boat Festival	2013/6/12
中秋	Mid_Autumn Festival	2013/9/19
中秋	Mid_Autumn Festival	2013/9/20
中秋	Mid_Autumn Festival	2013/9/21
国庆	National Day	2013/10/1
国庆	National Day	2013/10/2
国庆	National Day	2013/10/3
国庆	National Day	2013/10/4
国庆	National Day	2013/10/5
国庆	National Day	2013/10/6
国庆	National Day	2013/10/7
元旦	New Yesr's Day	2014/1/1
春节	The Spring Festival	2014/1/31
春节	The Spring Festival	2014/2/1
春节	The Spring Festival	2014/2/2
春节	The Spring Festival	2014/2/3
春节	The Spring Festival	2014/2/4
春节	The Spring Festival	2014/2/5
春节	The Spring Festival	2014/2/6
清明	Qingming Festival	2014/4/5
清明	Qingming Festival	2014/4/6
清明	Qingming Festival	2014/4/7
劳动	Labour Day	2014/5/1
劳动	Labour Day	2014/5/2
劳动	Labour Day	2014/5/3
端午	The Dragon Boat Festival	2014/5/31
端午	The Dragon Boat Festival	2014/6/1
端午	The Dragon Boat Festival	2014/6/2
中秋	Mid_Autumn Festival	2014/9/6
中秋	Mid_Autumn Festival	2014/9/7
中秋	Mid_Autumn Festival	2014/9/8
国庆	National Day	2014/10/1
国庆	National Day	2014/10/2
国庆	National Day	2014/10/3
国庆	National Day	2014/10/4
国庆	National Day	2014/10/5
国庆	National Day	2014/10/6
国庆	National Day	2014/10/7
元旦	New Yesr's Day	2015/1/1
元旦	New Yesr's Day	2015/1/2
元旦	New Yesr's Day	2015/1/3
春节	The Spring Festival	2015/2/18
春节	The Spring Festival	2015/2/19
春节	The Spring Festival	2015/2/20
春节	The Spring Festival	2015/2/21
春节	The Spring Festival	2015/2/22
春节	The Spring Festival	2015/2/23
春节	The Spring Festival	2015/2/24
清明	Qingming Festival	2015/4/4
清明	Qingming Festival	2015/4/5
清明	Qingming Festival	2015/4/6
劳动	Labour Day	2015/5/1
劳动	Labour Day	2015/5/2
劳动	Labour Day	2015/5/3
端午	The Dragon Boat Festival	2015/6/20
端午	The Dragon Boat Festival	2015/6/21
端午	The Dragon Boat Festival	2015/6/22
中秋	Mid_Autumn Festival	2015/9/26
中秋	Mid_Autumn Festival	2015/9/27
国庆	National Day	2015/10/1
国庆	National Day	2015/10/2
国庆	National Day	2015/10/3
国庆	National Day	2015/10/4
国庆	National Day	2015/10/5
国庆	National Day	2015/10/6
国庆	National Day	2015/10/7
元旦	New Yesr's Day	2016/1/1
元旦	New Yesr's Day	2016/1/2
元旦	New Yesr's Day	2016/1/3
春节	The Spring Festival	2016/2/7
春节	The Spring Festival	2016/2/8
春节	The Spring Festival	2016/2/9
春节	The Spring Festival	2016/2/10
春节	The Spring Festival	2016/2/11
春节	The Spring Festival	2016/2/12
春节	The Spring Festival	2016/2/13
清明	Qingming Festival	2016/4/2
清明	Qingming Festival	2016/4/3
清明	Qingming Festival	2016/4/4
劳动	Labour Day	2016/4/30
劳动	Labour Day	2016/5/1
劳动	Labour Day	2016/5/2
端午	The Dragon Boat Festival	2016/6/9
端午	The Dragon Boat Festival	2016/6/10
端午	The Dragon Boat Festival	2016/6/11
中秋	Mid_Autumn Festival	2016/9/15
中秋	Mid_Autumn Festival	2016/9/16
中秋	Mid_Autumn Festival	2016/9/17
国庆	National Day	2016/10/1
国庆	National Day	2016/10/2
国庆	National Day	2016/10/3
国庆	National Day	2016/10/4
国庆	National Day	2016/10/5
国庆	National Day	2016/10/6
国庆	National Day	2016/10/7
元旦	New Yesr's Day	2016/12/31
元旦	New Yesr's Day	2017/1/1
元旦	New Yesr's Day	2017/1/2
春节	The Spring Festival	2017/1/27
春节	The Spring Festival	2017/1/28
春节	The Spring Festival	2017/1/29
春节	The Spring Festival	2017/1/30
春节	The Spring Festival	2017/1/31
春节	The Spring Festival	2017/2/1
春节	The Spring Festival	2017/2/2
清明	Qingming Festival	2017/4/2
清明	Qingming Festival	2017/4/3
清明	Qingming Festival	2017/4/4
劳动	Labour Day	2017/4/29
劳动	Labour Day	2017/4/30
劳动	Labour Day	2017/5/1
端午	The Dragon Boat Festival	2017/5/28
端午	The Dragon Boat Festival	2017/5/29
端午	The Dragon Boat Festival	2017/5/30
国庆	National Day	2017/10/1
国庆	National Day	2017/10/2
国庆	National Day	2017/10/3
国庆	National Day	2017/10/4
国庆	National Day	2017/10/5
国庆	National Day	2017/10/6
国庆	National Day	2017/10/7
国庆	National Day	2017/10/8
元旦	New Yesr's Day	2017/12/30
元旦	New Yesr's Day	2017/12/31
元旦	New Yesr's Day	2018/1/1
春节	The Spring Festival	2018/2/15
春节	The Spring Festival	2018/2/16
春节	The Spring Festival	2018/2/17
春节	The Spring Festival	2018/2/18
春节	The Spring Festival	2018/2/19
春节	The Spring Festival	2018/2/20
春节	The Spring Festival	2018/2/21
清明	Qingming Festival	2018/4/5
清明	Qingming Festival	2018/4/6
清明	Qingming Festival	2018/4/7
劳动	Labour Day	2018/4/29
劳动	Labour Day	2018/4/30
劳动	Labour Day	2018/5/1
端午	The Dragon Boat Festival	2018/6/16
端午	The Dragon Boat Festival	2018/6/17
端午	The Dragon Boat Festival	2018/6/18
中秋	Mid_Autumn Festival	2018/9/22
中秋	Mid_Autumn Festival	2018/9/23
中秋	Mid_Autumn Festival	2018/9/24
国庆	National Day	2018/10/1
国庆	National Day	2018/10/2
国庆	National Day	2018/10/3
国庆	National Day	2018/10/4
国庆	National Day	2018/10/5
国庆	National Day	2018/10/6
国庆	National Day	2018/10/7
元旦	New Yesr's Day	2018/12/30
元旦	New Yesr's Day	2018/12/31
元旦	New Yesr's Day	2019/1/1
春节	The Spring Festival	2019/2/4
春节	The Spring Festival	2019/2/5
春节	The Spring Festival	2019/2/6
春节	The Spring Festival	2019/2/7
春节	The Spring Festival	2019/2/8
春节	The Spring Festival	2019/2/9
春节	The Spring Festival	2019/2/10
清明	Qingming Festival	2019/4/5
清明	Qingming Festival	2019/4/6
清明	Qingming Festival	2019/4/7
劳动	Labour Day	2019/5/1
劳动	Labour Day	2019/5/2
劳动	Labour Day	2019/5/3
劳动	Labour Day	2019/5/4
端午	The Dragon Boat Festival	2019/6/7
端午	The Dragon Boat Festival	2019/6/8
端午	The Dragon Boat Festival	2019/6/9
中秋	Mid_Autumn Festival	2019/9/13
中秋	Mid_Autumn Festival	2019/9/14
中秋	Mid_Autumn Festival	2019/9/15
国庆	National Day	2019/10/1
国庆	National Day	2019/10/2
国庆	National Day	2019/10/3
国庆	National Day	2019/10/4
国庆	National Day	2019/10/5
国庆	National Day	2019/10/6
国庆	National Day	2019/10/7
元旦	New Yesr's Day	2020/1/1
元旦	New Yesr's Day	2020/1/2
元旦	New Yesr's Day	2020/1/3
春节	The Spring Festival	2020/1/24
春节	The Spring Festival	2020/1/25
春节	The Spring Festival	2020/1/26
春节	The Spring Festival	2020/1/27
春节	The Spring Festival	2020/1/28
春节	The Spring Festival	2020/1/29
春节	The Spring Festival	2020/1/30
清明	Qingming Festival	2020/4/4
清明	Qingming Festival	2020/4/5
清明	Qingming Festival	2020/4/6
劳动	Labour Day	2020/5/1
劳动	Labour Day	2020/5/2
劳动	Labour Day	2020/5/3
端午	The Dragon Boat Festival	2020/6/25
端午	The Dragon Boat Festival	2020/6/26
端午	The Dragon Boat Festival	2020/6/27
国庆	National Day	2020/10/1
国庆	National Day	2020/10/2
国庆	National Day	2020/10/3
国庆	National Day	2020/10/4
国庆	National Day	2020/10/5
国庆	National Day	2020/10/6
国庆	National Day	2020/10/7
国庆	National Day	2020/10/8
元旦	New Yesr's Day	2021/1/1
元旦	New Yesr's Day	2021/1/2
元旦	New Yesr's Day	2021/1/3
春节	The Spring Festival	2021/2/11
春节	The Spring Festival	2021/2/12
春节	The Spring Festival	2021/2/13
春节	The Spring Festival	2021/2/14
春节	The Spring Festival	2021/2/15
春节	The Spring Festival	2021/2/16
春节	The Spring Festival	2021/2/17
清明	Qingming Festival	2021/4/2
清明	Qingming Festival	2021/4/3
清明	Qingming Festival	2021/4/4
劳动	Labour Day	2021/4/30
劳动	Labour Day	2021/5/1
劳动	Labour Day	2021/5/2
端午	The Dragon Boat Festival	2021/6/12
端午	The Dragon Boat Festival	2021/6/13
端午	The Dragon Boat Festival	2021/6/14
中秋	Mid_Autumn Festival	2021/9/19
中秋	Mid_Autumn Festival	2021/9/20
中秋	Mid_Autumn Festival	2021/9/21
国庆	National Day	2021/10/1
国庆	National Day	2021/10/2
国庆	National Day	2021/10/3
国庆	National Day	2021/10/4
国庆	National Day	2021/10/5
国庆	National Day	2021/10/6
国庆	National Day	2021/10/7
元旦	New Yesr's Day	2021/12/31
元旦	New Yesr's Day	2022/1/1
元旦	New Yesr's Day	2022/1/2
春节	The Spring Festival	2022/1/31
春节	The Spring Festival	2022/2/1
春节	The Spring Festival	2022/2/2
春节	The Spring Festival	2022/2/3
春节	The Spring Festival	2022/2/4
春节	The Spring Festival	2022/2/5
春节	The Spring Festival	2022/2/6
清明	Qingming Festival	2022/4/3
清明	Qingming Festival	2022/4/4
清明	Qingming Festival	2022/4/5
劳动	Labour Day	2022/4/29
劳动	Labour Day	2022/4/30
劳动	Labour Day	2022/5/1
端午	The Dragon Boat Festival	2022/6/3
端午	The Dragon Boat Festival	2022/6/4
端午	The Dragon Boat Festival	2022/6/5
中秋	Mid_Autumn Festival	2022/9/9
中秋	Mid_Autumn Festival	2022/9/10
中秋	Mid_Autumn Festival	2022/9/11
国庆	National Day	2022/10/1
国庆	National Day	2022/10/2
国庆	National Day	2022/10/3
国庆	National Day	2022/10/4
国庆	National Day	2022/10/5
国庆	National Day	2022/10/6
国庆	National Day	2022/10/7
元旦	New Yesr's Day	2022/12/30
元旦	New Yesr's Day	2022/12/31
元旦	New Yesr's Day	2023/1/1
春节	The Spring Festival	2023/1/21
春节	The Spring Festival	2023/1/22
春节	The Spring Festival	2023/1/23
春节	The Spring Festival	2023/1/24
春节	The Spring Festival	2023/1/25
春节	The Spring Festival	2023/1/26
春节	The Spring Festival	2023/1/27
清明	Qingming Festival	2023/4/5
清明	Qingming Festival	2023/4/6
清明	Qingming Festival	2023/4/7
劳动	Labour Day	2023/4/29
劳动	Labour Day	2023/4/30
劳动	Labour Day	2023/5/1
端午	The Dragon Boat Festival	2023/6/22
端午	The Dragon Boat Festival	2023/6/23
端午	The Dragon Boat Festival	2023/6/24
中秋	Mid_Autumn Festival	2023/9/29
中秋	Mid_Autumn Festival	2023/9/30
国庆	National Day	2023/10/1
国庆	National Day	2023/10/2
国庆	National Day	2023/10/3
国庆	National Day	2023/10/4
国庆	National Day	2023/10/5
国庆	National Day	2023/10/6
元旦	New Yesr's Day	2023/12/30
元旦	New Yesr's Day	2023/12/31
元旦	New Yesr's Day	2024/1/1
春节	The Spring Festival	2024/2/9
春节	The Spring Festival	2024/2/10
春节	The Spring Festival	2024/2/11
春节	The Spring Festival	2024/2/12
春节	The Spring Festival	2024/2/13
春节	The Spring Festival	2024/2/14
春节	The Spring Festival	2024/2/15
清明	Qingming Festival	2024/4/4
清明	Qingming Festival	2024/4/5
清明	Qingming Festival	2024/4/6
劳动	Labour Day	2024/5/1
劳动	Labour Day	2024/5/2
劳动	Labour Day	2024/5/3
端午	The Dragon Boat Festival	2024/6/8
端午	The Dragon Boat Festival	2024/6/9
端午	The Dragon Boat Festival	2024/6/10
中秋	Mid_Autumn Festival	2024/9/15
中秋	Mid_Autumn Festival	2024/9/16
中秋	Mid_Autumn Festival	2024/9/17
国庆	National Day	2024/9/28
国庆	National Day	2024/9/29
国庆	National Day	2024/9/30
国庆	National Day	2024/10/1
国庆	National Day	2024/10/2
国庆	National Day	2024/10/3
国庆	National Day	2024/10/4
元旦	New Yesr's Day	2025/1/1
元旦	New Yesr's Day	2025/1/2
元旦	New Yesr's Day	2025/1/3
春节	The Spring Festival	2025/1/28
春节	The Spring Festival	2025/1/29
春节	The Spring Festival	2025/1/30
春节	The Spring Festival	2025/1/31
春节	The Spring Festival	2025/2/1
春节	The Spring Festival	2025/2/2
春节	The Spring Festival	2025/2/3
清明	Qingming Festival	2025/4/4
清明	Qingming Festival	2025/4/5
清明	Qingming Festival	2025/4/6
劳动	Labour Day	2025/5/1
劳动	Labour Day	2025/5/2
劳动	Labour Day	2025/5/3
端午	The Dragon Boat Festival	2025/5/30
端午	The Dragon Boat Festival	2025/5/31
端午	The Dragon Boat Festival	2025/6/1
国庆	National Day	2025/10/1
国庆	National Day	2025/10/2
国庆	National Day	2025/10/3
国庆	National Day	2025/10/4
国庆	National Day	2025/10/5
国庆	National Day	2025/10/6
国庆	National Day	2025/10/7
国庆	National Day	2025/10/8

**Comment by dr-prodigy** [comment]
Hi there @DaisyLL , thank you for your help.
Some questions:

1) the main goal of the library is to provide a business logic to setup holidays for past present and (possibly) future.
So in the end, instead of collecting fixed dates (which are very verbose and are not future-proof), and instead implement code like "Labour day happens in the first workday of May" (just an example: the sentence is probably wrong).
Then of course, when this is not possible, we try to manage the exceptions.
Do you think this approach is feasible/applicable to China holidays too?

2) In the list above I see a lot of holidays made up of multiple days (eg: National Day from 2025/10/1 to 2025/10/8): is this correct?

Can you rearrange your data according to these requests?

Thank you very much, KUTGW

**Comment by polyfaces** [comment]
> 
> 
> Hi there @DaisyLL , thank you for your help.
> Some questions:
> 
>     1. the main goal of the library is to provide a business logic to setup holidays for past present and (possibly) future.
>        So in the end, instead of collecting fixed dates (which are very verbose and are not future-proof), we always try to implement code like "Labour day happens in the first workday of May" (just an example: the sentence is probably wrong).
>        Then of course, when this is not possible, we try to manage the exceptions.
>        Do you think this approach is feasible/applicable to HK/Chinese holidays too?
> 
>     2. In the list above I see a lot of holidays made up of multiple days (eg: National Day from 2025/10/1 to 2025/10/8): is this correct?
> 
> 
> Can you rearrange your data according to these requests?
> 
> Thank you very much, KUTGW

The dates provided by @DaisyLL was China's holidays, and Hong Kong would have another holidays dates.  Therefore, I suggest using another separate thread for @DaisyLL case on China's holidays.

**Comment by polyfaces** [comment]
#208 I have implemented support for Hong Kong calendar and a pull request has been made.
