### ISSUE TITLE
The observed date for Canada and US New Years Day not correct

### ISSUE THREAD

**Issue by Derek-npp** [dr-prodigy/python-holidays#206]
Thanks, this is a great package.
In North America, if Dec 31 is Friday, the New Year's holiday is observed on the following Monday. It seems like there is special code here to force the observance to Friday Dec 31, but that's incorrect.
#The next year's observed New Year's Day can be in this year
            # when it falls on a Friday (Jan 1st is a Saturday)
            if self.observed and date(year, DEC, 31).weekday() == FRI:
                self[date(year, DEC, 31)] = name + " (Observed)"

The issue comes up in Dec 2022, because Dec 31 2021 is on Friday.

I'm not sure if you need anything official to verify that? The following site agrees with my claim:
https://www.timeanddate.com/calendar/?year=2022&country=27
OR
https://www.marketbeat.com/stock-market-holidays/canada/

Thanks!

**Comment by snoopyjc** [comment]
Also, per the Bond Market calendar, New Year's Eve in 2023 is observed on Dec 29th.  Your code for NYE doesn't handle that.

**Comment by mborsetti** [comment]
The code correctly follows U.S. law, which stipulates that if holiday falls on a Saturday, the Friday immediately before is a legal public holiday: https://www.law.cornell.edu/uscode/text/5/6103.

For January 3, 2022 to be a public holiday in the U.S. it would require a new law or a Presidential Proclamation, which I haven't found.  Private companies (such as stock exchanges and bond markets), of course, are free to make their own holidays, but this library appears to track official holidays only.

**Comment by dr-prodigy** [comment]
Hi,
thank you @mborsetti for sorting this out! I confirm this as closed.

Thanks to everybody, cheers
