### ISSUE TITLE
Detecting only holidays recognized in the banking/financial industry

### ISSUE THREAD

**Issue by archubbuck** [dr-prodigy/python-holidays#212]
Hello. I have a requirement for detecting only holidays that are recognized in the banking/financial industry. A colleague and I would like to add support for this type of detection. Is this something that you would consider adding the your open-source package if we were to provide you with a solution?

**Comment by dr-prodigy** [comment]
Hi, thank you for your contribution.
This is truely interesting!
What is difficult, IMHO, is applying it to all country holidays we've collected until now (or at least a good part of them).
Do you think it would be feasible?

Thank you again, cheers
dr-p
