### ISSUE TITLE
Region support for the United Kindgom

### ISSUE THREAD

**Issue by jamieshaw** [dr-prodigy/python-holidays#216]
The UK locale is not granular enough for holidays within the United Kingdom, and treats any holiday specific to a country within the UK as effective against the whole.

For specifically, today is the Battle of the Boyne, a national holiday only witnessed within Northern Ireland – the other countries are unaffected by this holiday.

An option to be more specific at the witnessed country (i.e. England, Wales, Scotland…) would be welcome.

**Comment by dr-prodigy** [comment]
Hmmm.. this sounds to be already there:
`        # Battle of the Boyne
        if self.country in ('UK', 'Northern Ireland'):
            name = "Battle of the Boyne"
            .....
`
For specific holidays only, you got
"England", "Wales", "Scotland", "IsleOfMan", "NorthernIreland"
while
"UK" (or "GB") sums up all country holidays.

Please let me know, cheers
dr-p

**Comment by robfraz** [comment]
```python
In [1]: from datetime import date                                                                             

In [2]: import holidays                                                                                       

In [3]: holidays_in_england = holidays.England()                                                              

In [4]: date(2019, 8, 26) in holidays_in_england                                                              
Out[4]: True

In [5]: holidays_in_england                                                                                   
Out[5]: 
{datetime.date(2019, 1, 1): "New Year's Day",
 datetime.date(2019, 4, 19): 'Good Friday',
 datetime.date(2019, 4, 22): 'Easter Monday',
 datetime.date(2019, 5, 6): 'May Day',
 datetime.date(2019, 5, 27): 'Spring Bank Holiday',
 datetime.date(2019, 8, 26): 'Late Summer Bank Holiday',
 datetime.date(2019, 12, 25): 'Christmas Day',
 datetime.date(2019, 12, 26): 'Boxing Day'}
```

**Comment by jamieshaw** [comment]
Apologies, meant to get back to you on this one. Can confirm all looks good, not sure if this is something I just missed on the documentation.
