### ISSUE TITLE
Holidays in Japan are not correct anymore, from May 2019

### ISSUE THREAD

**Issue by thophan92** [dr-prodigy/python-holidays#217]
In May 2019, Japan changed their king, it led the changes in the holiday system. Please update it.

**Comment by dr-prodigy** [comment]
Hi,
would you please provide us with the correct information?

Thank you very much, cheers
dr-p

**Comment by thophan92** [comment]
Hi dr-prodigy,

Thank you for your reply.

Filtering the official holiday in [Japan holiday](https://www.timeanddate.com/holidays/japan/) will give the exact result.

Thank you for your concern.

**Comment by juanesfonsecan** [comment]
Hi! Mexico holidays are not correct anymore. Can you add them please?
They seem to be these ones: https://publicholidays.mx/es/2019-dates/

Thanks!

**Comment by dr-prodigy** [comment]
> Hi dr-prodigy,
> 
> Thank you for your reply.
> 
> Filtering the official holiday in [Japan holiday](https://www.timeanddate.com/holidays/japan/) will give the exact result.
> 
> Thank you for your concern.
Hi,
according to your link, and comparing it with the current code, it results that the new holidays to be managed are:
14 Jan	Monday	Coming of Age Day	National holiday
14 Feb	Thursday	Valentine's Day	Observance
3 Mar	Sunday	Dolls' Festival/Girls' Festival	Observance
21 Mar	Thursday	Spring Equinox	National holiday
30 Apr	Tuesday	Coronation Day holiday	National holiday
2 May	Thursday	Coronation Day holiday	National holiday
6 May	Monday	Children's Day observed	National holiday
7 Jul	Sunday	Star Festival	Observance
15 Jul	Monday	Sea Day	National holiday
6 Aug	Tuesday	Hiroshima Memorial Day	Observance
9 Aug	Friday	Nagasaki Memorial Day	Observance
12 Aug	Monday	Mountain Day observed	National holiday
16 Sep	Monday	Respect for the Aged Day	National holiday
4 Nov	Monday	Culture Day observed	National holiday
15 Nov	Friday	7-5-3 Day	Observance
25 Dec	Wednesday	Christmas	Observance
Unfortunately, I don't speak a word of Japanese.. even worse to write in it :-)
Would you please help us with the japanese translation of them?
Thank you very much!

**Comment by thophan92** [comment]
> > Hi dr-prodigy,
> > Thank you for your reply.
> > Filtering the official holiday in [Japan holiday](https://www.timeanddate.com/holidays/japan/) will give the exact result.
> > Thank you for your concern.
> 
> Hi,
> according to your link, and comparing it with the current code, it results that the new holidays to be managed are:
> 
> 14 Jan Monday Coming of Age Day National holiday
> 14 Feb Thursday Valentine's Day Observance
> 3 Mar Sunday Dolls' Festival/Girls' Festival Observance
> 21 Mar Thursday Spring Equinox National holiday
> 30 Apr Tuesday Coronation Day holiday National holiday
> 2 May Thursday Coronation Day holiday National holiday
> 6 May Monday Children's Day observed National holiday
> 7 Jul Sunday Star Festival Observance
> 15 Jul Monday Sea Day National holiday
> 6 Aug Tuesday Hiroshima Memorial Day Observance
> 9 Aug Friday Nagasaki Memorial Day Observance
> 12 Aug Monday Mountain Day observed National holiday
> 16 Sep Monday Respect for the Aged Day National holiday
> 4 Nov Monday Culture Day observed National holiday
> 15 Nov Friday 7-5-3 Day Observance
> 25 Dec Wednesday Christmas Observance
> 
> Unfortunately, I don't speak a word of Japanese.. even worse to write in it :-)
> Would you please help us with the japanese translation of them?
> Thank you very much!

Hi,

Thank you for your reply.

Here you are:
2019:

2019/01/01      | 2019年1月1日（火） | 元日 | New Year's Day
2019/01/14      | 2019年1月14日（月） | 成人の日 | Coming-of-age Day
2019/02/11      | 2019年2月11日（月） | 建国記念の日 | National Foundation Day
2019/03/21      | 2019年3月21日（木） | 春分の日 | Vernal Equinox Day
2019/04/29      | 2019年4月29日（月） | 昭和の日 | Shōwa Day
2019/04/30      | 2019年4月30日（火） | 休日 | Holiday
2019/05/01      | 2019年5月1日（水） | 即位の日 | Throne day
2019/05/02      | 2019年5月2日（木） | 休日 | Holiday
2019/05/03      | 2019年5月3日（金） | 憲法記念日 | Constitution Memorial Day
2019/05/04      | 2019年5月4日（土） | みどりの日 | Greenery Day
2019/05/05      | 2019年5月5日（日） | 子供の日 | Children's Day
2019/05/06      | 2019年5月6日（月） | 振替休日 | Substitute Holiday
2019/07/15      | 2019年7月15日（月） | 海の日 | Marine Day
2019/08/11      | 2019年8月11日（日） | 山の日 | Mountain Day
2019/08/12      | 2019年8月12日（月） | 振替休日 | Substitute Holiday
2019/09/16      | 2019年9月16日（月） | 敬老の日 | Respect for the Aged Day
2019/09/23      | 2019年9月23日（月） | 秋分の日 | Autumnal Equinox Day
2019/10/14      | 2019年10月14日（月） | 体育の日 | Health-Sports Day
2019/10/22      | 2019年10月22日（火） | 即位礼正殿の儀の行われる日 | Day of The Coronation Court
2019/11/03      | 2019年11月3日（日） | 文化の日 | Culture Day
2019/11/04      | 2019年11月4日（月） | 振替休日 | Substitute Holiday
2019/11/23      | 2019年11月23日（土） | 勤労感謝の日 | Labour Thanksgiving Day

Here for 2020

2020/01/01      | 2020年1月1日（水） | 元日 | New Year's Day
2020/01/13      | 2020年1月13日（月） | 成人の日 | Coming-of-age Day
2020/02/11      | 2020年2月11日（火） | 建国記念の日 | National Foundation Day
2020/02/23      | 2020年2月23日（日） | 天皇誕生日 | Emperor's Birthday
2020/02/24      | 2020年2月24日（月） | 振替休日 | Substitute Holiday
2020/03/20      | 2020年3月20日（金） | 春分の日 | Vernal Equinox Day
2020/04/29      | 2020年4月29日（水） | 昭和の日 | Shōwa Day
2020/05/03      | 2020年5月3日（日） | 憲法記念日 | Constitution Memorial Day
2020/05/04      | 2020年5月4日（月） | みどりの日 | Greenery Day
2020/05/05      | 2020年5月5日（火） | 子供の日 | Children's Day
2020/05/06      | 2020年5月6日（水） | 振替休日 | Substitute Holiday
2020/07/23      | 2020年7月23日（木） | 海の日 | Marine Day
2020/07/24      | 2020年7月24日（金） | スポーツの日 | Sports Day
2020/08/10      | 2020年8月10日（月） | 山の日 | Mountain Day
2020/09/21      | 2020年9月21日（月） | 敬老の日 | Respect for the Aged Day
2020/09/22      | 2020年9月22日（火） | 秋分の日 | Autumnal Equinox Day
2020/11/03      | 2020年11月3日（火） | 文化の日 | Culture Day
2020/11/23      | 2020年11月23日（月） | 勤労感謝の日 | Labour Thanksgiving Day


Thank you so much!

**Comment by saurabh3896** [comment]
Hi @dr-prodigy , is there any update for this issue? I tested your library and found that for the following Japanese holidays, the results are incorrect. Would you be kind enough to update them?

**Comment by dr-prodigy** [comment]
Fixed and released on beta branch. Thank you!
