### ISSUE TITLE
Provided countries in documentation is not supported

### ISSUE THREAD

**Issue by saravanansaminathan** [dr-prodigy/python-holidays#224]
There are 40+ countries are supported in this package. But for a few provided countries error throw up
Not supported countries but provided in documentation are :

1. KE - kenya
2. PE -peru
3. IS -Iceland
4. ISLEOFMAN
5. EE - ESTONIA

<img width="929" alt="Screenshot 2019-08-21 at 12 40 29 PM" src="https://user-images.githubusercontent.com/36497548/63411548-62a64f80-c413-11e9-9d0d-2336573fe5e7.png">

**Comment by dr-prodigy** [comment]
Hi,
I can't replicate your issue: all values are available in code and work as expected.
Please note, correct values are:
KE - Kenya
PE -Peru
IS -Iceland
IsleOfMan
EE - Estonia
