### ISSUE TITLE
Flag to detect observed vs non-observed holidays

### ISSUE THREAD

**Issue by jbroudou** [dr-prodigy/python-holidays#225]
At the moment to determine if a date is an actual holiday you need to iterate through a list of all holidays to check if there is one that contains the string "(Observed)" in the name. This seems clunky. 

Is there interest in defining another get method that returns an object containing flags such as "observed"?

**Comment by dr-prodigy** [comment]
Hi,
until now, this is the first request on this topic. At the moment there is no place for such information, and in a lot of countries observed holidays apply, so surely it will be a quite expensive development.
Also, we won't be breaking compatibility with previous versions, so implementation must be well designed.

If you are interested in doing it, I will surely consider it for production.. thank you very much!

**Comment by dr-prodigy** [comment]
No news.. closing this ;-)

**Comment by msj121** [comment]
Simple script for those who need it:

Just note you need the full name I think for this to work, not part of name
    ```
def getObserved(name):
        day = us_holidays.get_named(name+" (Observed)")
        if(len(day)==0):
            day = us_holidays.get_named(name)
        return day
```
