### ISSUE TITLE
bug: an incomplete list of holidays is returned when the periods include more than one whole year

### ISSUE THREAD

**Issue by chla0089** [dr-prodigy/python-holidays#226]
Hi,

I noticed a bug when I tried to get a list of Irish holidays. When there is a complete year between the year of the start date and the year of the end date (e.g. start in 2018 and end in 2020), only the holidays of the start year and end year are returned.

Example:

`import pandas as pd`
`import holidays`

`start=pd.Timestamp('2010-12-20')`
`end=pd.Timestamp('2012-01-03')`

`cal_ie = holidays.CountryHoliday('IE', prov=None, state=None)`
`hld_ind = cal_ie[start:end]`

`print(hld_ind)`
`# returns: [datetime.date(2018, 12, 25), datetime.date(2018, 12, 26), datetime.date(2020, 1, 1)]`

As you can see the holidays of 2019 are missing.

Thanks and keep up the great work!

**Comment by dr-prodigy** [comment]
Hi,
thank you for your interest in the library, and sorry for the delay.
In fact, a new year is initialized whenever an enclosed date is searched.
If you want to initialize a list of contiguous years, instead, you should proceed like this:

`import holidays`
`holidays_ie = holidays.Ireland(years=range(2010,2013))`
`print sorted(holidays_ie)`

It's instead not currently possible to initialize all holidays from date1 to date2, as you tried to.

Cheers
dr-p

**Comment by etiennecaldichoury** [comment]
I use this workaround:
`type(holidays.CountryHoliday(country_code))(years=range(start_date.year, end_date.year))[
            start_date:end_date
 ]`

**Comment by dr-prodigy** [comment]
> I use this workaround:
> `type(holidays.CountryHoliday(country_code))(years=range(start_date.year, end_date.year))[ start_date:end_date ]`

Nice one! 👍
