### ISSUE TITLE
CountryHoliday doesn't support all HolidayBase options

### ISSUE THREAD

**Issue by jbroudou** [dr-prodigy/python-holidays#227]
Related to #128

CountryHoliday provides a useful mechanism to returns dates for countries and states that are only know at run time. However it doesn't support all the options that HolidayBase supports such as `expand` & `observed` which are documented in the README.

Can these either be added or reconsider the original proposal in #128 of using `**kwargs` ?

**Comment by dr-prodigy** [comment]
Hi,
I finally preferred to add those 2 missing parameters as optional ones. Done!
