### ISSUE TITLE
Support for Nigeria

### ISSUE THREAD

**Issue by ioluwayo** [dr-prodigy/python-holidays#229]
Hello, 
I am willing to contribute this support if you approve :)

Fixed holidays include
New year's day: 1 January
Workers day: 1 May
Children's day: 27 May
Democracy day: 12 June 
Independence day: 1 October
Christmas daya: 25 December
Boxing day: 26 December

I'd be happy to contribute this support.

**Comment by ioluwayo** [comment]
[Pull request](https://github.com/dr-prodigy/python-holidays/pull/230) to resolve this issue.

**Comment by dr-prodigy** [comment]
Of course I do.. just merged it.
Thank you very much again mate! 👍
