### ISSUE TITLE
Tests fail after 2020-01-01

### ISSUE THREAD

**Issue by bmwiedemann** [dr-prodigy/python-holidays#234]
Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +15 years, because that is how long I expect some software will be used in some places.
This showed up failing tests in our package build.
See https://reproducible-builds.org/ for why this matters.

The 3 observed failures were
```
File "holidays-0.9.11/tests.py", line 5205, in test_commerce_day
File "holidays-0.9.11/tests.py", line 5199, in test_first_day_of_summer
File "holidays-0.9.11/tests.py", line 5194, in test_maundy_thursday
```

Steps To Reproduce on openSUSE or Debian:
```
osc co openSUSE:Factory/python-holidays && cd $_
osc build --build-opt=--vm-custom-opt="-rtc base=2020-01-01T00:00:00" --vm-type=kvm --noservice --clean
```

**Comment by bmwiedemann** [comment]
Likely broke from #203 by @justinasfour04

**Comment by dr-prodigy** [comment]
Thank you very much!
