### ISSUE TITLE
Italian Holiday to add

### ISSUE THREAD

**Issue by jokerigno** [dr-prodigy/python-holidays#237]
Hi,

I'm not a developer but I can suggest some holiday for italy:

            elif self.prov == 'ME':
                self[date(year, JUN, 3)] = "Madonna della Lettera"
            elif self.prov == 'TO':
                self[date(year, JUN, 24)] = "San Giovanni Battista"

this is enough?

**Comment by dr-prodigy** [comment]
Good point!
Just added these 2.. thank you 👍

**Comment by jokerigno** [comment]
You're more than welcome :)
