### ISSUE TITLE
2020 UK Early May Bank Holiday Wrong

### ISSUE THREAD

**Issue by shassa21** [dr-prodigy/python-holidays#238]
The early May bank holiday for 2020 has been changed to 8th May from 4th May to mark Victory in Europe (VE) Day. This applies to England, Wales and Northern Ireland.
Source: https://www.gov.uk/bank-holidays#england-and-wales

Please update.

**Comment by shassa21** [comment]
and also Scotland*

**Comment by dr-prodigy** [comment]
Hi,
this is already done:
`
            if year == 2020 and self.country != 'Ireland':
                # Moved to Friday to mark 75th anniversary of VE Day.
                self[date(year, MAY, 8)] = name
`

Test:
`
from datetime import date
import holidays
date(2020, 5, 8) in holidays.UK()
`

Closing, cheers.

**Comment by shassa21** [comment]
Hi,
This is still not working. Please see attached where 8th May is showing False and 4th is showing True -> should be other way around. 

![image](https://user-images.githubusercontent.com/44369824/69056922-dc48dc00-0a08-11ea-892b-32f404ea70b7.png)
