### ISSUE TITLE
Missing one Easter holiday in the icelandic holiday calendar

### ISSUE THREAD

**Issue by astajenny** [dr-prodigy/python-holidays#239]
You have
'Skírdagur' and 'Páskadagur' but you are missing 'Föstudagurinn langi' which is the Friday between Skírdagur and Páskadagur (its a national holiday).
In 2019 the dates would be
Skírdagur 18th of April
Föstudagurinn langi 19th of April
Páskadagur 21st of April

**Comment by dr-prodigy** [comment]
Thank you, cheers!
