### ISSUE TITLE
Support timezones?

### ISSUE THREAD

**Issue by jluttine** [dr-prodigy/python-holidays#240]
Would it be possible to support timezones? One could query holidays based on timezones like `"Europe/Helsinki"`. Doesn't make sense for all timezones like UTC, though. In Pandas, timeseries indices may have timezones attached to them, so would be great if one could determine holidays based on that. Does it sound reasonable? Here's some discussion on how to get the country code based on a timezone, but that might not be sufficient if state or province information is needed too. But even just using the country code for a timezone would be great.

EDIT: Forgot to put the link: https://stackoverflow.com/questions/13020690/get-country-code-for-timezone-using-pytz

**Comment by dr-prodigy** [comment]
Unfortunately, nobody has shown interest in implementing this feature, nor having it available.
Being pretty expensive, I'm going to put it in standby ( = closing issue), to prioritize other tasks. Sorry for this, please reach out if you're interested in its development: I'll be glad to include your work. Thank you
