### ISSUE TITLE
Support for School-Holidays in Germany?

### ISSUE THREAD

**Issue by T-Born** [dr-prodigy/python-holidays#249]
Hi, 
is it planned to provide regular school holidays for Germany (for each prov)? Maybe by integrating an API?

**Comment by dr-prodigy** [comment]
Hi,
thank you for your interest in the project.
Unfortunately, this is currently not in the development plans (to make sense, this logic should be applied to all countries).
Moreover, library is self-containing and doesn't rely on any external service to work, so this would cause a requirements / compatibility break we don't want.
Closing this, thanks all the same!

**Comment by karlsebal** [comment]
@T-Born there is an [API for germany: ](https://feiertage-api.de/)

**Comment by nhoening** [comment]
That's a valid strategic choice. For people who want school holidays (because they do matter), check out [the workalender project.](https://github.com/peopledoc/workalendar/) A colleague of mine [just added](https://github.com/peopledoc/workalendar/pull/569/files) the Dutch school holidays there.
