### ISSUE TITLE
Mexico holidays are not correct anymore.

### ISSUE THREAD

**Issue by mborsetti** [dr-prodigy/python-holidays#255]
Hi! Mexico holidays are not correct anymore. Can you add them please?
They seem to be these ones: https://publicholidays.mx/es/2019-dates/

Thanks!

_Originally posted by @juanesfonsecan in https://github.com/dr-prodigy/python-holidays/issues/217#issuecomment-520610719_

**Comment by dr-prodigy** [comment]
@juanesfonsecan
Thank you for your interest in the project.
Would you please be more specific (ie: provide specific date issues)?
Thanks in advance

**Comment by Rosi2143** [comment]
Hi,

I try to solve it.

I will also try to have a mexican friend to have a look at it - but I can't promise that he is good at python 😄 .

**Comment by dr-prodigy** [comment]
Fixed with #281 PR. Well done, thank you very much!

**Comment by pixelead0** [comment]
That the Federal Labor Law and the Federal Law of Workers in the Service of the State, through the Official Calendar published in the Official Gazette of the Federation on October 6, 1993 and modified on January 27, 2006, coincide in determining The following days will be observed as compulsory rest days:

- January 1;
- the first Monday of February in commemoration of February 5;
- the third Monday of March in commemoration of March 21;
- May 1;
- 16 of September;
- the third Monday of November in commemoration of November 20; 
- December 1 of every six years, on the occasion of the transmission of the Federal Executive Power,
- December 25th.

source: http://dof.gob.mx/nota_detalle.php?codigo=5639091&fecha=22/12/2021
