### ISSUE TITLE
ZA holiday list error 

### ISSUE THREAD

**Issue by bruc314** [dr-prodigy/python-holidays#256]
hi, 

The code snippet from https://pypi.org/project/holidays/:

for date, name in sorted(holidays.ZA(state=' ', years= XXXX).items()):
    print(date, name)

gives all holidays since 1999 instead of just those from year XXXX, for any XXXX. Same happens for holidays.SouthAfrica. 

Cheers
B

**Comment by dr-prodigy** [comment]
Hi,
this does not seem to happen.
Please remember that, if expand=True, whenever you test a new date against the holidays object, it will add all dates in its containing year.
If you want to have a list of years, you should instead write, for instance:

`for date, name in sorted(holidays.ZA(state=' ', years=range(2010,2013)).items()):`
`     print(date, name)`

Cheers,
dr-p
