### ISSUE TITLE
Split up code file

### ISSUE THREAD

**Issue by MaxHaertwig** [dr-prodigy/python-holidays#260]
Hi @dr-prodigy,

the `holidays.py` file has grown quite big over time. I suggest to split it up and have a separate file for each country to make maintaining the codebase more manageable in the future. However, all names should still be exported from the main module. Do you want me to do this kind of refactoring and submit a pull request?

**Comment by dr-prodigy** [comment]
Hi,
thank you very much for your help.. 
This sounds pretty good! And that's something we would like to work on soon.
If you want to start the work, yes, please, do it (note: please start from and target "unstable" branch), and let me review it after the first changes applied (naming convention, structure, etc). 
After that we will be completing it. 
Okay for you?
Thank you very much again!
Cheers
dr-p

**Comment by 0xF4D3C0D3** [comment]
I was just thinking the same thing! I agree with this.

**Comment by dr-prodigy** [comment]
Hey there @MaxHaertwig 
I finally completed the whole refactoring (added header comments, PEP8 / flake8 fixes, TravisCI review etc. etc.) and released to beta branch.
Thank you very much for your contribution!
Cheers
dr-p
