### ISSUE TITLE
Indonesian holiday

### ISSUE THREAD

**Issue by ranrinc** [dr-prodigy/python-holidays#261]
Is there away to make Indonesian holiday into this project? Thanks

https://www.timeanddate.com/calendar/?year=2020&country=65

**Comment by dr-prodigy** [comment]
Hi,
this is mainly a voluntary crowd sourcing project.
If you want soon any specific features, you will have to code them on your own.
Otherwise, you can provide any useful information and wait for someone to do them.

Best regards 
dr-p

**Comment by ranrinc** [comment]
I there away for me to contribute maybe adding my country holiday? if yes.. how?
