### ISSUE TITLE
New subdivision request (BR-PR: Brazil, Paraná)

### ISSUE THREAD

**Issue by jbroudou** [dr-prodigy/python-holidays#266]
See https://github.com/dr-prodigy/python-holidays/blob/61274d44f04f2a1cf8b1cb98a9b57c81ee585d2f/holidays.py#L510

The Brazilian State of Paraná (https://en.wikipedia.org/wiki/Paran%C3%A1_(state)) appears to be the only ISO subdivision of Brazil that is not currently supported by python-holidays.

Is it possible to add support for it?

**Comment by dr-prodigy** [comment]
Done and released on beta branch, thx
