### ISSUE TITLE
Invalid subdivisions in Italy IT

### ISSUE THREAD

**Issue by jbroudou** [dr-prodigy/python-holidays#269]
The bulk of provinces listed for Italy use ISO codes apart from the following:

Cesena
Forli
Pesaro
Urbino

According to the ISO subdivisions list these provinces should be merged. Additionally IT-GO and IT-TS appear to have been abolished.

What's the best way to update these subdivisions on the basis that you agree they need updating?

**Comment by dr-prodigy** [comment]
1) The 4 aforementioned cities as provinces are indeed "merged" like this:
Forlì + Cesena = FC
Pesaro + Urbino = PU
Unfortunately, the 4 cities have all different patron days, so from the holidays PoV they need to be kept apart.
Not being an ISO code for them in existence, they have been referred to with their complete name, as it already was done for French departments.

Meanwhile, instead:
GO = Gorizia
TS = Trieste
are both valid provinces.
