### ISSUE TITLE
Code change for subdivision (CA-YU)

### ISSUE THREAD

**Issue by jbroudou** [dr-prodigy/python-holidays#270]
The project records the following PROVINCE for Canada:
YU
https://github.com/dr-prodigy/python-holidays/blob/61274d44f04f2a1cf8b1cb98a9b57c81ee585d2f/holidays.py#L731

It appears from https://en.wikipedia.org/wiki/ISO_3166-2:CA that the subdivision Yukon should be referred to as CA-YT (not CA-YU).

Can you please confirm this and then we could submit a PR?

**Comment by dr-prodigy** [comment]
Fix released on beta. Closing, thx
