### ISSUE TITLE
Martin Luther King Day is not a federal holiday

### ISSUE THREAD

**Issue by yaohongkok** [dr-prodigy/python-holidays#273]
I believe in line 1444, we need to specify which states should have Martin Lurther King day as a holiday. I know that MA is definitely not one of them.

**Comment by dr-prodigy** [comment]
Hi,
thank you very much for your support.
The code is already managing differences among states about MLK day, and MA is in fact working as you expect.
Would you please provide more complete information on this issue?
Thanks in advance

**Comment by dr-prodigy** [comment]
No news.. closing.

**Comment by yaohongkok** [comment]
Sorry... I just saw this today...

Anyways, when I use the holiday function, it is telling me MLK is a holiday
in MA. Isn't that wrong?

Or do you actually tested it and it says that it is not a holiday?

Maybe I am using the older version?
