### ISSUE TITLE
US Easter Holiday Issues

### ISSUE THREAD

**Issue by EmptyG** [dr-prodigy/python-holidays#279]
Version 0.10.1 Easter is unable to import. Previous version works fine.

ImportError: cannot import name 'easter' from 'holidays' (/usr/local/lib/python3.7/site-packages/holidays/\_\_init\_\_.py)

**Comment by dr-prodigy** [comment]
https://github.com/dr-prodigy/python-holidays/issues/277

**Comment by EmptyG** [comment]
Thank you for the response. The ticket you linked was the exact same issue I was having. I've updated the fbprophet files and have verified your recommendation does work correctly. Thank you for the feedback and I apologize for not reviewing previously submitted tickets before creating my own ticket (I'm new to github).

**Comment by dr-prodigy** [comment]
No problem, glad to help you!
Cheers
dr-p
