### ISSUE TITLE
State Holiday incorrect (Subdivision: US-GA / Year: 2020)

### ISSUE THREAD

**Issue by jbroudou** [dr-prodigy/python-holidays#282]
Per https://georgia.gov/popular-topic/state-holidays Friday, April 10 is a State Holiday in 2020, however we are currently getting 2020-04-27

https://github.com/dr-prodigy/python-holidays/blob/b523509367869228e97f33824e241137920483f3/holidays/countries/united_states.py#L243

**Comment by dr-prodigy** [comment]
Released in beta.. thank you 👍
