### ISSUE TITLE
Use recognised subdivisions for Spain

### ISSUE THREAD

**Issue by jbroudou** [dr-prodigy/python-holidays#283]
"Would it be possible to apply the use of ISO codes to Spain? The use of recognised ISO codes would make integration into other projects easier as a common standard is followed.

Wikipedia lists the ISO 3166-2 codes for Spain at https://en.wikipedia.org/wiki/ISO_3166-2:ES.

The mappings look like they should be as follows

ISO (ES-AN) = AND
ISO (ES-AR) = ARG
ISO (ES-AS) = AST
ISO (ES-CN) = ICA
ISO (ES-CB) = CAN
ISO (ES-CL) = CAL
ISO (ES-CM) = CAM
ISO (ES-CT) = CAT
ISO (ES-CE) = not supported by python-holidays
ISO (ES-EX) = EXT
ISO (ES-GA) = GAL
ISO (ES-IB) = IBA
ISO (ES-RI) = RIO
ISO (ES-MD) = MAD
ISO (ES-ML) = not supported by python-holidays
ISO (ES-MC) = MUR
ISO (ES-NC) = NAV
ISO (ES-PV) = PVA
ISO (ES-VC) = CVA

"

**Comment by dr-prodigy** [comment]
Hi, it makes sense: updated in beta for Spain too. Thank you cheers 👍
