### ISSUE TITLE
Use recognised subdivisions for Austria

### ISSUE THREAD

**Issue by jbroudou** [dr-prodigy/python-holidays#284]
As per #283, is is possible to use standard ISO 3166-2 codes for Austria?

Per wikipedia:
AT-1  Burgenland Burgenland
AT-2  Kärnten Carinthia
AT-3  Niederösterreich Lower Austria
AT-4  Oberösterreich Upper Austria
AT-5  Salzburg Salzburg
AT-6  Steiermark Styria
AT-7  Tirol Tyrol
AT-8  Vorarlberg Vorarlberg
AT-9  Wien Vienna

Per python-holidays - the codes for AT subdivisions are: 'B', 'K', 'N', 'O', 'S', 'ST', 'T', 'V', 'W' (W is the default) which appears to be the first letter of the subdivision name (see wikipedia list).

**Comment by dr-prodigy** [comment]
Hi, released in beta, thank you!

**Comment by dr-prodigy** [comment]
Hi,
in order to maintain consistency with other countries behaviour, these codes have been chosen instead:
1, 2, 3, 4, 5, 6, 7, 8, 9 (default)
