### ISSUE TITLE
 Some Croatian holidays have different dates in 2020

### ISSUE THREAD

**Issue by sebojanko** [dr-prodigy/python-holidays#286]
Hi,
I found this package on another github page (https://github.com/christopherthompson81/pgsql_holidays) and saw that your data for Croatia has also some mistakes so I want to help :)

Last year, the government decided to change some state holidays - https://publicholidays.com.hr/2020-dates/
For fixing this issue, the holiday on the 25th of June should be deleted and a new one should be added on the 18th of November. This one should be named 'Dan sjećanja'.

Keep up the good work!

**Comment by dr-prodigy** [comment]
Just released on beta.. Thank you very much! 👍 
Cheers
dr-p
