### ISSUE TITLE
French country code

### ISSUE THREAD

**Issue by reinaldoramosarxi** [dr-prodigy/python-holidays#287]
Hello,

Would it be possible to add the alpha-2 country code for France? It is the only one that only has an alpha-3 code, which creates inconsistencies in our code by forcing us to validate if the country is France before inserting the code (our software uses alpha-2).

Thank you!

**Comment by dr-prodigy** [comment]
Hi,
thank you very much for pointing this out.
Unfortunately, "FR" is used internally to represent Friday, so we had to leave it out to avoid a name clash. At the moment it is not in the plans, but we will possibly re-consider this request in a future.
Thank you again, cheers!
