### ISSUE TITLE
Incorrect England holiday

### ISSUE THREAD

**Issue by sammaule** [dr-prodigy/python-holidays#288]
Following code shows incorrect holiday dates for England.

```
from datetime import date
import holidays
holiday = holidays.England()
date(2020, 5, 4) in holiday # outputs True
date(2020, 5, 8) in holiday # outputs False
```
in fact 4 May is not a holiday and 8 May is.

**Comment by sammaule** [comment]
Running latest version (0.10.1)

**Comment by lukedyer-peak** [comment]
FYI for a reference: https://www.gov.uk/bank-holidays.  The holiday has been moved for 2020 only (to celebrate VE day).

**Comment by dr-prodigy** [comment]
Hi @sammaule ,
library behaviour is in fact correct: thank you very much @lukedyer-peak for your contribution.
Closing issue, best regards to both of you.
