### ISSUE TITLE
Ash Wednesday holiday in Brazil should not last the whole day

### ISSUE THREAD

**Issue by lucasqueiroz** [dr-prodigy/python-holidays#292]
The Ash Wednesday in Brazil ends at 12pm, and the rest of the day is considered a business day.
Not sure if this is achievable in the lib, but just opening the issue to make sure it can be treated if possible and if other people have the same issue, they can find the possible reason.

**Comment by dr-prodigy** [comment]
Hey there!
Thank you for your report.
Unfortunately, at the moment there is no way to express half days in the results returned by the library, so as for now, we won't be implementing this; anyway, we will possibly evaluate this in a future, so thanks for pointing this out!

Cheers
dr-p
