### ISSUE TITLE
Australian non-public holiday

### ISSUE THREAD

**Issue by cosmicpudding** [dr-prodigy/python-holidays#293]
Hello! Love this package :) Just wanted to check - one of the holidays for NSW Australia returned is a bank holiday on 3rd Aug 2020, but this is actually a holiday just for banks and not a public holiday. is there a way to differentiate between these somehow? Or is this a problem in source data?

c.f. https://www.nsw.gov.au/about-new-south-wales/public-holidays/

**Comment by dr-prodigy** [comment]
Hey there, thank you :-)
Unfortunately, we don't have a differentiation for this yet.. but we will possible consider it for a future release: keeping this open as a reminder.

Thanks again for your help, cheers!
dr-p

**Comment by TroyWilliams3687** [comment]
Remembrance Day, November 11, isn't a public holiday across Canada either. In Ontario, it is for government employees but not across the board.

**Comment by Ghawken** [comment]
Hi 
Well done on maintaining library!

Further to the original request, which I see has been closed, this 3rd August Subdiv=NSW Australia Holiday remains.  

It is a ‘Bank employee’ only holiday and not a public holiday for the vast majority of population.  Seems to be misreported still currently in 0.41
Could be removed, in my mind altogether, OR have add a new category for bank for AU added- and include this current entry as a bank only holiday?  

Thanks for reviewing.
