### ISSUE TITLE
MLK day causes confusion

### ISSUE THREAD

**Issue by snoopyjc** [dr-prodigy/python-holidays#295]
If multiple holidays occur on the same day, they are separated with ", ".  However, Martin Luther King day also contains a ", ", so my program doesn't know if that's a sequence of holidays or what.  I recommend removing the "," from the name of MLK day - in fact I subclassed Holidays and did just that!

**Comment by dr-prodigy** [comment]
Good point.. fixed and pushed on beta branch.
Cheers!
dr-p

**Comment by raffg** [comment]
This issue still exists with the Idaho holiday:
https://github.com/dr-prodigy/python-holidays/blob/02d5d510202a02471cd0a939a11525cf02ca115c/holidays/countries/united_states.py#L107
I suggest removing the comma here as well. Or, in case this issue arises in other countries, maybe change the delimiter to a semicolon?
