### ISSUE TITLE
Fix March 19 on Spain

### ISSUE THREAD

**Issue by gerardo15** [dr-prodigy/python-holidays#296]
Hello,

I think this date should be removed from the Holidays because each year it randomly changes between the states.. for example this year only the following states celebrates it:

Galicia, País Vasco, Navarra, Castilla-La Mancha, Región de Murcia y Comunidad Valenciana.

It would be impossible to follow it each year as it is a "exchangable holiday" so each year only 6 states in the country gets to celebrate it. for example in the current file MADRID its on it. but MADRID does not celebrate it..

I just realized all this because it did not wake me up for work haha

**Comment by dr-prodigy** [comment]
Hi,
thank you for your interest and support. We have updated Spanish holidays according to this: 
https://www.timeanddate.com/holidays/spain/san-jose

Thank you very much, cheers
dr-p
