### ISSUE TITLE
Latvia holiday calendar

### ISSUE THREAD

**Issue by jluttine** [dr-prodigy/python-holidays#303]
Thanks for the package! Just wanted to make it known that someone here is interested in Latvia holiday calendar. I might also do it myself if I find the time (and the information), we'll see.

**Comment by rolandinsh** [comment]
Made that :) : https://github.com/dr-prodigy/python-holidays/pull/314

**Comment by dr-prodigy** [comment]
Merged! 👍 
Thx
dr-p

**Comment by jluttine** [comment]
@rolandinsh Wow, thanks a lot!!!
