### ISSUE TITLE
Error Labor Day in Spain

### ISSUE THREAD

**Issue by gerardo15** [dr-prodigy/python-holidays#307]
Hello!

Today is labor day in the whole country, but i see in the file that is only counted for some provinces!

https://github.com/dr-prodigy/python-holidays/blob/345b458b194198b51dfa4dd3207f6e0159151793/holidays/countries/spain.py#L57

**Comment by sermayoral** [comment]
Hi! Same here.

May 1 is holiday for all the country: https://en.wikipedia.org/wiki/Public_holidays_in_Spain

Thanks!

**Comment by dr-prodigy** [comment]
Fixed and released on beta branch, thx
dr-p
