### ISSUE TITLE
Spain Holidays that fall on Sunday are passed to Monday always

### ISSUE THREAD

**Issue by sermayoral** [dr-prodigy/python-holidays#308]
This year there are two days that fall on Sunday:

- 2020-11-01 Todos los Santos
- 2020-12-06 Día de la constitución Española

These days are not holidays. Right dates are:
- 2020-11-02 Todos los Santos
- 2020-12-07 Día de la constitución Española

More info in https://www.qppstudio.net/publicholidays2020/spain.htm

**Comment by dr-prodigy** [comment]
Please check my comments on #310

**Comment by dr-prodigy** [comment]
No updates on this: closing, thx
dr-p

**Comment by sermayoral** [comment]
Sorry @dr-prodigy I have recently had a baby, so no time to opensource.

In a close future, when i have time, i will open a new issue regarding this again.

I hope you understand it.
