### ISSUE TITLE
Only empty sets returned

### ISSUE THREAD

**Issue by thomas-woodruff** [dr-prodigy/python-holidays#312]
Hello there,

I've just installed the most recent version of `holidays` on pip: `holidays-0.10.2`.

This only seems to return empty sets however:

```
>>> import holidays
>>> holidays.UnitedStates()
{}
```

Any idea what the problem may be?

Thanks,
Tom

**Comment by thomas-woodruff** [comment]
Ah, it appears I need to pass a `years` argument too!

**Comment by r-luo** [comment]
This is actually helpful as their official get started guide doesn't include that argument, and I was so confused...
