### ISSUE TITLE
Holidays returning always "False" when using no parameters?

### ISSUE THREAD

**Issue by Marmeladenbrot** [dr-prodigy/python-holidays#323]
I have a column "date" in ISO 8601 with days for 2018, 2019 and 2020.

When using the holiday package without parameters

    de_holidays = holidays.DE()
    traffic["holiday"] = traffic["date"].isin(de_holidays)

It returns "False" for every row.

When using "years" as a parameter it works

    de_holidays = holidays.DE(years=[2018, 2019, 2020])
    traffic["holiday"] = traffic["date"].isin(de_holidays)

Regarding to the documentation of the package it should work automatically when using "expand=False" but default is "expand=True".
So "years" should not be required in my case?

**Comment by stephanie-mak** [comment]
Yes it was working fine without parameters yesterday and for some reason it now requires the years parameter (no restart nor reinstall since yesterday). 
Please either update the Example Usage or default to have no year parameters required.

**Comment by dr-prodigy** [comment]
Hi,
sorry but it's not clear what kind of object `traffic["date"]` is.
More in general, if no `years` parameter is provided, the library initializes itself as empty. Then, if `expand` is set to `true` (default behaviour) whenever a date object is queried for existance in the holidays object (usually done with `in` operator), its all relevant year's holidays are loaded in the library object, so from there on, it will contain all that year's holidays.
This applies to any further date existance check, which will append all the involved years to the holidays object list. 

Would you please better explain your issue?

Thanks in advance, cheers
dr-p
