### ISSUE TITLE
Every Sunday in Norway is a holiday

### ISSUE THREAD

**Issue by robbieandrew** [dr-prodigy/python-holidays#324]
While it's true that most people don't work on Sundays in Norway, they are certainly not public holidays in the normal sense. But the holidays package returns every single Sunday as a holiday for Norway. Second vote for having a flag to distinguish different sorts of holidays.

**Comment by dr-prodigy** [comment]
Hi,
thank you for your interest in python-holidays.
Please refer to here:
https://translate.google.it/translate?hl=&sl=auto&tl=en&u=https%3A%2F%2Fsnl.no%2Fhelligdag
"[...] The following days are holidays in Norway:
- regular Sundays [...] "
This is explained here:
https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/norway.py#L30

We will consider a specific flag adoption for this, but at the moment this is not a priority.
Thank you again, cheers
dr-p
