### ISSUE TITLE
Failing to get non-mutual german state holidays 

### ISSUE THREAD

**Issue by abdullahmsalama** [dr-prodigy/python-holidays#325]
so I run this-> holidays.DE(state= 'BY', years=2020). This is bavaria and I still get only the mutual holidays in Germany. How can I get the holidays per state?, is there something I am doing wrong?

**Comment by dr-prodigy** [comment]
Hi,
when you wish to refer to german federal states, you should initialize holidays with "prov" parameter:
>>> import holidays
>>> a = holidays.DE(prov='BY', years=2020)

Thank you very much, cheers
dr-p
