### ISSUE TITLE
Get date by holiday string

### ISSUE THREAD

**Issue by rosiecakes** [dr-prodigy/python-holidays#326]
Hello! I feel like this is a dumb question but am just not seeing anything about it in the readme. 

Is there a method that supports something like `us_holidays.get('Thanksgiving')`? 

For example if I wanted to add the day after Thanksgiving to my custom calendar, I will need to first get that holiday, which feels like an odd thing to do manually with a library that handles holidays - 

```
class MyCal(holidays.UnitedStates):
    def _populate(self, year):
        holidays.UnitedStates._populate(self, year)
        # Add Friday after Thanksgiving
        thanksgiving = date(year, 11, 1) + rd(weekday=TH(+4))
        thanksgiving_friday = thanksgiving + rd(days=1)
        self[thanksgiving_friday] = 'Thanksgiving Friday'
```

(this is just an example, I know I can get the day other ways)

**Comment by samtregar** [comment]
I just added this to my new module, holidays_plus:

https://github.com/samtregar/python-holidays-plus

**Comment by mborsetti** [comment]
> I just added this to my new module, holidays_plus:
> 
> https://github.com/samtregar/python-holidays-plus

Great functionality but ... _really_?  You couldn't contribute to _this_ project? <shakehead>

**Comment by dr-prodigy** [comment]
Hi, 
thank you for your interest in holidays library.
I've added get_named(key) method, receiving a complete or partial string, which will be checked against all currently available holidays (ie: depending on initialization), applying a case insensitive match.
Results are returned in a list containing all matched dates.

Pushed on beta branch, thank you again, cheers!
dr-p

**Comment by samtregar** [comment]
Excellent - this will make implementing pop_named() in my module much simpler - unless you'd like to take that suggestion now too?  There's a closed PR you could use!  :)

**Comment by samtregar** [comment]
Oh and I see you did that.  Awesome all around - thanks!

**Comment by dr-prodigy** [comment]
@samtregar Glad to be helping! Sorry for getting there a little late, but better late than never.. :)
