### ISSUE TITLE
Missing Swiss holidays

### ISSUE THREAD

**Issue by kasparthommen** [dr-prodigy/python-holidays#336]
Hi,

The following Swiss holidays are missing:
- 2nd of January
- 1st of May
- 26th of December

See here:
- https://vschweiz.ch/feiertage-schweiz/
- https://de.wikipedia.org/wiki/Feiertage_in_der_Schweiz

**Comment by mborsetti** [comment]
Thanks for your input!

According to the code:
- 2nd of January is a holiday in cantons 'AG', 'BE', 'FR', 'GL', 'GR', 'JU', 'LU', 'NE', 'OW', 'SH', 'SO', 'TG', 'VD', 'ZG', 'ZH' 
- 1st of may is a holiday in cantons 'BL', 'BS', 'JU', 'NE', 'SH', 'SO', 'TG', 'TI', 'ZH'
- 26th of December is a holiday in cantons 'AG', 'AR', 'AI', 'BL', 'BS', 'BE', 'FR', 'GL', 'GR', 'LU', 'NE', 'NW', 'OW', 'SG', 'SH', 'SZ', 'SO', 'TG', 'TI', 'UR', 'ZG', 'ZH'

This matches what's in Wikipedia.  Did you request the holidays for a specific Canton?  The code currently defaults to none (i.e. to reporting only holidays that are National in scope)

**Comment by kasparthommen** [comment]
Hi, thanks for your comment. You are right, these are already properly defined in the code for the respective cantons. I was under the false impression that these three dates were national holidays where in fact it depends on the canton. I'll close the issue accordingly.
