### ISSUE TITLE
Unable to install version 0.10.3

### ISSUE THREAD

**Issue by s-weigand** [dr-prodigy/python-holidays#338]
For version 0.10.3 the [uploaded files on PyPi](https://pypi.org/project/holidays/0.10.3/#files) only have a sdist for macos, this prevents installation on other operation systems. 
Could you upload a general tarball [as it was done before](https://pypi.org/project/holidays/0.10.2/#files).
Thanks a lot

**Comment by Mangips** [comment]
I have the same issue, on Windows 10 I had to install it with 
`pip install --upgrade https://github.com/dr-prodigy/python-holidays/tarball/master`

With that I managed to install version 0.10.3.

**Comment by s-weigand** [comment]
@dr-prodigy If you are interested I could make a PR that sets up [github actions](https://github.com/features/actions) as CI+CD, so it will build and deploy automatically when you push a tag.

**Comment by dr-prodigy** [comment]
Hi,
unfortunately, in fact, PyPi has changed its behaviour, and now doesn't accept multiple source packages anymore.
Now it should be fixed (I've quit macos version in favour of the standard one), please confirm thank you! 👍
 
On the other hand, it would be really interesting to add CI+CD to the project: I would highly appreciate any help on this, thank you @s-weigand ! I'm at disposal for clarifications / suggestions.

Cheers,
dr-p

**Comment by s-weigand** [comment]
@dr-prodigy I can confirm that it works on Linuxs, Windows and MacOS, thanks a lot 😄 

I will make a PR with github actions CI+CD workflow this week.
For managing versioning I use [bump2version](https://pypi.org/project/bump2version/), with this (+CD) a new release is as easy as two command:
```bash
$ bump2version major|minor|patch
$ git push --follow-tags
```
Would you want to use that too?

**Comment by dr-prodigy** [comment]
Hi @s-weigand 
great to know everything is in shape now thx!

Bump2version is very interesting too 👍
So yes please, let's work on it too, thank you very much! Please let me know if I can help you in any way.

Cheers
dr-p
