### ISSUE TITLE
List with "Available countries" is wrong for 2020

### ISSUE THREAD

**Issue by vin2015-edem** [dr-prodigy/python-holidays#340]
I took a list of countries and checked "Available countries" with the command
```
make_holidays_df([2020],  country)

```

> where: country = 'Latvia' or  'LV' or 'LVA'...

Results:
1. Countries that are on this list, but their holidays are not available

> ['Burundi', 'Latvia', 'Morocco']

2. Countries that are not on this list, but their holidays are available

> ['China', 'Indonesia', 'Philippines', 'Thailand']

3. A list of country codes, the holidays of which are available, but it is difficult to find them there because of incorrect names (not according to ISO, see **pycountry**):

> ['DO', 'GB', 'KR', 'NZ', 'RU', 'US', 'ZA']

4. There is a problem with short country codes (according to ISO):
- there are 'France', 'FRA', 'Honduras', 'HND', 'Turkey' but there are not 'FR', 'HD', 'TR', TUR'.

Please correct it.

**Comment by mborsetti** [comment]
I add my vote to be 100% [ISO 3166-1](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) (alpha-2) code compliant.  I don't think there's much use of the alpha-3 codes so I'd just drop them all; otherwise they also need to be present for all countries.

**Comment by vin2015-edem** [comment]
I fixed all these problems and added 5 new countries (Europe). But the holidays' format doesn't fit me for solving the coronavirus problem (I found a bug in Prophet and suggested that to 
Prophet team makes changes to their code, but they refused and offered to change the parameters of the library "holidays" - see [issue](https://github.com/facebook/prophet/issues/1588)). I decided not to beg anyone and made [my dataset](https://www.kaggle.com/vbmokin/covid19-holidays-of-countries) in Kaggle. It doesn't contain all these errors, it is adapted to the coronavirus task, and I plan to develop it further (for more countries). You can take and carry on to "holidays" all the information that you think is necessary. Good luck!

**Comment by dr-prodigy** [comment]
Thank you! Good luck to you too! 👍
