### ISSUE TITLE
[Question] Tooling changes

### ISSUE THREAD

**Issue by s-weigand** [dr-prodigy/python-holidays#341]
As promissed in https://github.com/dr-prodigy/python-holidays/issues/338#issuecomment-662592391 I'm working on a PR to change the CI from travis to github actions and also add CD.

Since you liked the idea of using `bump2version`, for releas process.
I was wondering if would also be interested in some other changes:
- Autoformat code with [`black`](https://github.com/psf/black), so formatting code to look nice is a no brainer
- Add  [`pre-commit`](https://pre-commit.com/) to run `back` and `flake8` on commit, like that  there won't be commits like `fix flake8` which I saw a lot on other projects
- Style check the tests with `flake8`, IMHO tests should also comply with styling rules
- Use [`pytest`](https://docs.pytest.org/en/latest/) as testrunner, `pytest` is more prowerful (and gives prettier output) than good old `unittest` and would also allow to restructure the tests to mimic the projects structure, which again would make it easier to find corresponding tests
- Use [`tox`](https://tox.readthedocs.io/en/latest/) so contributors can tests multiple python version locally

**Comment by s-weigand** [comment]
Also, since the [coveralls action doesn't support xml reports](https://github.com/coverallsapp/github-action/issues/30), I would use [codecov](https://codecov.io/) instead.

**Comment by mborsetti** [comment]
This would be so nice!

**Comment by dr-prodigy** [comment]
We are on the way to release this soon.. Closing this question, thx! 👍
