### ISSUE TITLE
Would it be possible to download all a country's holidays, including those of the states/provinces?

### ISSUE THREAD

**Issue by EddyvK** [dr-prodigy/python-holidays#345]
Hi, thank you for creating this. It has been really useful.

What I was wondering: would it be possible to download all a country's holidays, including those of the states/provinces. E.g. through enabling a states='all' or prov=[AB, BC, MB]?

Thanks again and regards, Eduard

**Comment by mborsetti** [comment]
Not that I can think of. Just create a loop to pull one state/province at a time.

**Comment by dr-prodigy** [comment]
Unfortunately, due to the project structure, this is not currently possible.
On the other hand, I confirm the solution from @mborsetti is perfectly adequate, yet easy to implement.
Thank you both, best regards
dr-p
