### ISSUE TITLE
Revisit #211 to include FR for France

### ISSUE THREAD

**Issue by ramonfm** [dr-prodigy/python-holidays#348]
This is an appeal to reconsider the request in #211 

Started using this library and I really like it, but this one exception to the [iso3166 standard](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) is most unexpected. I'll skip a lengthy opinion on the value of standards and go directly to my question: if there was a pull request to adhere to iso3166, would it be considered? Or would that be wasted work because of reasons (backwards compatibility or anything else)?

Thanks,
rfm.

**Comment by crashdomi** [comment]
Two-letter standards would be heavily appreciated. Non-compatibility with certain countries is [surprising](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), to say the least. Thank you!
