### ISSUE TITLE
pop_named() sometimes generates an exception

### ISSUE THREAD

**Issue by rccoleman** [dr-prodigy/python-holidays#349]
This simple code block generates an exception when I try to pop "Columbus Day" (last line):

```
from datetime import date
  
import holidays

us_holidays = holidays.CountryHoliday('US', prov=None, state='CA', years=2022)

print(us_holidays.get('2022-10-10').format("%s"))

us_holidays.pop_named("Columbus Day")
```

The exception is `dictionary changed size during iteration`, and it seems to be related to popping elements out of a dictionary while you're iterating through it: https://stackoverflow.com/questions/11941817/how-to-avoid-runtimeerror-dictionary-changed-size-during-iteration-error.  The element to be popped isn't actually removed.

I'm far from a competent Python programmer, but iterating over `list(self)` seems to solve the problem for me - no exception, and the item is removed properly:

```
    def get_named(self, name):
        # find all dates matching provided name (accepting partial
        # strings too, case insensitive), returning them in a list
        return [key for key in list(self) if name.lower() in self[key].lower()]
```

**Comment by dr-prodigy** [comment]
Thank you @rccoleman + @mborsetti ! 👍 Merged on beta.
