### ISSUE TITLE
MLK still causes confusion at the state level

### ISSUE THREAD

**Issue by raffg** [dr-prodigy/python-holidays#351]
If multiple holidays occur on the same day, they are separated with a `,`. This issue was fixed for `Martin Luther King, Jr. Day` by removing the comma (https://github.com/dr-prodigy/python-holidays/issues/295), however for Idaho the issue still exists:
https://github.com/dr-prodigy/python-holidays/blob/02d5d510202a02471cd0a939a11525cf02ca115c/holidays/countries/united_states.py#L107
I suggest removing the comma here as well. Or, in case this issue arises in other countries, maybe change the delimiter to a semicolon?

_Originally posted by @raffg in https://github.com/dr-prodigy/python-holidays/issues/295#issuecomment-680171130_

**Comment by dr-prodigy** [comment]
Fixed and released in beta, thanks
dr-p
