### ISSUE TITLE
MX holidays incorrect for "Benito Juarez's Birthday (observed)"

### ISSUE THREAD

**Issue by krzheng3150** [dr-prodigy/python-holidays#356]
For MX, seems like Benito Juarez's Birthday is incorrect.

In 2021 it's March 21. But there are TWO instances of "Benito Juarez's Birthday (observed)", one on March 15 and one on April 30.

For MX in 2022, Benito Juarez's Birthday does not appear at all, and instead we again have TWO instances of "Benito Juarez's Birthday (observed)", one on March 21 and one on May 2.

In 2023, we again have "Benito Juarez's Birthday" on **Tuesday** March 21 and "Benito Juarez's Birthday (observed)" on **Monday** March 20.

**Comment by mborsetti** [comment]
Thanks for the report.

Am not sure why the package reports **both** the observed and the "base" (March 21) holiday, and am not changing this behavior until I hear from @dr-prodigy .

However, I have made a PR to fix the bug that led to the extra "Benito Juarez's Birthday (observed)" in 2021 as #377

**Comment by dr-prodigy** [comment]
Hi, thank you. This issue has been solved with @mborsetti 's work on #377
Closing, thank you both!
