### ISSUE TITLE
Support for Non-Country Holidays

### ISSUE THREAD

**Issue by sblanton** [dr-prodigy/python-holidays#365]
Other entities have holidays, like your company and a commonly followed holiday schedule is the stock market holidays - many companies follow NASDAQ holidays.  And, guess who all don't want their python programs running on NASDAQ holidays - many companies!    Maybe this gets into the realm of a custom holiday that people can add themselves, though thousands care about the NASDAQ holiday calendar.  Nice work. Cheers

**Comment by mborsetti** [comment]
ECB holidays are already supported.

Can you provide authoritative list of NASDAQ holidays?

**Comment by dr-prodigy** [comment]
Marking closed, thx both, cheers
