### ISSUE TITLE
Wrong workday info for country HR

### ISSUE THREAD

**Issue by haseat** [dr-prodigy/python-holidays#369]
Today (Oct. 8, 2020) my alarmclock automation did not go off, because my workday sensor gave the wrong info (no workday). This day used to be a holiday in Croatia, but is not anymore.

binary_sensor:
  - platform: workday
    country: HR

![image](https://user-images.githubusercontent.com/61622258/95419607-4082d000-093a-11eb-904c-77a2639b1719.png)

**Comment by dr-prodigy** [comment]
Hi,
fix merged in beta.. thank you very much @haseat and @mborsetti !
Cheers
dr-p
