### ISSUE TITLE
Problem when checking a date with unknown year in a pandas series

### ISSUE THREAD

**Issue by sebastianfastert** [dr-prodigy/python-holidays#382]
Intuitively I'd think the following test should work.
But the only the first assertEqual is fine.
The second fails, because _populate was never called with the year 2026.

```
us = holidays.UnitedStates(years=[2025])
df = pd.DataFrame.from_dict({"date": [date(2025, 1, 1), date(2025, 1, 2)]})
self.assertEqual(df["date"].isin(us).tolist(), [True, False])
df = pd.DataFrame.from_dict({"date": [date(2026, 1, 1), date(2026, 1, 2)]})
self.assertEqual(df["date"].isin(us).tolist(), [True, False])
```

I changed the __contains__ method of the HolidayBase class.

```
    def __contains__(self, key):
        if str(type(key)) == "<class 'pandas.core.series.Series'>":
            res = []
            for k in key:
                res.append(dict.__contains__(self, self.__keytransform__(k)))
            return res
        return dict.__contains__(self, self.__keytransform__(key))
```

Using this it kind of works...
But I don't think it's a nice solution.

**Comment by dr-prodigy** [comment]
Hi,
unfortunately, although probably working, I don't think we can accept this code, sorry.
If you could design a cleaner code to accomplish that (I'm no pandas expert) I will surely consider your improvement.
Thank you very much, cheers

**Comment by sebastianfastert** [comment]
Hi,
I agree, it's bad code...
This is the first time I'm writing something for an opensource project and I can't find a good solution.
Maybe it's better to just add a few lines to the README.

Something like:
```
df = pd.DataFrame.from_dict({"date": [datetime(2026, 1, 1), datetime(2026, 1, 2)]})
us = holidays.UnitedStates(years=df.date.dt.year.unique())
```

**Comment by giladmaya** [comment]
@sebastianfastert which pandas version are you using? I've tried your initial solution with pandas 0.24.0 and `HolidayBase.__contains__` isn't triggered at all when using `.isin` therefore 2026 isn't expanded and the second test fails
