### ISSUE TITLE
hebrew.to_jd_gregorianyear(...) cannot unpack non-iterable float object in python 3

### ISSUE THREAD

**Issue by carma31** [dr-prodigy/python-holidays#391]
Hi,

I am using fbprophet 0.7.1 and holidays 0.10.3 but since Nov 8th I am getting an error when trying to add holidays from Israel.
In holidays it is used hebrew module from convertdate.

`When
30 # Passover
31 name = "Passover I"
---> 32 year, month, day = hebrew.to_jd_gregorianyear(year, hebrew.NISAN, 14)
33 passover_start_dt = date(year, month, day)
34 self[passover_start_dt] = name + ' - Eve'

TypeError: cannot unpack non-iterable float object`

¿Is this related to last convertdate 2.3 release of Nov 7th?

**Comment by dr-prodigy** [comment]
Hi,
yes, in fact it is so.
For this issue, we decided to temporarily keep convertdate back to 2.2.0: we'll then investigate the issue.
Workaround released (and reviewed again just now) on beta branch.

Thx

**Comment by mayag-gett** [comment]
@dr-prodigy did you start working on the fix? if not, I'll be happy to

**Comment by giladmaya** [comment]
@dr-prodigy did you start working on this? if not, I'll be happy to

**Comment by dr-prodigy** [comment]
Just released in beta. Thank you very much for your good work! 👍
