### ISSUE TITLE
self.country values seem inconsistent.

### ISSUE THREAD

**Issue by agorajek** [dr-prodigy/python-holidays#405]
Hi, is there a particular reason that all the country classes use the two letter abbreviation for their `self.country` value except these four: 

- Ireland --> using Ireland
- India --> using IND
- Honduras --> using HND

Feels inconsistent and makes my life much harder. Wondering if this is a typo or is it by design?

**Comment by dr-prodigy** [comment]
Hi,
thank you for your support: requested fixes have been released in beta.
Best regards
