### ISSUE TITLE
RuntimeError when using get_named for year 2022

### ISSUE THREAD

**Issue by katscott** [dr-prodigy/python-holidays#409]
When trying to get a named holiday such as "Thanksgiving" for 2022 a RunTime error occurs.
```
RuntimeError: dictionary changed size during iteration
```
(same error as closed issue #355)

reproduction: https://repl.it/@katscott/holidays2022#main.py

sample code:
```
holidays = holidays.US(years=[2022])
thanksgiving = holidays.get_named("Thanksgiving")
```

**Comment by giladmaya** [comment]
Additional information regarding this bug:
When you use 2022 with US holidays, New Year's Day is observed and "goes back" 1 day into 2021.
During the search for any holiday using `get_named` function, at some point the observed date is reached and triggers the code to expand data for 2021 which results in the runtime change of holiday lists

**Comment by dr-prodigy** [comment]
Fix released in beta. Thank you both 👍
