### ISSUE TITLE
Help with adding holidays for Sri Lanka

### ISSUE THREAD

**Issue by batmanscode** [dr-prodigy/python-holidays#412]
Hi, I'd like to add [holidays for Sri Lanka](https://publicholidays.lk/2020-dates/). I'm a noob but I figure I could use another country's holiday code as a guide/template.

Apart from fixed date holidays (like Christmas) there are some that don't have the same date. For example Poya is a very frequent holiday where the dates usually match the full moon. I'm not sure how this could be implemented.

Any ideas on how this can be done?

**Comment by giladmaya** [comment]
@batmanscode try using [pylunar](https://pypi.org/project/pylunar/) package
