### ISSUE TITLE
The alternative holiday in Korea is wrong.

### ISSUE THREAD

**Issue by janggiKim** [dr-prodigy/python-holidays#414]
I watched wrong korea holiday.

I watched under url,  182th line. 
https://github.com/dr-prodigy/python-holidays/blame/master/holidays/countries/korea.py
        name = "Alternative public holiday"
        alt_date = date(2020, OCT, 17)
        self[alt_date] = name

Korean Alternative public holiday was August. 
Could you change holiday?

**Comment by ywkim92** [comment]
Yes, I agree. Please check it.

**Comment by dr-prodigy** [comment]
Hi, released in beta. Thank you both, cheers
