### ISSUE TITLE
Always generates 2020 calendar for Korea

### ISSUE THREAD

**Issue by spar7453** [dr-prodigy/python-holidays#415]
t = holidays.CountryHoliday("KR", years = [2021])

returns 2021 calendar and also 2020 calendar

**Comment by ywkim92** [comment]
![image](https://user-images.githubusercontent.com/66911578/106544366-beeb2980-654a-11eb-93a1-1b6a5455157d.png)

**Comment by dr-prodigy** [comment]
Released in beta, thx 👍
