### ISSUE TITLE
Collecting holidays for Singapore takes to long!

### ISSUE THREAD

**Issue by mateuszserocki-kinesso** [dr-prodigy/python-holidays#418]
Hi folks!

I noticed that, in newest version of you package (10.4), simple code which I'm already using takes a lot of time and at the end it raise error. I noticed that it happens only for 'Singapore'. In version 10.3 and earlier (10.2 for sure) it works normally. Please take a look into that. The following code is used daily in the popular fbprophet python package.
Code below

Best regards,
Mateusz Serocki

Checked on Windows and Linux
Python version 3.7
holiday version 10.4
hijri-converter version 2.1.1 # after uninstalled that package the problem still occurs with additional warning messages to install that one
```

import holidays #(version 10.4)
import numpy as np

country='Singapore'
years = np.arange(1995,2045)
holiday_names = getattr(holidays, country)(years=years).values() # <- it raise error
```
I attached error logs
[holidays error.txt](https://github.com/dr-prodigy/python-holidays/files/5885868/holidays.error.txt)

**Comment by mborsetti** [comment]
I fixed the slowness issue with the above PR #419 (it was due to an architecture choice I had not taken into consideration), but I cannot replicate the separate OverflowError("date out of range") error from `hijri_converter`. Please make sure you have the latest version of that library, i.e. 2.1.1 (https://pypi.org/project/hijri-converter/) 

```
>>> import holidays # (version 0.10.4 with speed patch)
... import numpy as np
... country = 'Singapore'
... years = np.arange(1995, 2045)
... holiday_names = getattr(holidays, country)(years=years).values() # <- no error
... print(f'{len(holiday_names)=}')
len(holiday_names)=628
```

**Comment by mateuszserocki-kinesso** [comment]
@mborsetti  thank you for help! Waiting till PR will on master. 


Best regards,
Mateusz Serocki

**Comment by dr-prodigy** [comment]
Hi @mateuszserocki-kinesso , this has seen release last April. Closing, thx!
