### ISSUE TITLE
Can't un-pickle a `HolidayBase`

### ISSUE THREAD

**Issue by avivrosenberg** [dr-prodigy/python-holidays#421]
Seems that after a holidays class, e.g. `holidays.UnitedStates()` is used once, it can't be un-pickled.

For example, this snippet:

```python
import holidays
import pickle
from datetime import datetime

# Works:
us_holidays = holidays.UnitedStates()
us_holidays_ = pickle.loads(pickle.dumps(us_holidays))
b = datetime.fromisoformat("2020-01-01") in us_holidays_

# Fails:
us_holidays = holidays.UnitedStates()
b = datetime.fromisoformat("2020-01-01") in us_holidays
dump = pickle.dumps(us_holidays)
pickle.loads(dump)  # <- exception
```

Raises the following exception from the last line:
```
~/.local/share/virtualenvs/sibylla-v2-LxBhzJgn/lib/python3.8/site-packages/holidays/holiday_base.py in __setitem__(self, key, value)
    116
    117     def __setitem__(self, key, value):
--> 118         if key in self:
    119             if self.get(key).find(value) < 0 \
    120                     and value.find(self.get(key)) < 0:

~/.local/share/virtualenvs/sibylla-v2-LxBhzJgn/lib/python3.8/site-packages/holidays/holiday_base.py in __contains__(self, key)
     73
     74     def __contains__(self, key):
---> 75         return dict.__contains__(self, self.__keytransform__(key))
     76
     77     def __getitem__(self, key):

~/.local/share/virtualenvs/sibylla-v2-LxBhzJgn/lib/python3.8/site-packages/holidays/holiday_base.py in __keytransform__(self, key)
     67             raise TypeError("Cannot convert type '%s' to date." % type(key))
     68
---> 69         if self.expand and key.year not in self.years:
     70             self.years.add(key.year)
     71             self._populate(key.year)
```

The `expand` attribute is set by `__init__`, but it's not there during deserialization via unpickling.
I think it's because the `HolidayBase` inherits from dict and there's some weirdness there - it seems to first populate the dict in the deserialized object and only then sets the attributes from the state. But since `HolidayBase` overrides `__setitem__` and in this override it's using state attributes that weren't yet set on the object, the `expand` attribute is missing.

Tested with `holidays=='0.10.4'`.

**Comment by DSchmidtDev** [comment]
Hi, 
great package but having the same issue here with `holidays=='0.10.5.2'`

**Comment by dr-prodigy** [comment]
Hi,
thank you, this is not fixed yet, and will be considered in a next release: thx for your patience.

**Comment by giladmaya** [comment]
@dr-prodigy have you started working on this? if not, I can work on this
