### ISSUE TITLE
Tests don't pass because of flake8 E501 line too long

### ISSUE THREAD

**Issue by mweinelt** [dr-prodigy/python-holidays#423]
Tests run on 0.10.4 and 0.10.5.

```
FAIL: test_flake8 (tests.TestFlake8)
Test that we conform to PEP-8.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/holidays-0.10.5/tests.py", line 35, in test_flake8
    self.assertEqual(self.report.get_statistics('E'), [])
AssertionError: Lists differ: ['1 E501 line too long (82 > 79 characters)'] != []

First list contains 1 additional elements.
First extra element 0:
'1 E501 line too long (82 > 79 characters)'

- ['1 E501 line too long (82 > 79 characters)']
+ []

----------------------------------------------------------------------
Ran 579 tests in 23.641s
```

**Comment by dr-prodigy** [comment]
Hi,
I'm trying to reproduce this issue, but no luck, either calling
`flake8`
directly and either via
`coverage run --omit=*site-packages* tests.py TestFlake8`

Please let me know if you have any further details, thank you very much!

**Comment by mweinelt** [comment]
It seems to happen here:

```
/build/holidays-0.10.5.2/holidays/__init__.py:15:80: E501 line too long (82 > 79 characters)
```

https://github.com/dr-prodigy/python-holidays/blob/cb875fb87e91f8c555966659bca1636519c47d6f/holidays/__init__.py#L15

**Comment by mweinelt** [comment]
And it seems you are not seeing this, because you have excluded this file, but somehow that exclusion doesn't work for us when running the tests.

https://github.com/dr-prodigy/python-holidays/blob/master/.flake8#L3

**Comment by dr-prodigy** [comment]
Oh I see.. that's pretty weird: flake8 is in fact instructed by .flake8 file to skip some warnings / files (most notably __init__.py), which works both in local and on Travis CI since a large number of past releases.

Fixing that long row is easy and I will do it (thank you for your details btw) but still, if .flake8 file is ignored for any reason, some other issues should than arise, such as:
```
./holidays/__init__.py:13:1: F403 'from holidays.countries import *' used; unable to detect undefined names
```

Any ideas?

**Comment by mweinelt** [comment]
No idea. Though the flake8 test has its own style guide, too. Not sure how that influences the .flake8 file.

**Comment by dr-prodigy** [comment]
Ok, np.. in the meantime, I released the fix on beta. Thx cheers
