### ISSUE TITLE
Could not find a version that satisfies the requirement hijri_converter (from holidays)

### ISSUE THREAD

**Issue by chauhan47** [dr-prodigy/python-holidays#427]
We are facing this issues. after taking the latest holiday pypi library 0.10.5.2

"runError": "Run result unavailable: job failed with error message\n Library installation failed for library due to user error for Some(pypi {\n package: \"holidays\"\n}\n). Error messages:\njava.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, holidays, --disable-pip-version-check) exited with code 1. ERROR: Could not find a version that satisfies the requirement hijri_converter (from holidays) (from versions: none)\nERROR: No matching distribution found for hijri_converter (from holidays)\n for library:PythonPyPiPkgId(holidays,None,None,List()),isSharedLibrary=false", "effectiveIntegrationRuntime": "DefaultIntegrationRuntime (East US)"

**Comment by dr-prodigy** [comment]
Hi,
I've just uploaded to PyPi a build for Python3.9 ( holidays-0.10.5.2-py3.9.egg ), which in fact was not there yet.
Pls let me know if it sorts this out, thx

**Comment by dr-prodigy** [comment]
Closing this, thx
