### ISSUE TITLE
New Zealand announces a new public holiday

### ISSUE THREAD

**Issue by alanstockwell** [dr-prodigy/python-holidays#428]
Something you may not be aware of is that a new public holiday has been announced recently in New Zealand.

https://www.rnz.co.nz/news/national/435789/prime-minister-jacinda-ardern-reveals-date-of-first-matariki-public-holiday

The first date it will occur is Friday 24 June 2022. My understanding at this time is that it will be a wandering holiday as it is based on the position of a specific constellation in the sky. A committee has been formed to determine future dates based on consensus over when the position of said constellation is in the correct place in a given year. I am not clear as of writing on the definition of "correct place".

**Comment by nickrout** [comment]
There will be legislation introduced to parliament in due course, but we may need to automate a cultural committee :)

**Comment by 36wish** [comment]
I'm working on it, pull request coming soon.

**Comment by nickrout** [comment]
The 30 years of dates have been published, but I am not sure where. This News article has the dates, but I would not classify it as canonical https://www.rnz.co.nz/news/national/445990/matariki-public-holiday-dates-for-next-30-years-announced

**Comment by 36wish** [comment]
#499 pull request created.

I used the file published by the government here: https://www.mbie.govt.nz/assets/matariki-dates-2022-to-2052-matariki-advisory-group.pdf

I tried to calculate the dates using a formula but isn't having much success at the moment so just listing them for now

**Comment by 36wish** [comment]
```
import datetime
from lunarcalendar import Converter, Solar, Lunar, DateNotExist

for year in range(2022,2053):


  lunar = Lunar(year, 5, 23)
  solar = Converter.Lunar2Solar(lunar)

  startdate = solar.to_date()
  
  convert = [4,3,2,1,0,-1,-2] 
  matariki = startdate + datetime.timedelta(days=convert[startdate.weekday()])
  print(matariki)
```

This gives correct dates except for 2028, 2033, 2036, 2039, 2041, 2047 so need further study.

**Comment by nickrout** [comment]
Yeah I suspect that there is not a python module for the Maori star calendar :)

**Comment by 36wish** [comment]
I could't even find a Gregorian-Maori calendar online so that might be a bit hard.

**Comment by dr-prodigy** [comment]
PR by @36wish is in beta! Closing this, thanks everyone! 👍
