### ISSUE TITLE
Natal Day, Nova Scotia, Canada

### ISSUE THREAD

**Issue by ric99001** [dr-prodigy/python-holidays#437]
I believe this one is missing.   Nova Scotia, Canada is observing the Civic Holiday on the 1st Monday in August, called Natal Day. I am not able to find what year it started to fall on the first Monday in August.  Natal Day is the official birthday of the province.

**Comment by dr-prodigy** [comment]
Hi,
I get back to this very old issue to clarify that national official holidays are currently the only scope for python-holidays, therefore Natal Day seems not suitable to be added.
Thx for your understanding, cheers!
