### ISSUE TITLE
"vervangingsdag" in Belgian holidays

### ISSUE THREAD

**Issue by leonoverweel** [dr-prodigy/python-holidays#444]
In Belgium there is a concept of a "vervangingsdag" (literally translated: "replacement day"); [from the Federal Public Service Employment, Labour and Social Dialogue](https://werk.belgie.be/nl/themas/feestdagen-en-verloven/feestdagen) (translated using Google Translate):

> **And if a public holiday coincides with a Sunday or a normal day of inactivity?**
> To guarantee the employee ten public holidays, the law states that if a public holiday coincides with a Sunday or an ordinary day of inactivity in the company, he must be replaced. This "replacement day" must be determined on an ordinary day of activity in the company. This replacement day becomes a public holiday for the employees employed in the company. The number of hours that would have been worked on the replacement day is of no importance.

From looking at the [Belgium source code](https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/belgium.py), I don't think this concept is currently supported in `holidays`.

Is this something that `holidays` wants to support? If so, I'd be happy to implement it and make a PR. If I'm welcome to do so, how would you want this to be designed? e.g., should it be always-on, behind an optional argument to the class that's on by default, the same but off by default, etc.?

**Comment by mayag-gett** [comment]
@leonoverweel Take a look at `observed` feature, I think it might be what you're looking for

**Comment by giladmaya** [comment]
@leonoverweel Take a look at observed feature, I think it might be what you're looking for

**Comment by dr-prodigy** [comment]
@leonoverweel I confirm, as stated by @giladmaya, that observed feature (ie: move holiday to next workday if it falls on Sunday) is what is currently being supported in holidays.
If this doesn't apply, any PR is, surely, always welcome!
Thx in advance, best
