### ISSUE TITLE
UK Prov needs adding

### ISSUE THREAD

**Issue by loversama** [dr-prodigy/python-holidays#447]
In the UK the holidays of England are not the same as Scotland for example so holidays are reading incorrectly for say England aas it is adding the holidays of everyone together.

**Comment by willthong** [comment]
Hi! If you look at the country table, it includes separate entries for 'England', 'Scotland', 'Wales' and 'Northern Ireland'. Use one of those as your "country" variable instead.

**Comment by loversama** [comment]
Thank you for the heads up, I must have missed the "England" listing expecting to see it as a region of the UK.

Cheers!
