### ISSUE TITLE
Observeed dates being duplicated

### ISSUE THREAD

**Issue by lispwarez** [dr-prodigy/python-holidays#449]
When trying to create a list of holidays for more than 1 year and the holiday falls on a sunday the Observed holiday duplicates itself to the monday and the tuesday but only for the first year

If I do for a single year there is no issue.

Example
`holiday_za = holidays.CountryHoliday("ZA", years=[2021])` returns the correct list of holidays
```
{
    "date": "2021-03-21",
    "holiday": "Human Rights Day"
  },
  {
    "date": "2021-03-22",
    "holiday": "Human Rights Day (Observed)"
  }
```
`holiday_za = holidays.CountryHoliday("ZA", years=[2021,2022])` will duplicate any public holiday falling on a sunday for year 2021
```
  {
    "date": "2021-03-21",
    "holiday": "Human Rights Day"
  },
  {
    "date": "2021-03-22",
    "holiday": "Human Rights Day (Observed)"
  },
  {
    "date": "2021-03-23",
    "holiday": "Human Rights Day (Observed)"
  ```

**Comment by dr-prodigy** [comment]
Fixed by mborsetti.. closing, thx!
