### ISSUE TITLE
country variable undefined

### ISSUE THREAD

**Issue by Z223I** [dr-prodigy/python-holidays#461]
holidays/holiday_base.py
`        country = getattr(self, "country", None) or getattr(
            other, "country", None
        )
`
The "country" variable should probably be changed to "self.country".

**Comment by dr-prodigy** [comment]
Hi @Z223I
I don't think this is the case: country is in fact a local variable set to be returned at the end of the function, ie:
```
        return HolidaySum(
            years=(self.years | other.years),
            expand=(self.expand or other.expand),
            observed=(self.observed or other.observed),
            country=country,
            prov=prov,
        )
```
Could you experience any issue? In that case, please provide some proof code.

Thx a lot, cheers!

**Comment by dr-prodigy** [comment]
Closing, thx
