### ISSUE TITLE
Movable holidays in ARG

### ISSUE THREAD

**Issue by celispahn** [dr-prodigy/python-holidays#465]
There are 4 holidays in Argentina that are **movable** or transferable, meaning they aren't always on the exact same date. They're now set as fixed dates and that's not accurate.

This ones are:
Día Pase a la Inmortalidad del General Martín Miguel de Güemes [Day Pass to the Immortality of General Martín Miguel de Güemes] --- **it's set to XXXX-06-17**
Día Pase a la Inmortalidad del General D. José de San Martin [Day Pass to the Immortality of General D. José de San Martin] --- it's set to XXXX-08-17
Día del Respeto a la Diversidad Cultural [Respect for Cultural Diversity Day] --- **it's set to XXXX-10-12**
Día Nacional de la Soberanía [National Sovereignty Day] --- **it's set to XXXX-11-23**

The dates of this holidays in the last few years are:
►Día Pase a la Inmortalidad del General Martín Miguel de Güemes [Day Pass to the Immortality of General Martín Miguel de Güemes]
(this holiday didn't exist before 2018)
2018-06-17
2019-06-17
2020-06-15
2021-06-21

►Día Pase a la Inmortalidad del General D. José de San Martin [Day Pass to the Immortality of General D. José de San Martin]
2015-08-17
2016-05-15
2017-08-21
2018-08-20
2019-08-17
2020-08-17
2021-08-16

►Día del Respeto a la Diversidad Cultural [Respect for Cultural Diversity Day]
2015-10-12
2016-10-10
2017-10-16
2018-10-15
2019-10-12
2020-10-12
2021-10-11
2022-10-12

►Día Nacional de la Soberanía [National Sovereignty Day]
2015-11-23
2016-11-28
2017-11-20
2018-11-19
2019-11-18
2020-11-23
2021-11-20
2022-11-23

**Comment by madphysicist** [comment]
Is there any rhyme or reason for those dates (can they be computed), or are they based on the whims of lawmakers?

**Comment by leandrorojas** [comment]
in AR there are bridge holidays, some move and sone don't depending on the government, there is no way to compute them as they change every year. the information source can be found on (in spanish): https://www.argentina.gob.ar/interior/feriados-nacionales-2022
additionally, google's public holidays' calendar has them right

**Comment by leandrorojas** [comment]
in AR there are bridge holidays, some move and sone don't depending on the government, there is no way to compute them as they change every year. the information source can be found on (in spanish): https://www.argentina.gob.ar/interior/feriados-nacionales-2022
additionally, google's public holidays' calendar has them right

**Comment by PPsyrius** [comment]
Here's the info on moveable holidays in Argentina ([listed as "citation needed" on Wikipedia](https://en.wikipedia.org/wiki/Public_holidays_in_Argentina), but should be usable for now):
> The "movable holidays" whose dates coincide with Tuesdays and Wednesdays will be moved to the previous Monday. Those that coincide with Thursday, Friday, Saturday and Sunday will be moved to the following Monday. Every employee is entitled to 15 paid public holidays, and every year; the government adds a few more holidays known as "bridge holidays", which means that a holiday lasts two days.

As per Thailand's case, `"Bridge Holidays"` can be declared in the `special_holidays = { ... }` section separately.

@leandrorojas Is there an Argentinian calendar online anywhere with data from previous years that we can cross-check with on the bridge holidays pre-2020? Otherwise we can probably begin with data for [2020](https://www.argentina.gob.ar/interior/feriados-nacionales-2020), [2021](https://www.argentina.gob.ar/interior/feriados-nacionales-2020), [2022](https://www.argentina.gob.ar/interior/feriados-nacionales-2022), [2023](https://www.argentina.gob.ar/interior/feriados-nacionales-2023)

**Comment by leandrorojas** [comment]
The rule wikipedia described is ok  and it is also the Law 🤣  ([Ley 27399](https://www.argentina.gob.ar/normativa/nacional/ley-27399-281835), also mentioned at the bottom of https://www.argentina.gob.ar/interior/feriados-nacionales-2023)
I did find previous' years data, some in text form other as screen captures, let me know if you need translation or assistance:

**2019**: both from official sites
--> https://www.argentina.gob.ar/noticias/feriados-2019-conoce-el-calendario-completo
--> https://www.cultura.gob.ar/feriados-2019-en-argentina_7326/
**2019**: from a local news paper
--> https://servicios.lanacion.com.ar/app-mobile/feriados/2019

**2018**: from a local news paper
--> https://servicios.lanacion.com.ar/app-mobile/feriados/2018

**2017**: from local news paper, you get the idea
--> https://servicios.lanacion.com.ar/app-mobile/feriados/2017

hope this helps
PS: the link on 2021 you posted points to 2020

**Comment by PPsyrius** [comment]
Thanks for the help, I'll try to get them implemented soon enough :)

**Comment by PPsyrius** [comment]
As a side note, it seems like the current Ley 27399 only moved to the next Monday for the ones that fall on Thur/Fri, not Sat/Sun as per the current logic stated on Wikipedia above. This results in myriads of errors when checking with the official calendar data, so I will open up the pull request soon once I've finished the current code revamps. @leandrorojas @KJhellico

**Comment by arkid15r** [comment]
Resolved in #988.
