### ISSUE TITLE
Spring bank holiday 2022 in the United Kingdom

### ISSUE THREAD

**Issue by AhmosSansom** [dr-prodigy/python-holidays#471]
Spring bank holiday in 2022 is the 2nd June 2022 similar to 2012:

Current version gives 30th May 2022 instead of 2nd June 2022

https://www.gov.uk/bank-holidays
https://www.timeanddate.com/calendar/?year=2022&country=9

https://github.com/AhmosSansom/python-holidays/tree/patch-2

**Comment by capitalinc** [comment]
This issue still persists as of today. Please fix.
![image](https://user-images.githubusercontent.com/48288493/124928490-ecf3fe80-dfff-11eb-8eed-618ed1d8785d.png)

**Comment by jaroos95** [comment]
![image](https://user-images.githubusercontent.com/65154649/133949999-8116644c-82cd-4e50-a5db-b5ee0773b66e.png)
Issue is still present as of 20/09. Please fix this!

**Comment by dr-prodigy** [comment]
Hi, fixed in #487 . Thx, cheers
