### ISSUE TITLE
Norway national holidays include all Sundays

### ISSUE THREAD

**Issue by JoLo90** [dr-prodigy/python-holidays#472]
When asking for the national holidays of Norway and Sweden, the returned dictionary also returns every Sunday at the beginning (Søndag here).

Here an example for Norway for 2020:
`dict_items([(datetime.date(2020, 1, 5), 'Søndag'), (datetime.date(2020, 1, 12), 'Søndag'), (datetime.date(2020, 1, 19), 'Søndag'), (datetime.date(2020, 1, 26), 'Søndag'), (datetime.date(2020, 2, 2), 'Søndag'), (datetime.date(2020, 2, 9), 'Søndag'), (datetime.date(2020, 2, 16), 'Søndag'), (datetime.date(2020, 2, 23), 'Søndag'), (datetime.date(2020, 3, 1), 'Søndag'), (datetime.date(2020, 3, 8), 'Søndag'), (datetime.date(2020, 3, 15), 'Søndag'), (datetime.date(2020, 3, 22), 'Søndag'), (datetime.date(2020, 3, 29), 'Søndag'), (datetime.date(2020, 4, 5), 'Søndag'), (datetime.date(2020, 4, 12), 'Første påskedag, Søndag'), (datetime.date(2020, 4, 19), 'Søndag'), (datetime.date(2020, 4, 26), 'Søndag'), (datetime.date(2020, 5, 3), 'Søndag'), (datetime.date(2020, 5, 10), 'Søndag'), (datetime.date(2020, 5, 17), 'Grunnlovsdag, Søndag'), (datetime.date(2020, 5, 24), 'Søndag'), (datetime.date(2020, 5, 31), 'Første pinsedag, Søndag'), (datetime.date(2020, 6, 7), 'Søndag'), (datetime.date(2020, 6, 14), 'Søndag'), (datetime.date(2020, 6, 21), 'Søndag'), (datetime.date(2020, 6, 28), 'Søndag'), (datetime.date(2020, 7, 5), 'Søndag'), (datetime.date(2020, 7, 12), 'Søndag'), (datetime.date(2020, 7, 19), 'Søndag'), (datetime.date(2020, 7, 26), 'Søndag'), (datetime.date(2020, 8, 2), 'Søndag'), (datetime.date(2020, 8, 9), 'Søndag'), (datetime.date(2020, 8, 16), 'Søndag'), (datetime.date(2020, 8, 23), 'Søndag'), (datetime.date(2020, 8, 30), 'Søndag'), (datetime.date(2020, 9, 6), 'Søndag'), (datetime.date(2020, 9, 13), 'Søndag'), (datetime.date(2020, 9, 20), 'Søndag'), (datetime.date(2020, 9, 27), 'Søndag'), (datetime.date(2020, 10, 4), 'Søndag'), (datetime.date(2020, 10, 11), 'Søndag'), (datetime.date(2020, 10, 18), 'Søndag'), (datetime.date(2020, 10, 25), 'Søndag'), (datetime.date(2020, 11, 1), 'Søndag'), (datetime.date(2020, 11, 8), 'Søndag'), (datetime.date(2020, 11, 15), 'Søndag'), (datetime.date(2020, 11, 22), 'Søndag'), (datetime.date(2020, 11, 29), 'Søndag'), (datetime.date(2020, 12, 6), 'Søndag'), (datetime.date(2020, 12, 13), 'Søndag'), (datetime.date(2020, 12, 20), 'Søndag'), (datetime.date(2020, 12, 27), 'Søndag'), (datetime.date(2020, 1, 1), 'Første nyttårsdag'), (datetime.date(2020, 5, 1), 'Arbeidernes dag'), (datetime.date(2020, 12, 25), 'Første juledag'), (datetime.date(2020, 12, 26), 'Andre juledag'), (datetime.date(2020, 4, 9), 'Skjærtorsdag'), (datetime.date(2020, 4, 10), 'Langfredag'), (datetime.date(2020, 4, 13), 'Andre påskedag'), (datetime.date(2020, 5, 21), 'Kristi himmelfartsdag'), (datetime.date(2020, 6, 1), 'Andre pinsedag')])`

**Comment by jusce17** [comment]
Hi @JoLo90 
Are you from Norway ? in the code I found that someone said that **Sundays are considered holidays in Norway**
<img width="490" alt="Screen Shot 2021-07-05 at 8 35 13 PM" src="https://user-images.githubusercontent.com/5844555/124512599-ad939b00-ddd0-11eb-910d-127edb2ae895.png">

Maybe this is the reason you are getting this ?

**Comment by JoLo90** [comment]
Hi @jusce17 
I am not from Norway but I was working on a project in Norway where I needed the national holidays.
You are right this is probably due to this, even though we rather aim for the **national** holidays with this library, isn't it?
I would have rather expected the following dates  [https://en.wikipedia.org/wiki/Public_holidays_in_Norway](url).

**Comment by jusce17** [comment]
Hi @JoLo90 

From what I can tell is that this library aim for **national** and **regional** holidays (For those countries with some holidays only in some states )
But I think the calendar for Norway is def off, I am gonna check it with some Norwegian friends and see if I can fix it

**Comment by jusce17** [comment]
He actually added some links on his code that might help us understand this 


```
class Norway(HolidayBase):
    """
    Norwegian holidays.
    Note that holidays falling on a sunday is "lost",
    it will not be moved to another day to make up for the collision.

    In Norway, ALL sundays are considered a holiday (https://snl.no/helligdag).
    Initialize this class with include_sundays=False
    to not include sundays as a holiday.

    Primary sources:
    https://lovdata.no/dokument/NL/lov/1947-04-26-1
    https://no.wikipedia.org/wiki/Helligdager_i_Norge
    https://www.timeanddate.no/merkedag/norge/
    """
```

Apparently every sunday is indeed a holiday, but it is a bit confused I will double check with someone else

**Comment by mborsetti** [comment]
> Hi @jusce17
> I am not from Norway but I was working on a project in Norway where I needed the national holidays.
> You are right this is probably due to this, even though we rather aim for the **national** holidays with this library, isn't it?
> I would have rather expected the following dates [https://en.wikipedia.org/wiki/Public_holidays_in_Norway](url).

I believe you're correct: no other country in this library includes weekly "holidays", even though in pretty much all countries a day per week (typically Sunday or Friday) is considered a form of "holiday".

P.S. https://no.wikipedia.org/wiki/Helligdager_i_Norge agrees with you

**Comment by dr-prodigy** [comment]
Hi and thank you both!
After a check, I updated Norway to match all other countries (ie: Sundays are not considered holidays) while retaining the possibility to enable this with the flag `include_sundays` (now defaulting to False).
Released on beta.
Cheers 👍
