### ISSUE TITLE
New Holiday In Chile

### ISSUE THREAD

**Issue by pabloromeroc** [dr-prodigy/python-holidays#473]
from June 19th 2021, in Chile we have a new holiday, Día Nacional de los Prueblos Indígenas (National Day of Native Peoples), the new holiday occurs every winter solstice in Chile from year 2022, for the year 2021, the holiday occurs June 21th.

References: 
Ley 21.357 - https://www.bcn.cl/leychile/navegar?idNorma=1161743&idParte=&idVersion=2021-06-19

**Comment by dr-prodigy** [comment]
Thank you! Released on beta.
Cheers
