### ISSUE TITLE
Juneteenth Holiday Needed

### ISSUE THREAD

**Issue by bhackett** [dr-prodigy/python-holidays#482]
I ran the latest version of holidays and see that there is no entry for Juneteenth, a new holiday starting in June 2021 in the United States.  Hopefully, you can add it soon.  Thanks

**Comment by jusce17** [comment]
Hello @bhackett  I have submitted the PR #488 it should be fixed soon

**Comment by dr-prodigy** [comment]
Merged in beta.. thx!

**Comment by bhackett** [comment]
Thank you.  It works great!

Brian
