### ISSUE TITLE
How can I print out the next holiday?

### ISSUE THREAD

**Issue by NoCodeAvaible** [dr-prodigy/python-holidays#483]
Hey guys and contributors,
is there any way to print out the next holiday?
For example, if there is no holiday today, the program prints the nearest holiday out.

Thank's for every help and suggestion in advance:)

**Comment by jusce17** [comment]
HI @NoCodeAvaible ,
I believe you can just iterate to your holidays, this messy code my give you a hint 

```
from datetime import date, timedelta
import holidays

brazlian_holidays = holidays.Brazil()
holiday = date.today() in brazlian_holidays
day = date.today()
while not holiday:
    day = day + timedelta(days=1)
    if day in brazlian_holidays:
        print(brazlian_holidays.get(day))
        break
```
 OUTPUT 
```bash
 Independência do Brasil
```

**Comment by NoCodeAvaible** [comment]
Hey @jusce17 ,
sorry for my late response thank you very very much for your help:)
Worked great for me:)
