### ISSUE TITLE
Brazilian national and state holidays

### ISSUE THREAD

**Issue by Skippern** [dr-prodigy/python-holidays#49]
Could it be possible to include Brazilian national (federal) and state holidays? I am working on an app where I need to calculate `odd workdays`, that is single weekdays squeezed between holidays, or holiday and weekend. What I need for now is the federal + the state of Espírito Santo.

**Comment by dr-prodigy** [comment]
Could you possibly implement it? Thank you very much, your help is much appreciated! ;)

**Comment by dr-prodigy** [comment]
Okay, I'd say "timeout expired" for this request :)
