### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'country'

### ISSUE THREAD

**Issue by NoCodeAvaible** [dr-prodigy/python-holidays#500]
Hey guy's,
I am trying to add a new holiday to the general german holiday list on my machine.
But when running my code I am getting the following error:
`TypeError: __init__() got an unexpected keyword argument 'country'`

This is the full error message:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    date(2021 ,8, 28) in CorporateHolidays(country="Germany")
  File "C:\Users\supre\anaconda3\lib\site-packages\holidays\countries\germany.py", line 81, in __init__
    HolidayBase.__init__(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'country'
```

This is my code:
```
from datetime import date
import holidays

class CorporateHolidays(holidays.Germany):
    def _populate(self, year):
        holidays.Germany._populate(self, year)
        self[date(year, 8, 28)] = "My birthday"
date(2021 ,8, 28) in CorporateHolidays(country="Germany")#also tried with DE or DEU
```

Am I doing something wrong?
If so I would be really glad if someone could help me out with this problem and tell me what I've made wrong.
Thank's for every help and suggestion in advance:)

**Comment by mborsetti** [comment]
The keyword country is defined in holidays by the `CountryHoliday` function and it's used to instantiate the class from the correct country; however you are subclassing `holidays.Germany` directly, and if you look at its `__init__` it does not take a country keyword as it would be pleonastic.

Just instantiate with `CorporateHolidays()` and that error will go away.

Also, shouldn't you be calling `self._populate(year)`?

Oh, I see that the documentation needs to be updated.  Any volunteers? Should ideally be moved over to readthedocs as well.

**Comment by NoCodeAvaible** [comment]
Hey @mborsetti,
thank's for your fast response:)
This worked out great for me:)

**Comment by dr-prodigy** [comment]
Thank you both.. closing!
