### ISSUE TITLE
Juneteenth Holiday Observed date

### ISSUE THREAD

**Issue by empgc02** [dr-prodigy/python-holidays#503]
I noticed that there is no logic for the Juneteenth (Observed) date (i.e. June 20, 2022) and believe this needs to be updated

**Comment by karin-jsq** [comment]
It looks like Juneteenth logic

https://github.com/dr-prodigy/python-holidays/blob/1a407bd970ded0966f8f9457e4e49563681dd2c7/holidays/countries/united_states.py#L382-L386

needs to be updated with `observed` logic, like West Virginia Day

https://github.com/dr-prodigy/python-holidays/blob/1a407bd970ded0966f8f9457e4e49563681dd2c7/holidays/countries/united_states.py#L390-L398

**Comment by one10** [comment]
yes, according to this: https://www.federalreserve.gov/aboutthefed/k8.htm - 2021/06/18 and 2022/06/20 were the respective official holidays in '21 and '22, so the default python-holidays values seem incorrect.

**Comment by dr-prodigy** [comment]
@empgc02 this has been fixed by @khawley and then merged in beta.. thank you both! 👍 
Cheers
dr-p
