### ISSUE TITLE
Duplicate Angola holiday

### ISSUE THREAD

**Issue by pietervdw115** [dr-prodigy/python-holidays#505]
It seems that there is a duplicate holiday being added in the Angola public holidays.

@jusce17 I see you have made these changes and that you are from Angola. 

What is the difference between `Dia do Herói Nacional` and `Dia dos Heroes Nacional` and why do both of them fall on the same day from 1979. 

Should this have been a name change? Or was it accidentally added?

**Comment by jusce17** [comment]
Hi  @pietervdw115 
thanks for the heads up, I should be fixing this soon

**Comment by pietervdw115** [comment]
Thank you @jusce17 ! :)

**Comment by dr-prodigy** [comment]
Thank you both! 👍
