### ISSUE TITLE
Bulgarian holidays not alll

### ISSUE THREAD

**Issue by Martin0404** [dr-prodigy/python-holidays#507]
I suggest changing the source of information for holidays in Bulgaria to [https://kik-info.com/spravochnik/calendar/2021/](url). This is the most legitimate source from where the business community is finding out the dates that they need. The sources which the module is using right now are not comprehensive (for example: 2021-05-03 for 2021 is missing). Hope you fix it...

**Comment by dr-prodigy** [comment]
Fixed in #509 . Thank you very much!
