### ISSUE TITLE
08/16/2021 Is not a holiday in Spain

### ISSUE THREAD

**Issue by Danieldiazi** [dr-prodigy/python-holidays#511]
08/16/2021 is not holiday in spain! It's holidays in some provinces:

Castilla y León, Aragón, Asturias, Andalucía y Canarias.

It's not a holiday at: 

Galicia, Cantabria, La Rioja, Madrid, Extremadura, País Vasco, Navarra, Cataluña, Comunidad Valenciana, Baleares, Castilla-La Mancha, Murcia, Ceuta and Melilla.

**Comment by dr-prodigy** [comment]
Hi,
there is no direct reference to 18th Aug in Spanish holidays.
Would you please double check?
Pls let me know, thx!
