### ISSUE TITLE
"AttributeError: module 'holidays' has no attribute SA"

### ISSUE THREAD

**Issue by KathyGCY** [dr-prodigy/python-holidays#518]
Dear Developer,
How are you today?

I'm writing to report and issue when pulling holidays in SA (SAU)

According to "Available Countries" table SaudiArabia is country that we have available.
However, when run the code, it returned error:
`AttributeError: module 'holidays' has no attribute SA`
<img width="690" alt="Screen Shot 2021-09-09 at 4 34 14 PM" src="https://user-images.githubusercontent.com/14912791/132759006-b2345a6c-e880-4533-9a6c-18b50796b4b1.png">
I was wondering what could be the cause?
Thank you and have a wonderful afternoon!
All the best,
Kathy

**Comment by mborsetti** [comment]
Kathy, are you running the latest version of holidays?
```
>>> import holidays
>>> holidays.__version__
0.11.2
```

**Comment by KathyGCY** [comment]
Thank you @mborsetti ! It worked after updating it to the latest version!
All the best,
Kathy
