### ISSUE TITLE
Documentation/API typo

### ISSUE THREAD

**Issue by JustinKurland** [dr-prodigy/python-holidays#520]
Currently the ISO abbreviation for Bangladesh is written as 'BDG' but it is actually 'BGD'. Really minor thing, but easy enough to tweak in the documentation.

**Comment by JustinKurland** [comment]
Documentation for France needs to indicate if there are either provinces or states. It currently does not indicate if to access these local holidays you need one or the other.

**Comment by JustinKurland** [comment]
Portugal Extension, PRTE does not work as abbreviation.

**Comment by dr-prodigy** [comment]
Hi, thank you for your support! All fixes are released on beta branch. Thx again
