### ISSUE TITLE
Documentation in Sphynx

### ISSUE THREAD

**Issue by mborsetti** [dr-prodigy/python-holidays#526]
@dr-prodigy Would you accept a reorganization of the documentation into [Sphynx](https://www.sphinx-doc.org/en/master/) format, suggesting that it be hosted (for free) at https://readthedocs.org/ -- you'd have to set up an account for it?

You know, for sometime between now and 2030... ;)

**Comment by mborsetti** [comment]
@dr-prodigy any comments on the above?

**Comment by dr-prodigy** [comment]
Hey there Mike @mborsetti!
As you could (maybe) see, in these days I'm (slowly) trying to finally catch up with the open PRs/issues (quite a lot piled up in fact..).

Being yours often the most challenging (and clever!) ones, I usually leave them for last :)
But I will come back to this one (and the other one regarding date slices too) soon! 
Cheers
M.

**Comment by dr-prodigy** [comment]
At last, @mborsetti ! Sorry for getting to this so late, didn't have time to really get into it until the last days.

After some reading / learning  the topic, I agree: it's a very nice improvement.
As suggested, I've then opened an account on readthedocs.org , and created a linked project for python-holidays.
Then added sphinx dev dependency, and create the default stub project.
As a final "touch", I've added the relevant badge at the beginning of README.rst page.

All currently available on beta branch: you should be able to start your work from there (of course, no hurry.. take your time! :-) ).

Grazie 👍

**Comment by mborsetti** [comment]
Wonderful!  

It may have to wait until the new year, but will submit a PR when I have it built.

**Comment by mborsetti** [comment]
@dr-prodigy Submitted in #601
