### ISSUE TITLE
Wrong Observed Holiday for Korean National Foundation Day

### ISSUE THREAD

**Issue by AntonioVentilii** [dr-prodigy/python-holidays#531]
Hello, it seems there is no adaptation for Observed Holiday for the Korean National Fundation. For example on the year 2021 it falls on a Sunday and should be observed on the following Monday, but it is not showed. 
May you please check?

**Comment by 0xF4D3C0D3** [comment]
I have the same issue. so I issued this PR https://github.com/dr-prodigy/python-holidays/pull/535

**Comment by dr-prodigy** [comment]
PR is now merged in beta. Thx to both of you, cheers!
