### ISSUE TITLE
Please add holidays from Prophet

### ISSUE THREAD

**Issue by ourownstory** [dr-prodigy/python-holidays#538]
Thank you for this great library. We at NeuralProphet would like to be able to rely 100% on your great package.
However, you are lacking a few important countries, which we have to manually sync from Prophet.
If you could add those, it would make NeuralProphet's and Prophet's codebase simpler to maintain.

Prophet supports the following countries missing in your library:
* Indonesia
* Thailand
* Philippines
* Pakistan
* Belarus
* India (currently defined: 8 holidays,  [while Prophet has 22](https://github.com/facebook/prophet/pull/2044#issuecomment-1086869935))

You can find the relevant code here:
https://github.com/facebook/prophet/blob/master/python/prophet/hdays.py

"All that is needed" is to write tests for these countries, the holidays are all already defined.

If someone would be down to take on this task, we would be very thankful!

**Comment by dr-prodigy** [comment]
Hi @ourownstory thank you for your interest in python_holidays.

It would be great if you could contribute to it, if you can, thx!

In the meanwhile, I mark this as "help wanted".

Cheers!

**Comment by ourownstory** [comment]
Hi @dr-prodigy I am happy to contribute everything but the tests...

**Comment by tserekh** [comment]
I can work on it

**Comment by ourownstory** [comment]
Thank you @tserekh ! Please let me know when your work is merged!
