### ISSUE TITLE
Provincial holidays are not being Reported in case of India

### ISSUE THREAD

**Issue by sheminasalam** [dr-prodigy/python-holidays#539]
I use this to know the status of stock exchanges in India. The stock exchange that I follow is the province with code MH where 15th of October is a holiday declared by state government. But it seems this is not recognized by this program. You can get the official list of holidays from this 
https://mmrda.maharashtra.gov.in/public-holidays

**Comment by Rishabh04-02** [comment]
@dr-prodigy I would like to submit a patch to fix this.

**Comment by sheminasalam** [comment]
Did you submit the patch?

**Comment by Rishabh04-02** [comment]
NO, not yet. I was waiting for the approval.

**Comment by sheminasalam** [comment]
Will it help with all state holidays or  with maharastra or stock exchange holidays?

**Comment by Rishabh04-02** [comment]
well, ideally there should be all state holidays.

**Comment by dr-prodigy** [comment]
Hi, just fixed and released in beta: thx!
