### ISSUE TITLE
Please enter holidays for Macedonia

### ISSUE THREAD

**Issue by mojso** [dr-prodigy/python-holidays#541]
Please enter holidays for Macedonia (North Macedonia)

https://en.m.wikipedia.org/wiki/Public_holidays_in_North_Macedonia

**Comment by dr-prodigy** [comment]
Hi @mojso,
thank for your interest in python-holidays.. any contribution is welcome!
Pls refer to here:
https://github.com/dr-prodigy/python-holidays#contributions
for more info.

Cheers

**Comment by mojso** [comment]
Thank you for entering the Macedonian holidays

**Comment by dr-prodigy** [comment]
Big kudos to @tserekh for providing this: it is now available on beta branch.
Cheers
