### ISSUE TITLE
October 25 is no longer holiday in Spain Prov=PV

### ISSUE THREAD

**Issue by cyberdie** [dr-prodigy/python-holidays#544]
I'm using the WORKDAY integration of Home Assistant to obtain a binary sensor for workdays.
AFAIK python-holidays is being used "under the hood" in this integration
Yesterday October 25th was wrongly marked as holiday.
It's not holiday since 2014.

More info (sorry, in spanish): [https://es.wikipedia.org/wiki/D%C3%ADa_del_Pa%C3%ADs_Vasco#Creaci%C3%B3n_y_desaparici%C3%B3n_de_la_festividad]

**Comment by dr-prodigy** [comment]
Released in beta.. thx! 👍
