### ISSUE TITLE
Changing `province` to `state` for India

### ISSUE THREAD

**Issue by canute24** [dr-prodigy/python-holidays#548]
Wassup doc, xD

In India `province` is called a `state`. I was wondering if you are open to making this change and what the deprecation process is like.

**Comment by dr-prodigy** [comment]
Hey there @canute24 ! :)
thank you for your interest and suggestion! 👍 

Generally speaking, I don't feel this as a major improvement, although it definitely would make sense to apply it.
On the other hand, being a breaking change, if willing to implement it, it should be implemented in more than one steps to avoid issues on projects depending on python-holidays.

India is also one of the less test-covered countries, and therefore would require a quite deep tests review.

A good plan could be:

1) implement a first PR supporting both `prov` and `state`. In case `prov` is used, fire a deprecation warning and continue
2) merge to beta -> release a new lib version
3) remove `prov` support. In case `prov` is used, fire a "deprecated" error and ignore the province value
4) merge to beta -> release a new lib version

While implementing those changes, test coverage (currently scoring a poor 58%) should ideally be improved too.

Pls let me know if you're interested to work on this, I will do my best to support you.

Thx, cheers!
dr-p

**Comment by dr-prodigy** [comment]
Hi @canute24 
I've recently pushed a similar update (class initialization review => upgrade with retro-compatibility + deprecation warning, relevant tests) to United Kingdom: it's currently released on beta branch.
Relevant commit here:
https://github.com/dr-prodigy/python-holidays/commit/fcdfda92bb059f92a8de56ddcf4c84fe89f0c80c

You could get ideas / code snippets from there, if you wish to implement your change on India respecting what suggested above.

KUTGW, thx!
dr-p

**Comment by dr-prodigy** [comment]
This is now implemented / available on beta through the deprecation of `prov` and `state`, both replaced by `subdiv`.
Thx, cheers!
