### ISSUE TITLE
US Viriginia Lee Jackson Day Removed After 2020

### ISSUE THREAD

**Issue by evohnave** [dr-prodigy/python-holidays#559]
Jan 15th was removed as a state holiday by Virginia after 2020.

See Virginia Legislative Information System [here](https://lis.virginia.gov/cgi-bin/legp604.exe?201+sum+SB601)

All Lee Jackson Jan 15th holidays for 2021 and on should be removed.

**Comment by evohnave** [comment]
Seems like I don't have permissions to push...

holidays/countries/united_states.py lines 135, 138, 140 add in
  2020 >= year...
for all of the year checks.  This will fix this issue.

**Comment by dr-prodigy** [comment]
Hi @evohnave
thank you!
In fact, direct pushes are not allowed: you need to create a PR to collaborate.

Being a very limited and clear change, I provided the fix myself: now pushed in beta.

Thx, cheers!
