### ISSUE TITLE
Identify Spanish Province

### ISSUE THREAD

**Issue by ldsmovil** [dr-prodigy/python-holidays#561]
Hi, trying this, im in doubt about REGION DE MURCIA code.

**Comment by dr-prodigy** [comment]
Hi @ldsmovil ,
thank you for your interest in python-holidays.

In case you noticed any issue / improvable features, you are encouraged to provide a fix: we will appreciate your contribution! For further info, pls refer to:
https://github.com/dr-prodigy/python-holidays#contributions

Thx in advance, best!
dr-p

**Comment by javicalle** [comment]
Country codes used are from the ISO 3166 standard:
* https://www.iso.org/obp/ui/#iso:code:3166:ES

Spain holidays, are defined by 'comunidad autónoma', so the codes for 'región de Murcia', must be:
* holidays.Spain(prov='MC')


* https://www.boe.es/boe/dias/2021/10/21/pdfs/BOE-A-2021-17113.pdf

**Comment by ldsmovil** [comment]
> Country codes used are from the ISO 3166 standard:
> 
> * https://www.iso.org/obp/ui/#iso:code:3166:ES
> 
> Spain holidays, are defined by 'comunidad autónoma', so the codes for 'región de Murcia', must be:
> 
> * holidays.Spain(prov='MC')
> * https://www.boe.es/boe/dias/2021/10/21/pdfs/BOE-A-2021-17113.pdf

Thanks!! Perfect answer.
