### ISSUE TITLE
Add 'National Day for Truth and Reconciliation' holiday for Canada

### ISSUE THREAD

**Issue by bverkron** [dr-prodigy/python-holidays#562]
In 2021 a new holiday called 'National Day for Truth and Reconciliation' was added in Canada on Sept 30th of each year.
https://www.canada.ca/en/canadian-heritage/campaigns/national-day-truth-reconciliation.html

I don't see this accounted for, unless I missed it.

Edit: I would gladly add this and submit a PR as it's probably an easy change but I am painfully short on time these days. Just putting it out there in case someone that is already setup for development on this project has time to add it in. Love this project, thanks to all who maintain and contribute!

**Comment by dr-prodigy** [comment]
Hi @bverkron 
thank you!
This new holiday has been recently added (for MB and NS provinces only) by @cturra with #533 PR.
That PR has then been merged in beta and it will be released to master as soon as we release a new official python-holidays version (ETA still TBD).
I assume this covers your topic: I kindly ask you to please follow up here in case something else is still to be considered.. thx a lot!

**Comment by bverkron** [comment]
Thanks for the response and pointing out the PR, I did not think to search for PRs on this topic.

Some added info / context for others who might come across this...

My original understanding was that this was a nation wide statutory holiday but it does indeed appear to be province specific. In BC my children did not have school that day and my employer treated it as a stat holiday due to the industry I'm in but it appears to not be the case for everyone. Definitely not clear-cut in all cases, at least in BC.

BC: 
> The national holiday will be observed this Sept. 30 by federal employees and workers in federally regulated workplaces. We have advised provincial public-sector employers to honour this day and in recognition of the obligations in the vast majority of collective agreements. Many public services will remain open but may be operating at reduced levels. However, most schools, post-secondary institutions, some health sector workplaces, and Crown corporations will be closed.

https://news.gov.bc.ca/releases/2021FIN0048-001531

This makes it a little more clear unless you're in one of the above mentioned sectors / institutions, etc that treats it as a statutory holiday. lol
> Easter Sunday, Easter Monday, National Day for Truth and Reconciliation and Boxing Day **are not** statutory holidays in B.C.

https://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/statutory-holidays

**Comment by dr-prodigy** [comment]
@bverkron 
Oh gawrsh.. I must admit that this (interesting!) explanation doesn't clarify the topic too much to me ":-D

So in the end, given that BC seems not to be included in the list of provinces in which this holiday is, are MB and NS the only ones to be considered (at least, as of now)?

.. Thank you!

**Comment by bverkron** [comment]
I only spot checked BC, AB, SK and none of them have it as an official statutory holiday. However, [this article](https://dailyhive.com/vancouver/who-gets-september-30-truth-reconciliation-off-work) claims that PEI (Prince Edward Island) ...

> ... is recognizing Truth and Reconciliation as a holiday and closing schools and government office

and points to [this official statement](https://www.princeedwardisland.ca/en/news/province-recognizes-national-day-of-truth-and-reconciliation) which says...

> This Fall, Premier King will be introducing an amendment to the Employment Standards Act to officially recognize September 30 as a provincial statutory holiday for all Islanders 

but earlier in the statement also says...

> Provincial government offices, schools in the Public Schools Branch and la Commission scolaire de langue française will be closed for the day. Some Island businesses and organizations may decide to also observe the National Day of Truth and Reconciliation.

For comparison the official statement for NS states:

> Provincial government offices, public schools and regulated child care will be closed. Businesses will have the choice, as they do on other occasions, to remain open.

which is not unlike PEI and even BC to an extend.

This really makes me question what the criteria for a "holiday" is from a python-holidays perspective or even my own province / country's perspective 😅. Then there are further nuances between a holiday and statutory holiday? Yikes.

In all seriousness it seems like NS's and PEI's criteria for a statutory holiday are that government offices and schools are closed, but even though BC is following those same (or similar) actions it's not considered a statutory holiday. Also at a federal level it's listed as a statutory holiday but each individual province is able to treat it how they want. Clear as mud!

Maybe the best thing to do is fall back on python-holiday's official definition of a holiday? Not sure if that will help clear it up or make things more confusing. 🤔

**Comment by cturra** [comment]
> Maybe we only treat it as a holiday if the province deems it a **_statutory_** holiday regardless if each provinces definition of a statutory holiday is the same or not?

that was the approach i took when i implemented this holiday. figured i could circle back and add province’s or territories once they officially recognized the day as statutory. 

i’m open to changing that approach if the community feels it’s more appropriate. 🤷🏼

**Comment by dr-prodigy** [comment]
It is really not easy to say.. different countries, different rules!

In general, yes, only "statutory" holidays (as a rule of thumb, I'd put in this category all off (and usually paid) days for public & private workers, + schools) should be included as holidays in the lib.
Not being an expert of Canadian regulations / habits, I let you be judge for this case.. as soon as we have a clear answer, it'll be easy to implement it! :-)

Thank you and cheers everyone!

**Comment by bverkron** [comment]
After reviewing the official statements for the few provinces noted above and discussing / thinking about it I believe @cturra's approach is correct and probably the best criteria at this time.

There is so much nuance and variation in how the provinces are handling this holiday (and some others) that it's probably the only sane way to do it without getting into the weeds and causing a bunch of decision overhead and potential confusion.

One of the root issues that makes this a challenge for my use case is that I'm attempting to use `python-holidays` to determine which days my children have off school for some home automations (via Home Assistant). Sometimes, like in the case of National Day for Truth and Reconciliation, they (and I because I'm in the public sector) get the day off even though it isn't a statutory holiday. It would almost be nice to have a feature of `python-holidays` that would track holidays that apply to specific sectors / institutions like public, private, education, etc. Maybe an extra parameter even more granular than is specific to each province / state that would accept which sector / institution you want the holidays for. 🤔 That's very much another conversation though!

I will close this off. Thanks for the pleasant conversation around the topic!
