### ISSUE TITLE
Request: Method to get available countries and states

### ISSUE THREAD

**Issue by jahirfiquitiva** [dr-prodigy/python-holidays#563]
Hi

Would you mind adding a method to get the available countries, their ISO code and states for that country? 

I'm planning to use this dynamically instead of limiting it to a single country, so that would help a lot!

Thanks in advance

**Comment by madphysicist** [comment]
It seems that you are not the only one: https://stackoverflow.com/q/70237552/2988730

You can get what you want with something like this:

```
for cname in holidays.list_supported_countries():
    country = getattr(holidays, cname)()
    if cname != country.country:
        continue
    # Do stuff with country object
    if hasattr(country, 'PROVINCES'):
        # Do stuff with provinces
    if hasattr(country, 'STATES'):
        # Do stuff with states
```

**Comment by dr-prodigy** [comment]
Yes, this is being discussed in #575 .. please follow up there!
Thx cheers
