### ISSUE TITLE
Wrong ISO code for Venezuela

### ISSUE THREAD

**Issue by Skatox** [dr-prodigy/python-holidays#567]
Hello, nice work!

A friend's website uses this and I noticed that Venezuela is using YV code wich is used only for airplanes and telecomunications, the ISO should be VE.

You can see it here: https://laendercode.net/en/country/ve

**Comment by dr-prodigy** [comment]
Hi @Skatox , 
thank you!
Very easy fix, so I did it already.. it's released on beta branch.
Cheers! 👍

**Comment by Skatox** [comment]
Thank you!!
