### ISSUE TITLE
Observed Holidays for Canada is incorrect

### ISSUE THREAD

**Issue by Snitzel88** [dr-prodigy/python-holidays#583]
Hi,

Just noticed that the observed holidays logic for Canada is incorrect, for example the Christmas, boxing days, and new year days which falls on the weekend should have the following Monday (and Tuesday respectively) as the observed holidays not the previous day.

Ex:
Christmas = 25th - Saturday >Monday
Boxing day = 26th - Sunday>Tuesday
New year day = 31 = Saturday> Monday

**Comment by Undearius** [comment]
There's a pull request open to correct this for Christmas Day. It should probably be expanded to include New Year's Day

https://github.com/dr-prodigy/python-holidays/pull/579

**Comment by danielbrunt57** [comment]
Yes, I just noticed this also and it's showing Sat January 1 2022 as the holiday but there should be Observed on Monday Jan 3 2022...

**Comment by dr-prodigy** [comment]
Fixed with #678 .. closing, thx!
