### ISSUE TITLE
Missing holiday "Friedensfest" for Augsburg, Germany

### ISSUE THREAD

**Issue by nettnikl** [dr-prodigy/python-holidays#584]
Hey, i'd like to mention that there is a holiday missing.
On xxxx-08-08 the "Friedensfest" is celebrated in the city of Augsburg, Bavaria, Germany. It is celebrated exclusively there, otherwise, the holidays are equivalent to the Bavarian ones. However, it is a valid public holiday.
Could you add it, or in case it's to much of a hassle, add it as a note for Germany to the documentation?
EDIT: I'm aware of the note in the source code, it's just not very visible there.

**Comment by dr-prodigy** [comment]
Hi, 
thank you for your interest and support!
As you could notice in the code, that case was in fact evaluated and left willingly unmanaged, being that holiday not valid for whole Bavaria.
Also, unfortunately, there is currently no suitable space in the project doc (which is very concise and doesn't provide country specific details).

Note: @mborsetti promised to be soon working on some Sphynx documentation for the library. Depending on the depth we wish to reach, it could possibly be the right place to put this information. Mike please let us know your comments on the topic, if you wish, thx!

Thanks again, best

**Comment by nettnikl** [comment]
> evaluated and left willingly unmanaged

Closing then.

Would still welcome everyones input!
