### ISSUE TITLE
country BR, state SC - incorrect holiday

### ISSUE THREAD

**Issue by rpvelloso** [dr-prodigy/python-holidays#592]
https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/brazil.py#L202

there is a law (from 2017) that moves 11th aug to the next sunday whenever it falls in a work day.
https://www.sc.gov.br/noticias/temas/institucional/data-magna-de-santa-catarina-sera-comemorada-no-proximo-domingo

"O adiamento do feriado está previsto na Lei nº 17.335, de 30 de novembro de 2017, que prevê a transferência, sempre que o dia 11 de agosto e o dia 25 de novembro coincidirem com dias úteis da semana, dos feriados e os eventos alusivos às datas, para o domingo subsequente."

http://leis.alesc.sc.gov.br/html/2017/17335_2017_lei.html

"Dia do Estado de Santa Catarina

Sempre que o dia 11 de agosto coincidir com dia útil da semana, o feriado e os eventos alusivos à data serão transferidos para o domingo subsequente.

A semana em que recair o dia 11 de agosto constituirá período de celebrações cívicas em todo Território catarinense, sob denominação de Semana de Santa Catarina."

**Comment by Nalguedo** [comment]
My opinion on this is that since 2018, this is not an holiday anymore.

I may suggest 2 solutions:
1 - Remove the holiday from 2017 onwards
2 - Include the logic to move the date to Sunday whenever it falls in a workday.

I can take this one @dr-prodigy ... what's your thoughts about this?

**Comment by dr-prodigy** [comment]
Hi @Nalguedo thank you for notes.
I agree with you on both solutions.. holidays explicitly set in the weekend are not very impacting, being them days off by themselves, but in this case it's definitely correct to track it like so.. Pls go on thx a lot! 👍

**Comment by Nalguedo** [comment]
@dr-prodigy ... you can close this issue [ https://github.com/dr-prodigy/python-holidays/pull/761 ]

**Comment by dr-prodigy** [comment]
Thank you very much @Nalguedo @rpvelloso ! 👍
