### ISSUE TITLE
US - Juneteenth National Independence Day (Observed): name bug

### ISSUE THREAD

**Issue by apicht** [dr-prodigy/python-holidays#594]
This line is declaring the `name` variable:
https://github.com/dr-prodigy/python-holidays/blob/57dd2ed2b8659c76f776f10207456e5231c82099/holidays/countries/united_states.py#L326

This then gets picked up here, the cruel irony of which is not lost on me:
https://github.com/dr-prodigy/python-holidays/blob/57dd2ed2b8659c76f776f10207456e5231c82099/holidays/countries/united_states.py#L369-L380

In practice:
```
>>> us_holidays.get('June 20, 2022')
'Confederate Memorial Day (Observed)'
```

I will open a PR shortly to fix this.

**Comment by dr-prodigy** [comment]
This is now fixed in beta.
Thx, cheers!
