### ISSUE TITLE
US - Confederate Memorial Day is NOT a national holiday

### ISSUE THREAD

**Issue by DManowitz-VA** [dr-prodigy/python-holidays#598]
I noticed when looking at US holidays for 2021 and later that you have Confederate Memorial Day as a holiday.  This is NOT an official national holiday, and many people would consider including it in the list of US holidays as very inflamatory!  It is only observed in some states, and even then, only as a day off in fewer states (see for example https://www.timeanddate.com/holidays/us/confederate-memorial-day or https://www.forbes.com/sites/nicholasreimann/2021/04/26/state-offices-close-for-confederate-memorial-day-in-alabama-and-mississippi-heres-why-its-still-an-official-holiday-there/).

**Comment by apicht** [comment]
I believe this is related to #594 which I have opened a PR for: https://github.com/dr-prodigy/python-holidays/pull/595

**Comment by dr-prodigy** [comment]
Thank you both @DManowitz-VA @apicht , I will follow up on this on #595
Cheers everyone! 👍
