### ISSUE TITLE
Verbose name for `province`

### ISSUE THREAD

**Issue by guettli** [dr-prodigy/python-holidays#611]
It would be great if the library would provide a verbose name for the province.

Some abbreviations are not 100% clear.

BYP in Germany for example. If found it by searching, but an API would be nice.

**Comment by dr-prodigy** [comment]
Hi @guettli, thank you for your suggestion.
I've been just releasing in beta a major change while working on the new `subdiv` parameter.
In particular, the `list_supported_countries` method, along with the country names, is now returning all relevant available subdivisions (new naming for both states and provinces), so your requirement seems almost satisfied.

Therefore I label it as low priority: please let me know your point of view if you wish.

Thanks again, cheers!

**Comment by dr-prodigy** [comment]
@guettli I assume what above covers the request: thank you, closing this then!
Cheers
