### ISSUE TITLE
Holiday name traduction in other language - Suggestion

### ISSUE THREAD

**Issue by gobol007** [dr-prodigy/python-holidays#613]
Would it be possible to be able to translate the holidays into another language? example in French?

**Comment by arkid15r** [comment]
[This PR](https://github.com/dr-prodigy/python-holidays/pull/827) adds required functionality. After it's merged the holiday names will be translatable into other languages (the most of translations still need to be done).

**Comment by PPsyrius** [comment]
@dr-prodigy This issue can probably be closed now that v0.20 is released.

**Comment by arkid15r** [comment]
The v0.20 has been released and includes basic l10n support. Any localization PRs would be highly appreciated!
