### ISSUE TITLE
Province holiday in Italy

### ISSUE THREAD

**Issue by energywave** [dr-prodigy/python-holidays#614]
I see in code that there are "santo patrono" holidays for provinces (what's called in code "Provinces holidays"). But why? The "Santo patrono" is different from city to city, every municipality has its own special holiday. There isn't province holiday here.
I think there is no mean to keep provinces in Italy... Furthermore they're even partial as my province (VA) is not event present.
To manage the single municipality is a madness (or maybe finding some webservice that has that data freely available through a rest call... :) )

**Comment by dr-prodigy** [comment]
Hi @energywave, 
thx for your message, but I'm sorry I don't really catch its main goal (usually features are requested for add, rather than removal :) ).. to clarify :
1) AFAIK, a lot of small municipalities and companies align their holidays to their province's ones, so the feature is beneficial for those too
2) if that's not your case, you can always avoid setting the subdivision parameter, and you won't receive any local holiday 
3) by design, python holidays doesn't rely on webservices to work
Finally, if Varese's absence is your main concern, I'm sorry it went unnoticed until now.. But then you could then submit your first PR.. :)
Thx, cheers

**Comment by energywave** [comment]
Thank you for your reply, @dr-prodigy . I'll reply by quoting:

> usually features are requested for add, rather than removal :)

ahah, yes, you're right, I understand that sounds a bit strange. I was only thinking that a user could specify province thinking to have a more accurate result but, in fact, he will add a holiday that most probably is wrong for him.

> 1. AFAIK, a lot of small municipalities and companies align their holidays to their province's ones, so the feature is beneficial for those too

I don't know of such a situation of municipalities near where I live (Busto Arsizio, VA). I've seen you're italian too and near not far from me. For what I know every municipality has his own special holiday while the province holiday (Varese) is not an holiday, actually, for us that don't live in the province city.
While it's true that some organizations use "Sant'Ambrogio" as special holiday for the province of Milan (I think you was referring to that) I don't know of such cases outside the Milan province.
In fact event [Wikiepdia](https://it.wikipedia.org/wiki/Festa_del_santo_patrono) states that:
`Il giorno festivo varia da comune a comune, in base al santo celebrato.`

> 2. if that's not your case, you can always avoid setting the subdivision parameter, and you won't receive any local holiday

Yes, you're right. But that could be misleading to specify a province and receive a wrong holiday. Maybe it's better to just not provide it.

> 3. by design, python holidays doesn't rely on webservices to work

Ok, I see.

> Finally, if Varese's absence is your main concern, I'm sorry it went unnoticed until now.. But then you could then submit your first PR.. :) Thx, cheers

Yeah, I've discovered your library coming from Home Assistant by configuring workdays. while configuring I noted the province and I was wondering why to provide it, so I've read the code here to understand. I wanted to point that out to you, thinking that maybe you were not italian and was thinking that province special holiday was important.
The library is your and you decide. As you just closed the issue I think you already made the decision to keep provinces.
If you confirm that, yes, I'll make a PR by putting all the missing provinces in the list.

Thank you for your attention.

**Comment by mborsetti** [comment]
I think the problem can be fixed through documentation, as the subdivision for which the "Festa del santo patrono" holiday is calculated is the "capoluogo di provincia", not the entire provincia.

That should be an easy fix.

> I'll make a PR by putting all the missing provinces in the list.

That would be nice. We currently have ~40 provincial subdivisions out of the "80 provinces, 2 autonomous provinces, 4 decentralized regional entities, 6 free municipal consortia and 14 metropolitan cities" that [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:IT#Provinces) specifies, so we're missing quite a lot.

**Comment by energywave** [comment]
> I think the problem can be fixed through documentation, as the subdivision for which the "Festa del santo patrono" holiday is calculated is the "capoluogo di provincia", not the entire provincia.

At this point I agree. We should only specify it in the README.rst. I already added all the provinces there so maybe I can add a statement about that, then @dr-prodigy will review that if it's ok when merging my PR.

> That would be nice. We currently have ~40 provincial subdivisions out of the "80 provinces, 2 autonomous provinces, 4 decentralized regional entities, 6 free municipal consortia and 14 metropolitan cities" that [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:IT#Provinces) specifies, so we're missing quite a lot.

I already implemented all such provinces, even those with the "Santo patrono" of Sud Sardegna that is the Thursday after second Sunday in May... :D
Now I'm adding tests for those new provinces and when done I'll make the PR in the beta branch.

**Comment by dr-prodigy** [comment]
I've released in beta #617 so this seems done as well.
Thanks for your support @energywave @mborsetti , cheers!
