### ISSUE TITLE
Orphaned code on united_states.py, commit c4a2a0f

### ISSUE THREAD

**Issue by Sudo-Rob** [dr-prodigy/python-holidays#619]
If I'm not mistaken, lines 378 through 381 are orphans.

![image](https://user-images.githubusercontent.com/56487711/153284524-96ecd921-8d2c-492d-9680-4de28693f4f2.png)

**Comment by dr-prodigy** [comment]
Hey @Sudo-Rob that's correct! I applied your suggested fix and released in beta.
Thx, cheers!
