### ISSUE TITLE
Confederate Memorial Day, AR

### ISSUE THREAD

**Issue by SideTrackedResearch** [dr-prodigy/python-holidays#632]
Arkansas does not recognize Confederate Memorial day as a state holiday.
Current Arkansas holidays:

January 1 . . . . . . . . . . . . . . . . . . . . . . . . . New Year’s Day (Observed on Friday December 31,2021)
January 17 . . . . . . . . . . . . . Dr. Martin Luther King Jr.’s Birthday
February 21 . . . . . . . . . . . . . . . George Washington’s Birthday and Daisy Gatson Bates Day
May 30 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Memorial Day
July 4 . . . . . . . . . . . . . . . . . . . . . . . . . . . . Independence Day
September 5 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . Labor Day
November 11 . . . . . . . . . . . . . . . . . . . . . . . . . . . . Veterans Day
November 24 . . . . . . . . . . . . . . . . . . . . . . Thanksgiving Day
December 24 . . . . . . . . . . . . . . . . . . . . . . . . . . Christmas Eve (Observed on Friday, December 23)
December 25 . . . . . . . . . . . . . . . . . . . . . . . . . . . Christmas Day (Observed on Monday, December 26)
[Holidays_2022.pdf](https://github.com/dr-prodigy/python-holidays/files/8112136/Holidays_2022.pdf)

**Comment by dr-prodigy** [comment]
hi, this is in fact already working, as you can see:
```
>>> import holidays
>>> import datetime
>>> x = holidays.US(subdiv='AK')
>>> x
holidays.country_holidays('US', subdiv='AK')
>>> datetime.date(2022,1,1) in x
True
>>> x
{datetime.date(2022, 1, 1): "New Year's Day", datetime.date(2022, 1, 17): 'Martin Luther King Jr. Day', datetime.date(2022, 2, 21): "Washington's Birthday", datetime.date(2022, 3, 28): "Seward's Day", datetime.date(2022, 5, 30): 'Memorial Day', datetime.date(2022, 6, 19): 'Juneteenth National Independence Day', datetime.date(2022, 6, 20): 'Juneteenth National Independence Day (Observed)', datetime.date(2022, 7, 4): 'Independence Day', datetime.date(2022, 9, 5): 'Labor Day', datetime.date(2022, 10, 18): 'Alaska Day', datetime.date(2022, 11, 11): 'Veterans Day', datetime.date(2022, 11, 24): 'Thanksgiving', datetime.date(2022, 12, 25): 'Christmas Day', datetime.date(2022, 12, 26): 'Christmas Day (Observed)'}
```
I suggest you to double check your init code to be sure you're setting up holidays for AK.
Closing, cheers! 👍

**Comment by SideTrackedResearch** [comment]
Well, Arkansas is AR and Alaska is AK. 
I do see the correct holidays in my calendar for AR now.
