### ISSUE TITLE
Australia QLD Duplicate Entries in 2020 for "The Royal Queensland Show"

### ISSUE THREAD

**Issue by gavingc** [dr-prodigy/python-holidays#635]
The duplicate appears in the output for holidays version==0.13.
A recent previous version actually had this holiday correctly moved.

Reference:
https://www.qld.gov.au/recreation/travel/holidays/queensland-public-holiday-dates-for-2020

Note that 2021 appears to produce the correct date output.
Although technically the holiday was repealed and replaced with "2021 People's long weekend".
https://www.qld.gov.au/recreation/travel/holidays/public

Code to replicate:
```python
import holidays

# Select: Autralia, QLD, and the years to generate.
startYear = 2020
endYear = 2020
hols = holidays.Australia(
    years=range(startYear, endYear + 1), subdiv="QLD", expand=False
)

hols.get_named("The Royal Queensland Show")
```

Output:
```bash
[datetime.date(2020, 8, 14), datetime.date(2020, 8, 12)]
```

**Comment by arkid15r** [comment]
Closing this as #923 has been merged into beta.
@gavingc thanks for reporting this!
