### ISSUE TITLE
Add Holidays for Liechtenstien (country)

### ISSUE THREAD

**Issue by gerdschadler** [dr-prodigy/python-holidays#650]
It would be great if you could add Liechtenstien.

      # Holidays Every Year same date 2022
      - '2022-01-01' #Neujahrstag
      - '2022-01-02' #Berchtoldstag
      - '2022-01-06' #Heilige Drei Konige
      - '2022-02-02' #Lichtmess
      - '2022-03-19' #Joseftag
      - '2022-05-01' #Tag der Arbeit
      - '2022-08-15' #Furstenfest (Staatsfeiertag)
      - '2022-09-08' #Maria Geburt
      - '2022-11-01' #Allerheiligen
      - '2022-12-08' #Maria Empfagnis
      - '2022-12-24' #Heiligabned
      - '2022-12-25' #1. Weihnachtstag
      - '2022-12-26' #2. Weihnachtstag
      - '2022-12-31' #Silvester
      # Holidays 2022
      - '2022-03-01' #Fasnachtsdienstag - https://en.wikipedia.org/wiki/Shrove_Tuesday
      - '2022-04-15' #Karfreitag
      - '2022-04-17' #Ostersonntag
      - '2022-04-18' #Ostermontag
      - '2022-05-26' #Christi Himmelfahrt
      - '2022-06-05' #Pfingstsonntag
      - '2022-06-06' #Pfingstmontag
      - '2022-06-16' #Fronleichnam

**Comment by PriyabrataSamantaray** [comment]
@gerdschadler and @dr-prodigy, I would like to contribute here.
The clarification needed is, the holidays listed are not matching to the list provided in the below link.
https://tourismus.li/en/our-country/about-liechtenstein/bank-holidays-in-liechtenstein/
May I know the trusted website to refer for the holidays and then to add in our holidays library.

**Comment by gerdschadler** [comment]
@PriyabrataSamantaray - Correct... here 
You're right. Here's an explanation.

In addition to the statutory public holidays, there are two other public holidays that can be considered paid public holidays on the basis of collective labor agreements between individual professional groups.

Candlemas February 2nd
Josefi March 19

In addition, the following public holidays are considered bank holidays* across the country

Berchtold's Day January 2nd
Shrove Tuesday 47 days before Easter
Good Friday Friday before Easter
Christmas Eve December 24th
New Year's Eve December 31st

* [https://www.llb.li/en/contact/bank-holidays](https://www.llb.li/en/contact/bank-holidays)

**Comment by PriyabrataSamantaray** [comment]
Thanks @gerdschadler for the clarification, I'll work on this issue and update here once it is ready for beta version.

**Comment by dr-prodigy** [comment]
Completed by @kasya , merged in beta. Closing, thx everyone
