### ISSUE TITLE
Add Holidays for Oman (country)

### ISSUE THREAD

**Issue by ammaralfarsi** [dr-prodigy/python-holidays#658]
i would like to contrubute and add Oman in the list

basically it is similar to UAE country with differ in few holidays and yes we are same in the Islamic holidays as well as we depend on moon for holidays decisions.

please let me know what is require from my end.

**Comment by dr-prodigy** [comment]
hi @ammaralfarsi thank you! you can then proceed in implementing it.
You will find all the required info here:
https://github.com/dr-prodigy/python-holidays/blob/master/CONTRIBUTING.rst
Thx, best 👍
