### ISSUE TITLE
Change day of "Pueblos Indigenas" for Chile

### ISSUE THREAD

**Issue by kev-dfs** [dr-prodigy/python-holidays#666]
The real day for  "Día Nacional de los Pueblos Indígenas" in Chile (CL) is the June/21

Link about "senado" of Chile.
https://www.senado.cl/noticias/pueblos-originarios/confirman-feriado-para-el-21-de-junio-como-dia-de-los-pueblos-indigenas

**Comment by dr-prodigy** [comment]
Hi @kev-dfs thx.
Although I confirm from 2021 on it seems like you mention, I unfortunately couldn't find a clear rule for the previous years:
https://www.timeanddate.com/holidays/chile/2022
Would you please clarify this (or even better, create a PR yourself)?

Thx again, cheers 👍

**Comment by aandrewsv** [comment]
Hello @dr-prodigy couldn't find a rule either but besides that don't really get why the holiday is set to June 19. The law indicates that the holiday will be the day of the winter solstice in the southern hemisphere every year and that day will always be either June 20 or 21.

Here is an official source of the law, and btw thank u very much for this library it has been prove very helpful to me 

https://www.bcn.cl/leychile/navegar?idNorma=1161743

**Comment by Nalguedo** [comment]
I've submitted the following PR -> https://github.com/dr-prodigy/python-holidays/pull/828
The holiday takes place on the same date as the solstice; by calculating the solstice date using the formulas from the book Astronomical Algorithms, we just need to adjust it to the Chile timezone UTC-3.
The full list is available here -> https://github.com/pavolgaj/AstroAlgorithms4Python
This approach doesn't require any extra dependencies, although if you consider adding https://pypi.org/project/astronomy-engine/ we can get the date using the astronomy-engine.

**Comment by dr-prodigy** [comment]
Just released on beta branch.. closing this, thanks everyone! 👍
