### ISSUE TITLE
ModuleNotFoundError: No module named 'holidays.financial'

### ISSUE THREAD

**Issue by Stiven-Jaramillo** [dr-prodigy/python-holidays#670]
Hi guys, today after upgrade holidays got that error, I cant re stablish it on the fly.

**Comment by dhuang** [comment]
+1 seeing this as well.

**Comment by jfgomez0912** [comment]
+1 darts uses `holidays.financial` and throws the same error. I had to set the version to 0.13

**Comment by dr-prodigy** [comment]
It should now be fixed and released as v.0.14.1: thanks everyone!
