### ISSUE TITLE
No "New Year" Holiday for Colombia in some years (2022,2023)

### ISSUE THREAD

**Issue by Gama8** [dr-prodigy/python-holidays#674]
Hi everyone, I'm testing the Python holiday library for Colombia.

col_holidays = holidays.country_holidays('CO')

But some years like 2022 and 2023 doesn't have the first holiday of the year "New Year".

Another years like 2020 or 2021 doesn't have this issue.

Thanks.

**Comment by bkthomps** [comment]
Apparently this is expected. The test code expects fixed holidays (for which there are 4, including New Year) to not be holidays if they fall on the weekend: https://github.com/dr-prodigy/python-holidays/blob/master/test/countries/test_colombia.py#L44

**Comment by bkthomps** [comment]
I've confirmed that they should fall on those days, but noticed some other errors in the colombia file. The law for bridging holidays to the next monday was enacted in 1983 among other things. I'll create a PR shortly.

**Comment by dr-prodigy** [comment]
Fixed with #676 .. Thx both! 👍
