### ISSUE TITLE
Custom holidays not iterable

### ISSUE THREAD

**Issue by steakhutzeee** [dr-prodigy/python-holidays#685]
Hello,

i added some holidays to the "IT" ones this way:

```
class my_holidays:
    def _populate(self, year):

        holidays.IT._populate(self, year)

        # Add custom holidays
        self[date(year, 6, 24)] = "San Giovanni Battista"
        self[date(year, 12, 31)] = "San Silvestro"
```

But when i try to call it:
Note: holidays is a personal custom list, current_day is a variable and i also tested it directly in the interpreter but issue is the same. No issue with the standard `it_holidays = holidays.IT()`

```
# Check if current day is an holiday
if x > 0 and current_day in my_holidays:
    holidays.append(
        (
           days_list[x],
           datetime.strptime(current_day, "%m/%d/%y").strftime("%d/%m/%Y"),
        )
    )
```

i receive the following error:

```
if x > 0 and current_day in my_holidays:
TypeError: argument of type 'type' is not iterable
```

Any idea what am i doing wrong?

Thanks!

**Comment by dr-prodigy** [comment]
Hi, 
I kindly ask you to follow the provided doc and, when possible, avoid opening project issues about specific implementation issues.
This said, in order to make it work, you should at least inherit your class from Italy class, like so (I'm from mobile so there could be some small error / typo):
```
...
class my_holidays (holidays.Italy):
...
```
Then, if your added holidays are valid for the whole Italy,

**Comment by dr-prodigy** [comment]
Hi, 
I kindly ask you to follow the provided doc and, when possible, avoid opening project issues about specific implementation issues.
This said, in order to make it work, you should at least inherit your class from Italy class, like so (I'm from mobile so there could be some small error / typo):
```
...
class my_holidays (holidays.Italy):
...
```
Then, if your added holidays are valid for the whole Italy,

**Comment by steakhutzeee** [comment]
Before implementing this in my personal code i tried the exact code from the documentation in the section "Creating custom holidays (or augmenting existing ones with private ones)" and got same issue discussed here [](https://github.com/dr-prodigy/python-holidays/issues/500)

That's why i used:

`class my_holidays:`

instead of:

`class my_holidays (holidays.Itay):`

If i use the code from the docs:

```
>>> import holidays
>>> from datetime import date
>>> class CorporateHolidays(holidays.US):
...     def _populate(self, year):
...             holidays.US._populate(self, year)
...             self[date(year, 7, 13)] = "Ninja Turtle Day"
```

```
>>> date(2014, 10, 14) in CorporateHolidays(country="US")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\holidays\countries\united_states.py", line 107, in __init__
    HolidayBase.__init__(self, **kwargs)
TypeError: HolidayBase.__init__() got an unexpected keyword argument 'country'
```

That is exactly the error from the link i provided.

If i try to follow the solution provided in the link:

```
>>> class CorporateHolidays():
...     def _populate(self, year):
...             holidays.US._populate(self, year)
...             self[date(year, 7, 13)] = "Ninja Turtle Day"
```

I get exactly the same issue i have in my custom code:

```
>>> date(2014, 10, 14) in CorporateHolidays()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'CorporateHolidays' is not iterable
```

So there is probably something i'm not doing right :/

**Comment by dr-prodigy** [comment]
At a further check, I confirm that specific example referred to is providing a wrong code: being already a country-inherited object, the subsequent call to `country="US"` is not valid, thus the first reported error.

Going to the second code, on the other hand, the inheritance is still obviously required: no examples in the doc is omitting it.

The correct code is then
```
import holidays
from datetime import date

class CorporateHolidays(holidays.US):
  def _populate(self, year):
    holidays.US._populate(self, year)
      self[date(year, 7, 13)] = "Ninja Turtle Day"

print (date(2014, 7, 13) in CorporateHolidays())
```

The doc will be fixed accordingly, thx for your clarifications!

**Comment by dr-prodigy** [comment]
The fix has been just pushed on beta.
It will be then published to https://python-holidays.readthedocs.io when merged on master, ie: when the next app official version (0.15) is released.
Closing this: pls reach out in case of further needs, thx.
