### ISSUE TITLE
Australia one-off public holiday

### ISSUE THREAD

**Issue by cozimapotato** [dr-prodigy/python-holidays#706]
Hi there,

Just thought I'd flag the one-off public holiday that Australia is getting across all states on the Thursday 2022-09-22, see below:

https://www.theguardian.com/australia-news/2022/sep/11/australia-to-have-public-holiday-to-mark-the-death-of-queen-elizabeth-ii-anthony-albanese-announces

Keep up the good work!

**Comment by dr-prodigy** [comment]
Hi @cozimapotato thank you: we have just sorted this out merging #699 . It is currently released in beta, and will be included in the next release.
Cheers! :+1:
