### ISSUE TITLE
New temporary public holiday in New Zealand

### ISSUE THREAD

**Issue by markhoneth** [dr-prodigy/python-holidays#708]
- New Zealand will mark the passing of Queen Elizabeth II with a _one-off_ public holiday on **Monday 26 September**. 
- The Public Holiday will be called **Queen Elizabeth II Memorial Day**. 
- Legislation will be passed next week to bring the holiday into force.

More information [here](https://www.beehive.govt.nz/release/public-holiday-26-september-mark-passing-queen-elizabeth-ii).

**Comment by dr-prodigy** [comment]
Hi @markhoneth thank you, today I've released in beta an update on this.
I'm closing this, please follow up in case of any review required.

Thanks, cheers
dr-p
