### ISSUE TITLE
Sovereign's Birthday updates for New Zealand

### ISSUE THREAD

**Issue by markhoneth** [dr-prodigy/python-holidays#709]
With the passing of Queen Elizabeth II the Sovereign's Birthday public holiday will be called **King's Birthday** from **2023** for _Charles III_. Also see #708 for new temporary holiday in 2022.

More information [here](https://www.employment.govt.nz/leave-and-holidays/public-holidays/public-holidays-and-anniversary-dates/).

**Comment by dr-prodigy** [comment]
Hi @markhoneth thank you, today I've released in beta an update on this.
I'm closing this, please follow up in case of any review required.

Thanks, cheers
dr-p
