### ISSUE TITLE
Improve `holidays.constants` multi-line import sorting

### ISSUE THREAD

**Issue by arkid15r** [dr-prodigy/python-holidays#732]
Keep week days and months multi-line imports ordered according to the date/time context (which is more readable taking into account the nature of python-holidays package).

```I would have dreamt to see those holidays.constants multi-line import move to the isort format (definitely nicer and more readable than the black's version).```

_Originally posted by @dr-prodigy in https://github.com/dr-prodigy/python-holidays/issues/722#issuecomment-1268560210_

**Comment by dr-prodigy** [comment]
Pls see #734 for possible further improvements.. thx!

**Comment by arkid15r** [comment]
Yep, will do! I appreciate your suggestions!

**Comment by arkid15r** [comment]
Closing as obsolete.
