### ISSUE TITLE
Some holidays of Uruguay are incorrect.

### ISSUE THREAD

**Issue by oteroalejandro** [dr-prodigy/python-holidays#745]
Hello.
Some holidays for Uruguay are incorrect.

- The Battle of stones was in May, 18.
- The Respect for Cultural Diversity Day or Columbus day is October, 12.

In Uruguay are 2 categories of holidays (laborables and not laborables). In the not laborable holidays nobody works while in the laborable holidays the work is optional.

The not laborables holidays are:
- 01/01
- 01/05
- 18/07
- 25/08
- 25/12

The rest of holidays are laborables, and depending of the day of the week, some of them are moved to earlier monday or to the next friday. The rule is:
- If the holiday is tuesday or wednesday, they moved to earlier monday.
- If the holiday is thursday, is moved to next friday.
- If the holiday is in monday or friday, doesn't move.

That is the reason of the error.
For example, the Battle of the Stones is the May, 18. In 2021 was tuesday and was moved to the earlier monday that was May, 17.

One exception to this rule is the November, 2 ("Día de los difuntos"). This holiday is laborable, but doesn't move.

Best regards.

**Comment by kasya** [comment]
@oteroalejandro  I'm working on this issue. Thanks for pointing out the problem.
One question:  do you get an extra day off (observance) if not laborable holiday falls on weekend?

**Comment by kasya** [comment]
By the way, this is what [Wikipedia](https://en.wikipedia.org/wiki/Public_holidays_in_Uruguay#Moveable_holidays) states:

According to Uruguayan Law 16,805 with modifications of Law 17,414, the holidays declared by law, subject to the commemoration of them, follow the following scheme (whose commemoration as “moveable holidays”):

- If coincide on Saturday, Sunday or Monday will be observed in those days.
- If occur on Tuesday or Wednesday, will be observed on Monday immediately preceding.
- If occur on Thursday or Friday shall be observed on the Monday immediately following

It is a bit different from your explanation. Could you please clarify this? Thanks!

**Comment by oteroalejandro** [comment]
Hi Kate.

In the case a not laborable holiday falls on weekend, we don't get any
extra day.



[image: Logo]
<https://mailtrack.io/trace/link/1198366dea37c3e1f186c6569157d85010525afa?url=https%3A%2F%2Fwww.acceleanation.com&userId=7259985&signature=f5b9c321d1b4c8b6>
*Cr. Alejandro Otero*
*Consulting Manager*
*e:* ***@***.***
*w:* acceleanation.com
<https://mailtrack.io/trace/link/796c3c61a2a904b5f2e5e6a20a7bcc6f31db93fe?url=https%3A%2F%2Fwww.acceleanation.com&userId=7259985&signature=034bc373cc95696f>
*m:* +598 99119120
Book a meeting with me: 15min
<https://mailtrack.io/trace/link/7d344c211d5d322a1276818422b980f22bbe6057?url=https%3A%2F%2Fcalendly.com%2Foteroalejandro%2F15min&userId=7259985&signature=e0a6ac9c0fbe139d>
 | 25min
<https://mailtrack.io/trace/link/2332a2f58c83ca7c5f312b106a0793f9a2a7c7fe?url=https%3A%2F%2Fcalendly.com%2Foteroalejandro%2F25min&userId=7259985&signature=56ab97f153373533>
 | 50min
<https://mailtrack.io/trace/link/cb411452873f7e8a99c7f015769f7fa632e58206?url=https%3A%2F%2Fcalendly.com%2Foteroalejandro%2F50min&userId=7259985&signature=02b6aca2a820a339>

**Comment by oteroalejandro** [comment]
Hi Kate.

I checked with colleagues, and wikipedia is right. If the holiday is
Thursday or Friday, it's moved to next monday.

Another thing... In addition to November 2, exceptions to the holiday
movement rules are on January 06 and June 19. These holidays do not move
despite being working days.

Thanks a lot for your work.
Best regards.






[image: Logo] <https://www.acceleanation.com>
*Cr. Alejandro Otero*
*Consulting Manager*
*e:* ***@***.***
*w:* acceleanation.com <https://www.acceleanation.com>
*m:* +598 99119120
Book a meeting with me: 15min <https://calendly.com/oteroalejandro/15min> |
25min <https://calendly.com/oteroalejandro/25min> | 50min
<https://calendly.com/oteroalejandro/50min>

**Comment by kasya** [comment]
> In addition to November 2, exceptions to the holiday movement rules are on January 06 and June 19. These holidays do not move despite being working days. Thanks a lot for your work. Best regards. >

Yes, I noticed that as well in Wikipedia. 
Thanks for the clarification!

**Comment by dr-prodigy** [comment]
Fixed by @kasya and merged in beta.. thx! 👍
