### ISSUE TITLE
Optimize Kst day lookup process

### ISSUE THREAD

**Issue by arkid15r** [dr-prodigy/python-holidays#768]
Replace while loops with `dateutil` logic:

The list of code parts to optimize:
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/angola.py#L63
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/botswana.py#L57
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/mozambique.py#L38
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/south_africa.py#L138
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/south_africa.py#L158
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/south_africa.py#L169
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/south_africa.py#L176
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/zimbabwe.py#L56
  - https://github.com/dr-prodigy/python-holidays/blob/a772f79327a64639ec1fe89c79165d585c3a9b3d/holidays/countries/zimbabwe.py#L67

**Comment by arkid15r** [comment]
Hey @KJhellico, would you like to look into this? 
For some reason I though may be interested :)

**Comment by KJhellico** [comment]
Definitely! 😋 I will look into it

**Comment by dr-prodigy** [comment]
#770 merged right now.. thank you both! 👍
