### ISSUE TITLE
Tree planting day in South Korea

### ISSUE THREAD

**Issue by Inundata** [dr-prodigy/python-holidays#788]
I found that there is an error about the tree-planting day.

This day was ruled out from the holiday after 2006.

However, the package still returns this day as a holiday on 2006-4-5 and 2007-4-5.

https://glaw.scourt.go.kr/wsjo/lawod/sjo190.do?contId=1680822#1668387535738 ← This is the Decree on which it is based.

Translating the Decree shortly, the Tree planting day and the Constitution day would be ruled out after 2006 and 2008, respectively.

**Comment by dr-prodigy** [comment]
@Inundata does #791 fix it? Pls let us know, thx

**Comment by arkid15r** [comment]
Fixed in https://github.com/dr-prodigy/python-holidays/pull/791/, closing this.
@Inundata thanks for reporting the issue!
