### ISSUE TITLE
Labour day in South Korea

### ISSUE THREAD

**Issue by Inundata** [dr-prodigy/python-holidays#789]
There is an error about Labour day in South Korea.

Labour day was a holiday on March 10, before 1994, and it changes to May 1 after 1994.

In the Package, Labour day was returned on May 1 even if it was before 1994.

https://elaw.klri.re.kr/kor_service/lawView.do?lang=ENG&hseq=23586 ← This is the Decree on which it is based.

**Comment by dr-prodigy** [comment]
@Inundata does #791 fix it? Pls let us know, thx

**Comment by arkid15r** [comment]
Also was fixed in #791, closing out.

Thanks everyone!
