### ISSUE TITLE
Hangeul day in South Korea

### ISSUE THREAD

**Issue by Inundata** [dr-prodigy/python-holidays#790]
I found that there is an error about the Hangeul day.

Originally, Hangeul day was a holiday, but during the period from 1991 to 2012, it was removed from the holiday.

After 2013, it was redesignated as a holiday again.

https://elaw.klri.re.kr/kor_service/lawView.do?hseq=59601&lang=ENG ← This is the Decree on which it is based.

The ADDENDUM <Presidential Decree No. 24273, Dec. 28, 2012> below in the Decree is notifying that Hanguel day would be redesignated as a holiday again.

I could not find the addendum in English, so I attached in Korean version(https://law.go.kr/LSW/lsInfoP.do?lsiSeq=234501&viewCls=lsRvsDocInfoR#).

**Comment by dr-prodigy** [comment]
@Inundata does #791 fix it? Pls let us know, thx

**Comment by Inundata** [comment]
@dr-prodigy, #791 does not fix yet 😥
I have upgraded the package version to 0.17.2, but the errors still exist.

I have attached the screenshots.
<img width="420" alt="labour" src="https://user-images.githubusercontent.com/70585698/207775223-bdc871aa-e511-4bf2-9f1c-653106558ea3.PNG">
<img width="256" alt="tree" src="https://user-images.githubuserconten
<img width="267" alt="hangeul" src="https://user-images.githubusercontent.com/70585698/207775239-ca136275-d4d5-4ff1-b0c6-089cf4efad7e.PNG">
t.com/70585698/207775233-18cfa524-cafc-4c5a-a238-e7c61cc21a7c.PNG">

**Comment by Inundata** [comment]
I clicked the wrong button. Sorry. I reopen it.

**Comment by dr-prodigy** [comment]
Thank you, closing this then! Cheers :+1:
