### ISSUE TITLE
South Africa new public holiday 27th December 2022

### ISSUE THREAD

**Issue by csloz** [dr-prodigy/python-holidays#838]
27th of December is a public holiday in South Africa

Proof:
https://www.gov.za/speeches/president-cyril-ramaphosa-declares-27-december-public-holiday-8-dec-2022-0000
South Africans will enjoy Tuesday, 27 December 2022, as a public holiday in lieu of Christmas Day falling on a Sunday.

This doesn't seem to be updated in the current holidays db.  Can it be added?
---------
import holidays #Version (0.17.2)
sa_holidays =  holidays.country_holidays('ZA')  
'2022-12-27' in sa_holidays

False

**Comment by csloz** [comment]
Have created a pull request with the change 
https://github.com/dr-prodigy/python-holidays/pull/839

**Comment by dr-prodigy** [comment]
Fixed in beta with #848 .. closing this, thank you! :+1:
