### ISSUE TITLE
Multiple holidays delimiter

### ISSUE THREAD

**Issue by KJhellico** [dr-prodigy/python-holidays#873]
Now we use comma (,) as delimiter when several holidays fall on the same date. But some countries have holidays with comma in name (BR, BG, LT, TR). For these cases `get_list()` function does not work correctly. We need to global change delimiter symbol (e.g. to semicolon) or introduce something like `self.delimiter` and change it for these countries.

**Comment by arkid15r** [comment]
Thanks for reporting this issue @KJhellico!
The fix has been merged into beta.
