### ISSUE TITLE
Today (2022/01/02) is not holiday in Madrid (province: MD), Spain

### ISSUE THREAD

**Issue by ifajardoj** [dr-prodigy/python-holidays#885]
Hi, the workday_sensor is returning Off, holiday today January 2 for Madrid (MD), Spain. That's wrong. Today is working day.

**Comment by flipdream** [comment]
Hello, also Spain (ES) and Autonomous community: CT (Catalonia), January 2 are working days.

**Comment by KJhellico** [comment]
Seems it resolved by #902

**Comment by arkid15r** [comment]
The fix was merged into beta. Closing this out.

@ifajardoj, @flipdream  thank you for bringing this up!
