### ISSUE TITLE
Holidays in Panamá

### ISSUE THREAD

**Issue by Afroefras** [dr-prodigy/python-holidays#907]
Hi there!

I'm very thankful for this project, it had really helped me :)

I did not find the Panamá holidays list, so I've been wondering if you have an special format to add a new country or is it a different process?
I've read the [contributing guidelines](https://github.com/dr-prodigy/python-holidays/blob/39f3538764e7413c3b7a15426e065294238ce493/CONTRIBUTING.rst) but I am not sure if this applies to this kind of request.

**Comment by arkid15r** [comment]
Hey @Afroefras, Panama holidays support PR has been merged into beta.
@KJhellico went ahead and implemented it.

Closing this out.
