### ISSUE TITLE
February Bank Holiday in Ireland calculated wrong

### ISSUE THREAD

**Issue by kenguest** [dr-prodigy/python-holidays#917]
Today -1st February - is incorrectly marked as a holiday in Ireland.
The bank holiday this year is on the 6th - the first Monday of the month.
It should only be marked as a bank holiday on the 1st if the day is a Friday.

https://www.irishcentral.com/roots/st-brigids-day-traditions

**Comment by arkid15r** [comment]
Updated in https://github.com/dr-prodigy/python-holidays/pull/953

Thank you!
