### ISSUE TITLE
Version 0.19 throws ImportError on hijri_converter.ummalqura

### ISSUE THREAD

**Issue by inputvalidation** [dr-prodigy/python-holidays#918]
I have just upgraded to python-holidays 0.19 and have no restrictions on hijri_converter in my venv requirements, but holidays is now throwing an ImportError:

```
cannot import name 'GREGORIAN_RANGE' from 'hijri_converter.ummalqura'
```

It happens in holidays/utils.py:28. hijri_converter, as installed by pip, is on this version:

```
# pip freeze | grep hijri
hijri-converter==2.1.1
```

... looking at their repo they're on 2.2.4.

**Comment by arkid15r** [comment]
Hi @inputvalidation, thanks for bringing this up.

I tried to reproduce the error:

`virtualenv venv && source venv/bin/activate`

> created virtual environment CPython3.9.12.final.0-64 in 157ms
>   creator CPython3Posix(dest=/Users/ark/Dev/ph-test/venv, clear=False, no_vcs_ignore=False, global=False)
>   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/ark/Library/Application Support/virtualenv)
>     added seed packages: pip==22.3.1, setuptools==65.6.3, wheel==0.38.4
>   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator


`pip install holidays==0.19`

> Collecting holidays==0.19
>   Using cached holidays-0.19-py3-none-any.whl (208 kB)
> Collecting korean-lunar-calendar
>   Using cached korean_lunar_calendar-0.3.1-py3-none-any.whl (9.0 kB)
> Collecting convertdate>=2.3.0
>   Using cached convertdate-2.4.0-py3-none-any.whl (47 kB)
> Collecting hijri-converter
>   Using cached hijri_converter-2.2.4-py3-none-any.whl (14 kB)
> Collecting PyMeeus
>   Using cached PyMeeus-0.5.12-py3-none-any.whl
> Collecting python-dateutil
>   Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
> Collecting six>=1.5
>   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
> Installing collected packages: PyMeeus, korean-lunar-calendar, six, hijri-converter, convertdate, python-dateutil, holidays
> Successfully installed PyMeeus-0.5.12 convertdate-2.4.0 hijri-converter-2.2.4 holidays-0.19 korean-lunar-calendar-0.3.1 python-dateutil-2.8.2 six-1.16.0

`python -c "from holidays import utils"` worked fine.


Then I pinned hijri-converter to 2.1.1

`pip freeze`
> convertdate==2.4.0
> hijri-converter==2.1.1
> holidays==0.19
> korean-lunar-calendar==0.3.1
> PyMeeus==0.5.12
> python-dateutil==2.8.2
> six==1.16.0
> 

and successfully reproduced the error message

`python -c "from holidays import utils"`

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/ark/Dev/ph-test/venv/lib/python3.9/site-packages/holidays/__init__.py", line 13, in <module>
>     from holidays.countries import *
>   File "/Users/ark/Dev/ph-test/venv/lib/python3.9/site-packages/holidays/countries/__init__.py", line 12, in <module>
>     from .albania import AL, ALB, Albania
>   File "/Users/ark/Dev/ph-test/venv/lib/python3.9/site-packages/holidays/countries/albania.py", line 20, in <module>
>     from holidays.utils import _islamic_to_gre
>   File "/Users/ark/Dev/ph-test/venv/lib/python3.9/site-packages/holidays/utils.py", line 28, in <module>
>     from hijri_converter.ummalqura import GREGORIAN_RANGE
> ImportError: cannot import name 'GREGORIAN_RANGE' from 'hijri_converter.ummalqura' (/Users/ark/Dev/ph-test/venv/lib/python3.9/site-packages/hijri_converter/ummalqura.py)

So a workaround would be `pip install -U hijri-converter`. 
A permanent fix may require setting specific versions for python-holidays dependencies (we'll look into this option).

Please let me know if you have questions/suggestion regarding this issue.

Thank you!

**Comment by arkid15r** [comment]
Closing this out. Please let me know if you need additional assistance with the issue.
