### ISSUE TITLE
Python 3.12 DeprecationWarning: `find_module()`, `FileFinder.find_loader()`, `load_module()`

### ISSUE THREAD

**Issue by PPsyrius** [dr-prodigy/python-holidays#948]
This is the result from running `python -m pytest --cov-report term-missing .` on the `beta` branch:

```yml
<frozen importlib._bootstrap_external>:629: 119 warnings
  <frozen importlib._bootstrap_external>:629: DeprecationWarning: find_module() is deprecated and slated for removal in Python 3.12; use find_spec() instead

<frozen importlib._bootstrap_external>:1591: 119 warnings
  <frozen importlib._bootstrap_external>:1591: DeprecationWarning: FileFinder.find_loader() is deprecated and slated for removal in Python 3.12; use find_spec() instead

<frozen importlib._bootstrap>:283: 119 warnings
  <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
```

From some quick checks, switching to the method mentioned in the warning above should keep us compatible with Python 3.4+  - though judging from coverall tests; we only aim for version 3.7 and above anyway.

**Comment by mborsetti** [comment]
Incidentally, this may be a good time to also think about the architecture as it regards to performance. 

We advertise this library as "fast, efficient", and is performance or memory footprint affected by loading every single class for every single country (that's 340+ classes) even if the user needs holidays only for a single country, which I assume this to be 90%+ of use cases? What about on small footprints (e.g. Raspberry Pi)? I would assume so, but am not very familiar with Python innards.

If so, are there architectures that we can implement to maximize load performance especially when only one country is needed?

**Comment by arkid15r** [comment]
Resolved in https://github.com/dr-prodigy/python-holidays/pull/992.
