### ISSUE TITLE
Update Mexico holidays

### ISSUE THREAD

**Issue by jahirfiquitiva** [dr-prodigy/python-holidays#976]
According to this official document from the Mexico government (https://www.gob.mx/profedet/articulos/sabes-cuales-son-los-dias-de-descanso-obligatorios-163134?idiom=es) (in Spanish) New Year's and Independence Day are not re-calculated even if they happen on a weekend day

From the list in the doc, holidays should be:
1. January 1st
2. February 5th, or the first Monday in February
3. March 21st, or the third Monday in March
4. May 1st
5. September 16th
6. November 20th, or the third Monday in November
7. Every 6 years, December 1st, corresponding to `Change of Federal Government`
8. December 25th

I've created a Pull Request #977 trying to help update these, but I'm not sure how to fix the tests, so I'd appreciate it if you could take a look.

Thanks!

**Comment by arkid15r** [comment]
https://github.com/dr-prodigy/python-holidays/pull/980 has been merged into v0.21 beta.
Thank you for making python-holidays better!
